### ISSUE TITLE
Save Password For A Moment 

### ISSUE THREAD

**Issue by albertwh1te** [jrnl-org/jrnl#1008]
### Use Case/Motivation

Entering the password every time is great pain.  It is possible that save the password for a moment (three minutes or five minutes ?) And in this period, user can edit or view their diary without entering the password.

**Comment by wren** [comment]
Hi, @MarkWh1te!

Normally, jrnl relies on keyrings to provide this functionality. Most keyrings have options to allow you to keep using the keyring entry for some amount of minutes before prompting for a password again.

If you could give us some more information about your system, we might be able to help you figure out how to best accomplish your goal.

**Comment by albertwh1te** [comment]
@wren Thanks for the quick reply! By the way, it works perfectly!
I use Linux(Ubuntu & Centos) and Mac OS.

**Comment by wren** [comment]
@MarkWh1te It sounds like you got it figured out, I'm closing this ticket. But please let us know if you still need any help.
