### ISSUE TITLE
Tests don't catch missing dependencies that are included in dev

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#1013]
## Bug Report

So, #1011 happened recently. That patches the fact that we shipped v2.4.4 with a missing dependency (`packaging`). The reason our tests didn't catch it is because that same dependency is required by one of our dev dependencies. And since our tests have the test environment loaded, the dependency was present. This is a problem because we're not testing the actual build.

### Environment
  - Testing environment (travis, local dev, etc)

### Current Behavior
Runs tests on a dev build

### Expected Behavior
At some point, the tests should be run against an actual packaged build.

### Repro Steps
See jrnl v2.4.4

**Comment by micahellison** [comment]
@wren and I talked a little about how to implement this today. It doesn't seem like there's a straightforward way to run the behave tests without dev dependencies, but it might make sense to whip up a few basic tests to be runnable from the command line itself. This would have the added benefit of allowing package managers to run automated tests when installing jrnl.

In our CI, we could use a tool like [tox](https://tox.readthedocs.io/en/latest/) to execute those tests.
