### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1017]
## Feature Request

It will soon be time to officially support Python 3.9. The final beta came out recently and [the release candidate phase begins this month](https://pythoninsider.blogspot.com/2020/07/python-385-released-as-security-hotfix.html). It would be nice to support the official release in a timely manner, especially since we've just deprecated 3.6.

This change should involve:
* documentation
* Travis CI builds
* poetry
* Perhaps some other things (it would be worth searching the code base for "3.8")

**Comment by wren** [comment]
We should probably add 3.9 tests to the suite sooner, and mark them as `allow_failures`.
