### ISSUE TITLE
Can't save password to keychain when running --encrypt on already-encrypted journal

### ISSUE THREAD

**Issue by iedd** [jrnl-org/jrnl#1021]
### Affected Page(s)
https://jrnl.sh/encryption/#storing-passwords-in-your-keychain

### What Could Be Better?
In the situation where the user has generated a new keychain in place of the old one, it is not sufficient to simply run jrnl --encrypt on an already-encrypted journal. The user must run jrnl --decrypt before encrypting again, in order to access the prompt to store the password on the keychain.

Thanks for your hard work and for this great tool!

**Comment by wren** [comment]
@iedd Thanks for the report, and for the kind words!

Just to clarify, is this the situation you're talking about?

1. Encrypt a journal
2. Store password in keychain
3. Delete keychain
4. Make new blank keychain
5. Attempt to access the encrypted journal

Is that right?

**Comment by iedd** [comment]
That is correct. In the situation you describe, the user will be prompted for the password in order to access the journal. In order to avoid the prompt and add it to the keychain, you must decrypt/re-encrypt.
