### ISSUE TITLE
Linux nano editor

### ISSUE THREAD

**Issue by sparks56** [jrnl-org/jrnl#1030]
### Environment
jrnl: v2.4.5
Python: 3.7.7 (default, Jun 28 2020, 13:01:52) 
[GCC 7.5.0]
OS: Linux 5.3.0-59-generic
  - Jrnl `--diagnostic` output: 
  - Install method:

**Comment by wren** [comment]
Hi, can you please fill out the rest of the issue template? Especially the "What are you trying to do?" section. It'll help us give you the support you need.

Thanks!

**Comment by wren** [comment]
Closing for now. Please comment if you have more info.
