### ISSUE TITLE
Password Prompt Issue

### ISSUE THREAD

**Issue by stockphrase** [jrnl-org/jrnl#1034]
### Environment
- Using jrnl on Pop OS 20.04

```
DEBUG    jrnl.install Reading configuration from file /home/alan/.config/jrnl/jrnl.yaml
DEBUG    jrnl.cli     Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': False, 'default_minute': False, 'editor': 'gedit -w', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'culture': '/home/alan/Sync/Journal/culture.md', 'default': {'encrypt': True, 'journal': '/home/alan/Sync/Journal/journal.md'}, 'quotes': '/home/alan/Sync/Journal/quotes.md', 'rental': '/home/alan/Sync/Journal/rental.md', 'work': '/home/alan/Sync/Journal/work.md'}, 'linewrap': 80, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y/%m/%d %I:%M %p', 'version': 'v2.4'}"
DEBUG    jrnl.util    Updating configuration with specific journal overrides {'encrypt': True, 'journal': '/home/alan/Sync/Journal/journal.md'}
DEBUG    jrnl.cli     Using journal "default"
```
- Install method: PIP

### What are you trying to do?
I encrypted my default journal file with a password, but backed up the file beforehand in case of accident. Later, I decided to not use encryption and replaced the encrypted file with the backup. Now jrnl requests a password before it will allow me to make a new journal entry, and the password is rejected (it is emphatically correct, however). I am trying to make jrnl work without the password or encryption again. 

### What have you tried?
- I ensured that my `.jrnl_config` file is set to "false" for encryption. The default file I had backed up is unencrypted and can be viewed in a text editor fine. I can see from the debug above that encryption is still enabled somewhere; do I need to edit the setting in `jrnl.util`?

- I uninstalled jrnl and reinstalled it with pip3. Same issue remains.

Thanks for any pointers.

**Comment by wren** [comment]
Hi, thanks for the report. 

It looks like you're editing the old config file (`.jrnl_config` is from jrnl v1). As you can see in the debug logs that you pasted, the correct config file to edit is `/home/alan/.config/jrnl/jrnl.yaml`. Can you please change the `encrypt` setting in that file and see if jrnl reads your journal correctly?

**Comment by stockphrase** [comment]
@wren That was indeed it. I had no idea there was a different config file in the new version. Thank you for your help.
