### ISSUE TITLE
Vim editor for Windows (PowerShell)

### ISSUE THREAD

**Issue by jimmyhess** [jrnl-org/jrnl#1036]
I am trying to set vim as the editor for jrnl on Windows (not WSL).

### Environment

jrnl: v2.4.5
Python: 3.7.7
OS: Windows 10

Installed via pipx

### What have you tried?

`editor: vim`

Config file is successfully loaded
Vim is installed and runs with `vim` command in PowerShell

The following error occurs when running `jrnl`

```
[WinError 2] The system cannot find the file specified

Please check the 'editor' key in your config file for errors:
    'vim'
```

### Other Information

I can get gvim to work with:
`editor: C:\Program Files (x86)\Vim\vim82\gvim.exe`

However, I want to use vim inside of PowerShell for jrnl entry

I got it working ok with WSL2 & Ubuntu on another machine but jrnl does not seem to support the `wsl` command from PowerShell so it requires an extra step to run (`ubuntu` > `jrnl` instead of a single command `wsl jrnl`).

**Comment by micahellison** [comment]
Hi there, when you're in PowerShell, could you run `Get-Command vim` then use the full path of vim as displayed under the "Source" column? I think that should fix this issue. I know path environment variables in Windows can be a bit inconsistent from one context to another and I suspect that's the problem.

Alternatively, jrnl does work when called from the WSL command, but there can be some issues with WSL not getting all the Linux paths when run from PowerShell or Windows Command Prompt. For instance, `wsl jrnl` doesn't work for me, but if I open up wsl then run `which jrnl` and use that full path to jrnl in my wsl command from PowerShell, it works fine.

**Comment by jimmyhess** [comment]
Use `Get-Command vim` to find full path
Update yaml with full path (C:\Windows\vim.bat)
It works!

Thanks @micahellison
