### ISSUE TITLE
Error switching on encryption

### ISSUE THREAD

**Issue by johnr365** [jrnl-org/jrnl#1047]
### Environment

  - Jrnl `--diagnostic` output: 
jrnl: v2.4.5
**Python: 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
OS: Darwin 19.6.0**
  - Install method: 
**brew**

### What are you trying to do?
Trying to run 'jrnl --encrypt'
### What have you tried?
Haven't tried anything yet, as I'm unsure what to do.
### Other Information
This is the error I'm getting:

Macbook terminal: jrnl --encrypt
Enter password for new journal: 
Enter password again: 
Do you want to store the password in your keychain? [Y/n] n
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 33, in <module>
    sys.exit(load_entry_point('jrnl==2.4.5', 'console_scripts', 'jrnl')())
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 467, in run
    encrypt(journal, filename=args.encrypt)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 262, in encrypt
    new_journal.write(filename)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 95, in write
    self._store(filename, text)
  File "/usr/local/Cellar/jrnl/2.4.5/libexec/lib/python3.8/site-packages/jrnl/EncryptedJournal.py", line 87, in _store
    with open(filename, "wb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/user/Dropbox/Documents/Journal/jrnl-folder'

----
**Thanks in advance for any clues as to how to fix this issue! Would love to use the app, but don't feel comfortable using it without first having encryption switched on.**

**Comment by wren** [comment]
Hi! Thanks for filing this issue.

It looks like you're using a folder journal (rather than the default single-file journal). Unfortunately, the folder journal type doesn't support encryption yet. If you point jrnl at a single file (like `/Users/user/Dropbox/Documents/Journal/jrnl.txt` or whatever), then the encryption should work. This is work we're planning to do, but need to fix up some issues with the different journal types first.

**Comment by johnr365** [comment]
Hi @wren - appreciate the quick reply.

Ok, fantastic, can tell it to use a single file instead.

That being said, perhaps in the interim of adding folder encryption functionality, it's possible to output an error message that explains this?

It might help newbies like myself who weren't aware.

Anyhow, it's all more work either way, and there's finite resources.

Again, appreciate the quick reply, and the fantastic looking tool. I say looking, because I haven't got far into using it yet!
