### ISSUE TITLE
Extra error when writing empty entry

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1048]
### Environment
  - Jrnl `--diagnostic` output: 
```
jrnl: v2.4.5
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
OS: Windows 10
```
  - Install method: latest from `develop`, running w/ `poetry shell`

### Current Behavior
I'm now getting an error message when trying to add an empty entry, beyond the usual `[Nothing saved to file]` message:

```
C:\dev\jrnl>jrnl
[Nothing saved to file]
ERROR    root         Write mode: couldn't get raw text
```
### Expected Behavior
Should just be seeing: `[Nothing saved to file]`

### Repro Steps
* run `jrnl` with no parameters
* If using an editor, close your editor. Or if using console input, press Ctrl+Z to end the input

### Other Information

I don't think this is related to my development environment (like some sort of verbose logging variable?), but please let me know if it is.

**Comment by antanasb** [comment]
No such behavior here:
$ jrnl
[Nothing saved to file]
$ jrnl --diagnostic
jrnl: v2.4.5
Python: 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
OS Ubuntu 18.04.5 LTS

**Comment by wren** [comment]
Yeah, I don't see it on v2.4.5 either. Maybe this is running from source on the develop branch?
