### ISSUE TITLE
Decryption fails on previously created jrnl after each version update

### ISSUE THREAD

**Issue by hrafnthor** [jrnl-org/jrnl#1055]
## Bug Report

Hi, have been using jrnl now for a couple of years and on multiple machines. I have noticed that jrnl is consistently unable to decrypt files after I update to a new version, and in every instance I have needed to decrypt the files either using the previous version first.

I just migrated from the 2.0.1 version to the latest 2.4.5 and sadly there was no change in behaviour, I am again unable to decrypt my file and will have to go through the my standard routine.

I can see the stored password is on the system keyring and the configuration is unmodified.

The new version is able to create a new jrnl file, encrypt it (and hey! confirmation of password! nice!) and the new password is on the keyring now. Decryption works without flaw on the new one.

### Environment

jrnl: v2.4.5
Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
OS: Linux 5.4.0-48-generic

Previous jrnl version (2.0.1) was installed under Ubuntu 18.04 using pip.

The machine has now been updated to Ubuntu 20.04, the previous pip version was scrubbed and the current jrnl version (2.4.5) was installed using pipx as per instructions on your webpage.

### Current Behavior

Decryption of jrnl file created using previous versions of the software is not working as the given password is claimed to be incorrect (even though it is identical to the one currently stored in the keychain)

### Expected Behavior

Decryption of jrnl files should be consistent between versions of the software.

### Repro Steps

As far as steps go, this is what 
1. Create a new jrnl file using jrnl version 2.0.1
2. Add some values to it.
3. Encrypt it and store to the system keychain
4. Remove jrnl from the system, but keep configuration yaml
5. set up pipx
6. Install jrnl version 2.4.5 using pipx
7. Attempt to decrypt.

**Comment by hrafnthor** [comment]
I just now attempted to use the decryption script that you have on your webage, but only got a error regarding the IV not being 16 bytes long:

```
Traceback (most recent call last):
  File "jrnl_decryptor.py", line 19, in <module>
    crypto = AES.new(key, AES.MODE_CBC, ciphertext[:16])
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long
```

**Comment by hrafnthor** [comment]
Just noticed in the documentation for the decryption scrip that the IV is stored at the front of the file, so looked at it and saw that there had been a addition made straight to the file. I removed the tainted file and replaced it with a unmodified backup and now I receive the following error:

```
Traceback (most recent call last):
  File "jrnl_decryptor.py", line 20, in <module>
    plain = crypto.decrypt(ciphertext[16:])
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

**Comment by hrafnthor** [comment]
I was able to remedy the decode issue by moving the file that I previously attempted to decode (but got a multiples of 16 error on) over onto a Mac and using the latest jrnl version 2.4.5 installed through Homebrew I was able to decrypt just fine.

So the file was not the issue, but a clean install of jrnl v 2.4.5 through pipx refused to work correctly on a Ubuntu 20.04 system.

**Comment by wren** [comment]
Hrmm, this is a weird one. Would you mind running this with `--debug` on Ubuntu and paste the logs?

We haven't changed the encryption since v2.0, and haven't had any similar reports on any versions.

**Comment by hrafnthor** [comment]
I ran the following command `jrnl --decrypt --debug` using version 2.4.5 on a backup of a file previously decrypted using version 2.0.1 and got the following:

```
DEBUG    jrnl.install Reading configuration from file <PATH_REMOVED>.config/jrnl/jrnl.yaml
DEBUG    jrnl.cli     Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': 'nano', 'encrypt': True, 'highlight': True, 'indent_character': '|', 'journals': {'default': {'encrypt': True, 'journal': '<PATH_REMOVED>'}}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.4.5'}"
DEBUG    jrnl.util    Updating configuration with specific journal overrides {'encrypt': False, 'journal': '<PATH_REMOVED>'}
DEBUG    jrnl.cli     Using journal "default"
DEBUG    jrnl.Journal opened PlainJournal with 1 entries
DEBUG    jrnl.Journal Imported 1 entries from PlainJournal to PlainJournal
Journal decrypted to <PATH_REMOVED>
```

Now the file was not decrypted, but I see that the encrypted content has now been prefixed with a timestamp `[2020-10-17 16:15] gAAAAABenMg_j....`

**Comment by micahellison** [comment]
I tried to reproduce the seven steps at the root of this issue with Ubuntu 18.04.2 (in WSL) starting with jrnl 2.0.1 then 2.4.5, but I was still able to encrypt and decrypt without errors.

I'm really not sure what's going on here, though from your latest post, it looks like it has somehow encrypted it twice, as if it was first encrypted, then added to as if it were an unencrypted file, then encrypted again. It might be salvageable with that timestamp prefix removed, but I'm really not sure.

**Comment by wren** [comment]
I can't seem to repro this with the steps above. We haven't change the encryption since v2.0 (and this would be a significant enough change to go to v3.0 if we changed it again).

I've been racking my brain about this one all week, and just can't think of what would cause this.

My best guess is hinted at in your last comment above. It looks like the file was encrypted twice. Could that be the case? I'm thinking since you have two config files syncing, it's possible that they got out of sync with the file at some point, and the file ended up double-encrypted. This would explain why the decrypt command appears to work, and adds a timestamp, but we still have encrypted content.

You could verify this by comparing the encrypted data before and after running `--decrypt`. If it's different (but still encrypted), then it would suggest that the decrypt command is actually working, but the file is double-encrypted. If it's the same, but with an added timestamp, then we have more research to do.

**Comment by hrafnthor** [comment]
Thank you for the follow up, and sorry for the late reply on my end.

In the interem between filing this issue initially I have actually wiped and rebuilt my whole setup from scratch. Using jrnl versions 2.0.1 and 2.4.5 I am able to decrypt the old backup without issue today. I am not sure what may have been happening but what ever the issue was I am unable to reproduce it again.

This may be due to changes in the encryption scheme between these versions (or due to some time based mechanism in the methods used for the encryption) but there is a difference in the encrypted payload based on which version is used:

- I used an unmodified backup of an jrnl file encrypted with password X using version 2.0.1 of jrnl
- I duplicated the file
- Using the currently installed version 2.4.5 of jrnl I decrypted one of the files using password X.
- I then encrypted the decrypted file, without modifying it in any way (nor opening it), using the same password X.
- Running diff old_encrypted_copy new_encrypted_copy I see that the whole contents is different.
- Using my new setup I am not having any issues decrypting the files, neither the old copy nor the new one.

**Comment by wren** [comment]
@Hrafnthor No worries about timing, and I'm glad everything seems fine now.

For the encryption, I can assure you that we've been using the same [well-established library](https://pypi.org/project/cryptography/) since v2.0. I can see where your concern comes from though, seeing the different payloads the way you're describing. This happens because that library adds a timestamp on encryption. You can see an example of this by doing the same experiment above, but using the same version of `jrnl` both times (basically re-encrypt with the same version), and you'll see that the payloads are different even with the same version of `jrnl`.

Hopefully this has assuaged your fears, but please let us know if you have any other questions or concerns.

**Comment by hrafnthor** [comment]
@wren That would explain it then :)

Thank you for the assistance!
