### ISSUE TITLE
Search for entries with no tags or stars with `-not -starred` and `-not -tagged`

### ISSUE THREAD

**Issue by fourjay** [jrnl-org/jrnl#1057]
### Use Case/Motivation
I've moved to leveraging tags more seriously. 
I'd like be able to view/edit entries that are not tagged to (potentially) tag the entries
Another usage, untagged entries have an implicit "empty" tag, that could be part of a tagging system.
My current usage starts to emulate that, with untagged entries functioning as notes

### Example Usage
``jrnl -untagged``
### Other information
I've hacked together a shelled out (to awk) version, that "works"
``jrnl -s -not $(jrnl --tags | awk '/@/ {printf "%s ", $1}'``
It's ugly, as the resulting command line could be very long.
But this seems like it could/should be a core feature :-)

**Comment by wren** [comment]
Hi, and thank you for sending us an issue. I think this is a good idea, and I think this also applies to starred entries. I'm not sure what the syntax should look like, though. 

There's the suggested `-untagged`, which implies a `-tagged` to match `-starred`, and also an `-unstarred`. Maybe `-not-tagged`? Or maybe `-has-tag` and `-no-tag`?

We could also potentially accomplish this by leveraging the already existing `-not`. So, then maybe something like `-starred` and `-not -starred` would work as expected?

What do you think, @micahellison?

**Comment by micahellison** [comment]
I agree that this is a good idea. The `-not -tagged` and `-not -starred` approaches feel intuitive to me, and like there is less of a cognitive load for the user than adding more unique keywords. It makes sense to string them together.
