### ISSUE TITLE
Allow custom file extension for `jrnl --edit` command

### ISSUE THREAD

**Issue by rizaon** [jrnl-org/jrnl#1059]
## Feature Request
Currently, `jrnl --edit` comand will open temporary `.txt` file using user preferred editor.
https://github.com/jrnl-org/jrnl/blob/4ee4f38/jrnl/editor.py#L15
It will be great if there is a config to specify the file extension to use other than `.txt`.

### Use Case/Motivation
Some editor has support for text highlighting depending on what is the file extension, such as markdown-mode (`.md`) or org-mode (`.org`) in emacs.
Allowing user to specify the preferred file extension to use in this edit command will in turn let the editor to display the right text highlighting.

**Comment by wren** [comment]
This is a good idea. Should we add a config value. What would we name it?

Maybe we can just use the `template` field we already have? We could just copy the extension that the template has (and allow a blank template, too, in case people just want to give an extension without a full template).

**Comment by micahellison** [comment]
I also like using the `template` field for to resolve this.

We were just talking about this today and toying with the idea of using the whole template file name as a suffix to the temporary file name when editing. So if, for instance, a template is named `mytemplate.jrnl` the temporary file could look like: `jrnlmf1p_rgj-mytemplate.jrnl`

This would solve this issue, while also making temporary jrnl entries a little bit more identifiable in editors for people such as myself that have waaaay too many tabs open all the time.
