### ISSUE TITLE
Junk Entry added after each of my Jrnl Entries - 'SMS Backup & Restore Upload Test was successful.' 

### ISSUE THREAD

**Issue by jahamed** [jrnl-org/jrnl#1064]
### Environment

  - Jrnl `--diagnostic` output: 

> jrnl: v2.4.5
Python: 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
OS: Darwin 19.6.0

  - Install method: 

homebrew

### What are you trying to do?

Every time I add a new entry to my default jrnl in my Hyper Terminal it seems to be adding a new entry immediately after I exit the jrnl writing with Cntrl + D

>❯ jrnl -n 5
>2020-10-27 16:02 SMS Backup & Restore Upload Test was successful.

>2020-10-27 16:02 dfasfaf

>2020-10-27 16:02 SMS Backup & Restore Upload Test was successful.

>2020-10-27 16:02 history

>2020-10-27 16:02 SMS Backup & Restore Upload Test was successful.

### What have you tried?

Tried upgrading with Homebrew, didn't fix it.

>Updating Homebrew...
==> Upgrading 1 outdated package:
jrnl 2.4.5 -> 2.4.5_1
==> Upgrading jrnl 2.4.5 -> 2.4.5_1 

### Other Information

Not yet, a little stumped on this one :/.

**Comment by wren** [comment]
This is kind of a weird one, and I think we need a little more info to help. Can you run jrnl in another terminal to see if you still get the problem? Also, can you give an example of exactly what you type step by step (and use the `--debug` flag when you do it)?

Thank you, and I'm sorry you're having trouble!

**Comment by jahamed** [comment]
Sure, yeah this is a stumper 😕 

My original example was using Hyper terminal.
All terminals are using /bin/zsh

### With default mac terminal:
Actually the SMS message seems to be added before and after the journal entry...

```
❯ jrnl testing --debug
DEBUG    jrnl.install Reading configuration from file /Users/hal/.config/jrnl/jrnl.yaml
DEBUG    jrnl.cli     Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': '/Users/hal/Dropbox/Apps'}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.4.5'}"
DEBUG    jrnl.cli     Using journal "default"
DEBUG    jrnl.cli     Appending raw line "testing" to journal "default"
[Entry added to default journal]
```

```
❯ jrnl -n 3 --debug
DEBUG    jrnl.install Reading configuration from file /Users/hal/.config/jrnl/jrnl.yaml
DEBUG    jrnl.cli     Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': '/Users/hal/Dropbox/Apps'}, 'linewrap': 79, 'tagsymbols': '@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.4.5'}"
DEBUG    jrnl.cli     Using journal "default"
2020-11-01 11:56 SMS Backup & Restore Upload Test was successful.

2020-11-01 11:56 testing

2020-11-01 12:00 SMS Backup & Restore Upload Test was successful.

```

### jrnl.yaml
```
colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: ''
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: /Users/hal/Dropbox/Apps
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.5
```

I'll try to think of any other info that might help

**Comment by wren** [comment]
Ah, I think I might see the problem. It looks like your journal is pointing at a directory. (`~/Dropbox/Apps`). Is there, by chance a file in that directory that has this SMS message you keep seeing?

This looks like a directory-based journal (unless `Apps` is a file?). This directory should be empty you're telling jrnl to read entries from the files there. So maybe changing your journal to something like `~/Dropbox/Apps/my_journal` might work for you (you can also make `my_journal` a file, if you prefer your journal to be a single file instead of a directory).

**Comment by jahamed** [comment]
Ah >.< that was it.

I forgot I had some SMS backup program in my dropbox from years ago. Thanks wren! I'll make a fresh folder.
