### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by photoartist9** [jrnl-org/jrnl#1066]
Hi. Recently installed jrnl on my pi 4 running Ubuntu mate, but adding entries from the command line seems to be a craps shoot. Half the time the entry will save just fine, other times I’ll hit enter and just get a > prompt. What is causing this?

**Comment by gregorybodnar** [comment]
This looks like a shell problem. If you see '>', it is a line continuation,
which usually means that the shell is expecting more input because a string
hasn't been terminated. Make sure your apostrophes or quotation marks work
in pairs.

**Comment by wren** [comment]
Yeah, I see that happen when contractions (I'll, can't, don't, etc) because the apostrophe is read as a single quote without a pair. 

When in doubt, just put the whole entry in double quotes to avoid the problem (which quotes are best to use depend on your shell).

**Comment by wren** [comment]
Hi, @photoartist9, please report back when you have a chance on whether the above advice worked for you or not.

**Comment by wren** [comment]
Closing this for now. Please feel free to reopen if you have any new info.
