### ISSUE TITLE
Use jrnl to log numeric values in a csv 

### ISSUE THREAD

**Issue by loetters** [jrnl-org/jrnl#1071]
### Use Case/Motivation
It would be great if we can use jrnl to log numeric values in csv like form. For example I often have to note numbers like driven kilometers on a day, or money spend on something. Special software or even excel for this kind of task is to heavy for my personal taste. It would be great if to use jrnl in a to "note" this kind of numbers in a seperat file for different topics or as key value pair

### Example Usage
The created struture could look like this 

**Document: Car.csv**
|Timestamp | Value | Comment|
|---|---|---|
|2020-11-02 | 13.3 | Way to work. |
|2020-11-01 | 4.5 | Visit family |

**Document: Money**
|Timestamp | Value | Comment |
|---|---|---|
|2020-11-02 | 2.0 | Coffe to Go
|2020-11-01 | 9.5 | Cinema Visit

The comment could look like this 

jrnl -add Car 13.3 Way to work.
jrnl -add Money 2.0 Coffe to go

**Comment by wren** [comment]
Hi! Thanks for suggesting the feature.

I think you can mostly already do this with the current tools in `jrnl`.

If your example above, you could set up two journals (`car` and `money`), and set the config for those to something like `timeformat: '%Y-%m-%d,'` (notice the comma at the end). Then you can add entries like `jrnl money 2.0 , Coffe to Go` (the spacing around the comma is optional).

Then you can get output in a table with something like `jrnl -2 | column -ts','`, which will output like this:
```
2020-11-01   9.5    Cinema Visit
2020-11-02   2.0    Coffe to go
```

There are some limitations in that the file isn't actually stored as a csv (it's in jrnl's format), but you get ta csv fairly easily with something like `jrnl -2 > money.csv`. And it would get confused with extra commas (like `jrnl money 2.0 , Bought some coffee, and also a bagel`), which is a common problem with handling the csv format without a proper library.

If you want to get fancy with it and do use a proper library, you could make an exporter (a formatting plugin that jrnl supports) to better handle the csv format. If you want examples, you can take a look at the [plugins that ship with jrnl](https://github.com/jrnl-org/jrnl/tree/develop/jrnl/plugins) already.

Does that cover what you were looking for?

**Comment by loetters** [comment]
Hey Thanks for your feedback. I think this approach should work for me.

Thanks a lot!
