### ISSUE TITLE
How can I define an entry's date as yesterday when using an external editor?

### ISSUE THREAD

**Issue by trych** [jrnl-org/jrnl#1079]
When I use an external editor (vim in this case), and I want to add an entry for yesterday, how do I assign this date? When I do `jrnl yesterday:` it adds this straight as an entry with the current date and time instead of using yesterday's date with the default time.

Thanks!

**Comment by wren** [comment]
Hi! 

What you want to do is run `jrnl` and when your editor comes up, start the entry with `yesterday:` in the editor itself.

The general rule is that entries in the editor work the same as the cli. The only difference is that the shell no longer gets in the way.

**Comment by trych** [comment]
Ah, this works indeed.
Would maybe good to briefly mention this in the docs somewhere, because it does not feel very intuitive.

Thank you!

**Comment by wren** [comment]
Agreed. We actually already have an issue for that (#1072).

Thanks for letting us know!
