### ISSUE TITLE
Allow timestamps in command line for new entries with editor

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1083]
### Use Case/Motivation

When writing an entry from the command line, a user can enter a timestamp like so:
```
jrnl yesterday: That happened
```
But this doesn't work if the user wants to start an entry at a particular time, like so:
```
jrnl yesterday:
```
That just creates a new entry titled "yesterday:". It would be a lot more useful for users with editors configured to be able to open up a new entry with the timestamp they entered on the command line.

See #1079 for the original idea behind this ticket (thank you @trych).

### Other information

There's already a workaround for this -- starting off the new entry with the timestamp and a colon. For instance:
```
yesterday: That happened
```

Still, it's not particularly obvious nor consistent.

Also, jrnl handles the default terminal editor (which is just reading from `stdin` until an escape character) a little differently from an actual configured editor. This enhancement would either need some extra code to deal with the `stdin` editor, or only support a configured editor.

**Comment by trych** [comment]
Well, Mr. Robot, the problem still exists. :)

**Comment by wren** [comment]
@trych Mr. Robot can get a little sassy sometimes.

**Comment by wren** [comment]
Actually, Mr. Robot might be right. This works consistently across configured editors now. I think we might have accidentally fixed it when doing the arg parsing refactor that happened a while back. 

Opening an entry with a timestamp works if you tell jrnl you want to go to the editor (`jrnl yesterday: --edit`), and `yesterday: whatever` works in both a configured editor, and in the `stdin` editor.

@trych Can you clarify what part of this problem you're still seeing?

**Comment by trych** [comment]
Sorry, I was just commenting to keep the issue open because I *thought* it wasn't fixed yet, as nobody had further commented on it. I haven't tested it. If you're saying now it is fixed, then I assume it is fixed.

**Comment by wren** [comment]
@trych No worries. It's totally my fault. I think this got fixed along with something else, and I didn't update the issue. 

I'm going to go ahead and close it now, but if you get a chance to test this and still see a problem, please give us an update so we can take a look.
