### ISSUE TITLE
Weekday name ignored for multiple weeks ago

### ISSUE THREAD

**Issue by xeruf** [jrnl-org/jrnl#1099]
### Environment
```
❯ jrnl --diagnostic
jrnl: v2.4.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
OS: Linux 5.9.10-arch1-1
```
Installed through pacman (2.5 is unfortunately not out of testing yet)

### Current Behavior
```
❯ jrnl sun week ago: testing
[Entry added to default journal]
❯ jrnl sun 2 week ago: testing2
[Entry added to default journal]
❯ jrnl -contains testing
2020-11-12 Thu 00:00 testing2

2020-11-22 Sun 00:00 testing

❯ date -d "sun 2 weeks ago"
Sun 15 Nov 2020 00:00:00 CET
```

### Expected Behavior
Dates are resolved like in the `date` command

**Comment by micahellison** [comment]
Hi there, thanks for finding and submitting this bug.

It looks like it's a problem with the library that we're using to parse dates right now, [parsedatetime](https://pypi.org/project/parsedatetime/). We looked into another possibly more flexible library called [dateparser](https://github.com/scrapinghub/dateparser/), however it doesn't seem to support this either.

There's some discussion in the parsedatetime project about this in issue bear/parsedatetime#190 so if/when that is resolved, we should have this functionality in jrnl eventually.

**Comment by chwt** [comment]
In case it was the question if something similar could be achieved.
By chance I noticed that the following would work:
`<x> weeks before (last) sun`

```
>>> import parsedatetime
>>> cal = parsedatetime.Calendar()
>>> cal.parse('last sun')
(time.struct_time(tm_year=2024, tm_mon=8, tm_mday=11, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=224, tm_isdst=-1), 1)
>>> cal.parse('2 weeks before last sun')
(time.struct_time(tm_year=2024, tm_mon=7, tm_mday=28, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=210, tm_isdst=-1), 1)
```
