### ISSUE TITLE
Document keyring security concerns on Windows, Mac

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1142]
## Documentation Change

I've been playing around with the keyring functionality on Windows and I thought it might be worth documenting a few of its behaviors. At first, I thought Windows didn't have a keyring at all, but it turns out that the keyring module we use interfaces with Windows Credential Manager and is "working" just fine with jrnl.

jrnl was developed with the Mac's keyring in mind. Mac users have a keyring that, by default, prompts for credentials before a program can write or read stored keys. Windows, however, simply allows any program you're running to access Windows Credential Manager, with no locking mechanism, no ability to allow the user to refuse access, and no Windows prompt whatsoever. Worse, it even allows access to data saved by other programs.

So, for Windows users, saving a jrnl password to the keyring is not very secure, and that password could be retrieved by a relatively simple script running as the user.

### Affected Page(s)

* Maybe this page, which could some notes on cross-platform behavior: https://jrnl.sh/en/stable/encryption/
* Definitely this page: https://jrnl.sh/en/stable/privacy-and-security/

### What Could Be Better?

Windows users should be warned, at the very least, about this issue, and told where to find the credentials in the Credential Manager. Maybe we should even modify the program itself to warn users (if so, let's spin that off to a separate issue).

### Other Information

* [StackExchange thread lambasting Windows Credential Manager](https://security.stackexchange.com/questions/119765/how-secure-is-the-windows-credential-manager)

**Comment by KarimPwnz** [comment]
Hmmm... This does come with the assumption that the user's device is compromised; at that point, a script could wait to retrieve the decrypted journal from a jrnl temp file. Nevertheless, fetching the password from Windows Credential Manager would be easier.

**Comment by KarimPwnz** [comment]
I am not sure if warning about Windows Credential Manager is necessary.

> Mac users have a keyring that, by default, prompts for credentials before a program can write or read stored keys. 

This is not the default for the "login" keychain: you have to configure it to lock after x minutes of inactivity or during sleep. So it seems like the default behavior is the same across both platforms?

**Comment by wren** [comment]
> Hmmm... This does come with the assumption that the user's device is compromised; at that point, a script could wait to retrieve the decrypted journal from a jrnl temp file. Nevertheless, fetching the password from Windows Credential Manager would be easier.

@KarimPwnz That's very true. A device has to be compromised for either situation to matter. The with the current behavior from WCM, though, the amount of time someone needs access to a system is much smaller than other attack vectors. With only a few seconds of access, it would be trivial to run a script that copies all the WCM passwords, along with encrypted journal files to a removable drive, and just walk away. And that would compromise all data in every journal on the system. And all this can be done with nothing running in the background, no root access, and no indication of any breach. 

If a script were running in the background waiting for temp files, this would require something running in the background which could eventually be found (and warn about a breach). And while it's running, it could only ever get data that is accessed while it is running (not all data).

So, either scenario is bad news, but the quick, all data, no warning scenario seems much worse to me.


> I am not sure if warning about Windows Credential Manager is necessary.
> 
> > Mac users have a keyring that, by default, prompts for credentials before a program can write or read stored keys.
> 
> This is not the default for the "login" keychain: you have to configure it to lock after x minutes of inactivity or during sleep. So it seems like the default behavior is the same across both platforms?

Is that the default for the mac keyring? I don't think I've changed any settings on my system, and I get prompted for a password when an app tries to access my keyring. Maybe I did change it at some point, though.

**Comment by KarimPwnz** [comment]
According to https://forums.macrumors.com/threads/keychain-should-the-login-keychain-be-unlocked.2039476/, the login keychain is unlocked by default. I also verified that on three of my devices.

**Comment by wren** [comment]
Hrmm, that's interesting. I must have changed it at some point. Thanks for checking that!

Either way, I think that just means we should also warn about the mac keychain along with WCM if they are both unlocked by default. Maybe not in the app, but just a note on our security page.

**Comment by KarimPwnz** [comment]
Agreed 👍

**Comment by micahellison** [comment]
Thanks to both of you for all the info and Mac perspectives. I agree that just the privacy/security page should be edited, and it needs a new section on keyrings with warnings that sum up the discussion here.
