### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by jonaths** [jrnl-org/jrnl#1144]
### Use Case/Motivation

I tend to use markdown language to write structured documents using plain text. It allows me to order my ideas using a well-known framework. Right jrnl has no "support" for markdown. For instance, markdown document starts with a h1 header such as

```
# Document title
- a bullet
```

And text

The issue here is that a jrnl document starts with the date and title with no #. So any markdown linting software will complain. 

### Example Usage

For starters a nice initial approach will be to allow a markdown option while creating the date that starts with a "#" and the title, and a text below with the time and date of the entry. Then jrnl should be able to parse this header structura instead of the plain "date. title" current structure. 

So, while editing with an external text editor a "markdown header could be this"

```
# Year review
Today at 13:00
```

instead of this

Today at 13:00: Year review

Of course, the date can be parsed so that a datetime stamp is created as it happens now.

**Comment by wren** [comment]
Hrmm, interesting. Can you elaborate on this a bit?

Does `jrnl --format markdown` cover your needs? In what way does it fall short?

**Comment by jonaths** [comment]
Hi @wren. Just noticed the message. Perhaps it is a silly detail. 

If I understand correctly with jrnl --format markdown _I can see_ my journals in markdown format. I see that the hierarchy starts with the year, then the month (##) and finally my individual entries with ###. 

So I could write a sample text like this and import it with `jrnl < text.md`:

```
Last monday at 20:00: something good happened.

# Good news
bla bla

## A subtitle
bla 

Some bullets
- one
- two

# More good news
```
Then when using `jrnl --format markdown` my header `#Good news ` becomes `#### Good news `, which is great. 

The thing is that my sample text is not valid markdown since it starts with _Last monday... _, which is the required jrnl header, instead of a `# header` that would make a [valid markdown](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md041).

**UPDATE**

Just wrote all this and then realized that I can start my sample text as follows:

```
# Last monday at 20:00: something good happened.

# Good news
bla bla

```
The `#` solves the issue. A proper entry can be read by journal and it is a valid markdown!

**Problem solved.**
