### ISSUE TITLE
Specify an alternate config file in the command line

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1170]
## Feature Request

It would be nice to specify an alternate config file from the command line.

### Use Case/Motivation

We already have an issue for specific overriding configuration values on the command line (#1157), but in many situations, it would be a lot cleaner and more useful for users to be able to specify a full config file.

This could lead to some privacy-oriented use cases like a portable jrnl running on a removable drive, with no trace of its configuration on the operating system's drive. It could also be useful for testing and troubleshooting.

### Example Usage

```
# New entry
jrnl --config-file g:\portableconfig.yaml

# Viewing last five entries
jrnl --config-file g:\portableconfig.yaml -5

# Order of arguments shouldn't matter
jrnl -5 --config-file g:\portableconfig.yaml

# Writing a new entry on a particular journal specified in the alternate config file
jrnl secondary --config-file g:\portableconfig.yaml
```

### Other information

Would be nice to provide an alias for this argument, like --cf.

Some thought would need to go into how compatible this should (or shouldn't) be with features that change the config, such as  #1068 (modify config) and #330 (create new journals).

**Comment by samuelgregorovic** [comment]
@micahellison  @wren i can work on this if you would assign it to me.

**Comment by wren** [comment]
@samuelgregorovic Thanks for volunteering for this! We don't really use the assign field very often here. We just ask that someone comment in the issue that they're working on it (which you just did). 

So, just send a PR over whenever you're ready. 😄

**Comment by samuelgregorovic** [comment]
@wren  understood. thanks!
