### ISSUE TITLE
`jrnl --format pretty` returns an error

### ISSUE THREAD

**Issue by shazron** [jrnl-org/jrnl#1172]
### Environment
- `jrnl --diagnostic` output: 
jrnl: v2.7
Python: 3.9.1 (default, Jan  8 2021, 17:17:43)
[Clang 12.0.0 (clang-1200.0.32.28)]
OS: Darwin 20.1.0
- Install method: brew

### Current Behavior
`jrnl --format pretty` returns an error.
```
$ jrnl --format pretty                                                                                 
usage: jrnl [--debug] [--help] [--version] [--list] [--encrypt] [--decrypt] [--import] [-on DATE] [-today-in-history]
            [-month DATE] [-day DATE] [-year DATE] [-from DATE] [-to DATE] [-contains TEXT] [-and] [-starred]
            [-n [NUMBER]] [-not [TAG]] [--edit] [--delete] [--format TYPE] [--tags] [--short]
            [...]
jrnl: error: argument --format: invalid choice: 'pretty' (choose from 'boxed', 'dates', 'fancy', 'json', 'markdown', 'md', 'tags', 'text', 'txt', 'xml', 'yaml')
```
### Expected Behavior
`jrnl --format pretty` returns the journal listings pretty printed (as described in https://jrnl.sh/en/stable/formats/)

### Repro Steps
Run `jrnl --format pretty`

**Comment by sriniv27** [comment]
`--format pretty` errors out in the release branch and in the prior release tag. 

The valid formats are enumerated from the list of exporter plugins and there is a missing one for pretty.

 I suppose one solution for this is to have a lightweight  PrettyExporter that is a thin wrapper to `Entry.pprint()`

**Comment by wren** [comment]
Yup! This was absolutely me putting something in the docs without the proper testing (same with `--format short`). Good catch!
