### ISSUE TITLE
Cannot end / exit an entry on Git Bash in Windows. 

### ISSUE THREAD

**Issue by PrecisionWordcraft** [jrnl-org/jrnl#1179]
### Environment

  - Jrnl `--diagnostic` output: 
jrnl: v2.7
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
OS: Windows 1

  - Install method: 
pipx

### What are you trying to do?

I'm simply trying to write ONE journal entry and EXIT the entry.

On Linux, Ctrl-D does it. There is nothing in the docs about how to do this on ANY OS. I don't know how I figured it out on Linux. 

### What have you tried?

Various key combinations

**Comment by micahellison** [comment]
Hi there, ctrl+z should work in Windows. When you run jrnl, does it show this message?
```
[Writing Entry; on a blank line, press Ctrl+z and then Enter to finish writing]
```

**Comment by PrecisionWordcraft** [comment]
> 
> 
> Hi there, ctrl+z should work in Windows. When you run jrnl, does it show this message?
> 
> ```
> [Writing Entry; on a blank line, press Ctrl+z and then Enter to finish writing]
> ```

There's no message at all. I'll try that combo.

**Comment by PrecisionWordcraft** [comment]
Ctrl + Z gives this output on my system but does not close the entry.

0 [sig] bash 2816! sigpacket::process: Suppressing signal 18 to win32 process (pid 5736)

**Comment by micahellison** [comment]
It looks like a couple different things are happening here:

* Your terminal is suppressing STDERR output, which is where that message should show
* Your terminal is suppressing the ctrl+z command (based on that error - that's what "signal 18" is)

I'm not sure what the solution is. You may want to investigate your git bash configuration. I have a pretty default installation of git bash on my Windows 10 machine, and it is working:
```
$ jrnl
[Writing Entry; on a blank line, press Ctrl+z and then Enter to finish writing]

This is a test
^Z
[Entry added to default journal]
```

**Comment by PrecisionWordcraft** [comment]
I moved over to Ubuntu on Win10 and all's well - no error / output suppression, can exit entries as I'm used to. 

And the output tells me to press Ctrl - D to exit, which is accurate.

I did enter a doc issue on "how to exit" and since it's easy to miss seeing standard CLI output, you may want to add it to docs as well.
