### ISSUE TITLE
Update documentation about journal-level config values

### ISSUE THREAD

**Issue by sriniv27** [jrnl-org/jrnl#1196]
### Affected Page(s)

  - https://jrnl.sh/en/stable/advanced/

### What Could Be Better?

The section on multiple journal files makes a passing mention that a specific journal can have its own configured options, but the examples are only limited to preferences for `encrypt`. It is left to the reader to extrapolate that things like `timeformat`, `editor`, etc. can also be configured on a per-journal basis.  

### Other Information

I think that a couple of code snippets or even an extension of the existing snippet should suffice. 

Another (not necessarily exclusive) option is to update recipes with workflows that allude to it.

**Comment by wren** [comment]
Good catch!

**Comment by micahellison** [comment]
Resolved by #1199
