### ISSUE TITLE
Wrong delete count when manually changing entries

### ISSUE THREAD

**Issue by tiagoboldt** [jrnl-org/jrnl#1198]
### Environment
```
> jrnl --diagnostic
jrnl: v2.7
Python: 3.9.2 (default, Feb 19 2021, 17:43:04)
[Clang 12.0.0 (clang-1200.0.32.29)]
OS: Darwin 20.3.0
```

  - Install method: homebrew

### Current Behavior
When editing a list of entries in my editor, and adding one entry in the list, after saving the file, the summary says that a negative number of entries was deleted. 

```
> jrnl -n 5 --edit
[-1 entries deleted, 1 entry modified]
```

### Expected Behavior
I would expect to see the following output when adding one entry and changing another:
```
> jrnl -n 5 --edit
[1 entry added, 0 entries deleted, 1 entry modified]
```

### Repro Steps
Open a list of recent entries in your editor with the command above and add an additional entry between those.

**Comment by micahellison** [comment]
Thanks for submitting this bug. I've just reproduced it in on my end too, though with slightly different circumstances that the fix should also account for.

When I run `jrnl --edit` on an empty journal and add an entry:
```
[-1 entries deleted, 1 entry modified]
```
I think it should actually just say:
```
[1 entry added]
```

**Comment by piero-vic** [comment]
Hi.
I think I've find the root of the problem.
It's on `jrnl.py`. Right here.
https://github.com/jrnl-org/jrnl/blob/44edb9bdee0f0bcd7f8000039c3eeeb3850e9718/jrnl/jrnl.py#L276-L296
I'm new to Python and open source but I think I can fix it. Can I work on this issue?

**Comment by micahellison** [comment]
> I'm new to Python and open source but I think I can fix it. Can I work on this issue?

Yes please, feel free to submit a PR and let us know if you have any questions!

I think to fully resolve this issue, a resolution should:
- [ ] fix the bug
- [ ] test for this in BDD (let us know if you need help)
  - [ ] this should include scenarios for all journal types (regular, directory, encrypted, DayOne)
