### ISSUE TITLE
Prompt for password after some time of inactivity (Mac)

### ISSUE THREAD

**Issue by zerolatnc** [jrnl-org/jrnl#1212]
### Environment

  - Jrnl `--diagnostic` output:
  ```
jrnl: v2.6
Python: 3.9.1 (default, Jan  8 2021, 17:17:17)
[Clang 12.0.0 (clang-1200.0.32.28)]
OS: Darwin 19.5.0
```

  - Install method: `brew`

### What are you trying to do?
Currently, if I encrypt my journal and select yes when prompted to store the password in my keychain, I never have to enter the password again because the password seems to be stored in the `login` keychain which is always unlocked when I log in on my mac.

Instead, I would like the behavior to be such that `jrnl` asks me for the password when I try to access it and then allow me to access it without a password for some time. If there is some time of inactivity, then `jrnl` should ask me for the password again.

### What have you tried?
One way to do this would be to change the settings for the `login` keychain so that it prompts for a password after some amount of inactivity. But the problem is that the `login` keychain has many other password items for which I don't want this sort of behavior.

So, I created a new keychain in which I put in the password item for `jrnl`, but this doesn't seem to work. I guess `jrnl` only looks for the password in the `login` keychain. I checked the config file to see if there is a way I can tell `jrnl` to look for the password in a different keychain, but couldn't find any such option.

Is there a way to achieve the behavior that I want?

**Comment by wren** [comment]
This is a very good point. If we were to add support for a secondary keyring, it would allow users more options.

It could also maybe help deal with #1142.

**Comment by wren** [comment]
To clarify, there is no current way to achieve what you're looking for. Jrnl uses the primary keyring, so you're stuck with the implications of that. But we might be able to change that behavior.

**Comment by zerolatnc** [comment]
Thanks for the reply!

Should I close this issue or leave it open for a discussion about the possibility of adding this functionality to jrnl?

**Comment by wren** [comment]
Happy to help, and sorry it wasn't the answer you were looking for.

Please leave this open while we figure out the best course of action, and we'll close it up when we have a new ticket for whatever the fix ends up being.

**Comment by micahellison** [comment]
Spinning this off to #1226.
