### ISSUE TITLE
Add statistics report

### ISSUE THREAD

**Issue by albertwh1te** [jrnl-org/jrnl#1225]
## Feature Request
Add diary statistics .
### Use Case/Motivation
for example , like how many entries I have wrote 
### Example Usage
jrnl --statis

**Comment by micahellison** [comment]
A statistics report sounds fun and interesting. It should work with existing query arguments (such as `-n` and `-from`) and should probably a parameter of `--format`.

However, to address the specific use case you mentioned, just grabbing the number of entries is already possible with a little piping, depending on your OS:

* *nix: `jrnl --short | wc -l`
* Windows: `jrnl --short | find /c /v ""`
