### ISSUE TITLE
Add support for bullet journaling through default Markdown format

### ISSUE THREAD

**Issue by Haze-sh** [jrnl-org/jrnl#1235]
## Feature Request
Right now **jrnl** has limited support for Markdown format through importing/exporting but I believe Markdown (with bullets) should be the default used format.

### Use Case/Motivation
Markdown is a standardised format for plain-text and it's wide known so it's future-proof as this project aims to be. Also adding bullets allows for better formatting and solving for existing problems and better journaling experience.

This would make the bullets the standard entry identifier rather than the timestamp.

This would solve many problems:
1- Making generic entries without timestamps (see: #1046)
2- Adding TODOs support rather than plain journaling.
3- Better journaling within text editors.

### Example Usage

```
# 2021
## June
### 2021-6-1
[x] Go to the gym.
[ ] Right down ideas.
o 2021-06-01 12:00 Dentist appointment.
```
Keep in my mind that in this proposed format the date of the entry is still a solid identifier but not the timestamp, where the individual entries are identified by type rather than the timestamp.

### Other information
The implementation of this shouldn't be hard if the different bullet symbols mapped to different keywords like TODO or EVENT even though it would take some work to export the entries in the date fromat. But I believe it would be a crucial step towards v3.

**Comment by micahellison** [comment]
Hi there, thanks for filing this issue. Could you elaborate on these examples and what your process for entering these entries might be like? I'm not sure if the example usage above is referring to one entry or multiple entries. And are you referring to storage format or display format, or both?

**Comment by Haze-sh** [comment]
Hi there, sorry for the delayed response.

1- My process for entry would be like:
`jrnl task yesterday: bla bla.`
`jrnl event today: bla bla.`

2- It's referring to multiple entries

3- I am referring to the storage format here, as markdown is a standardized format so it can be to exported to many other formats easily even by external tools.

Thanks for respond and please ask if something is not clear.

**Comment by micahellison** [comment]
It looks like the current markdown export could *almost* meet the needs you're talking about:
```
jrnl --export md
```
However, it doesn't remove timestamps like your example specifies. We're getting close to implementing support for format plugins, which could eventually do this - see #1239.

As for dealing with this in the the storage format, we are eventually planning to add support for a wide variety of storage formats, though that is a longer way away since it is a large change to the way jrnl runs.

**Comment by lamyergeier** [comment]
@micahellison May I suggest you to watch this 4 minutes video  

> [How to Bullet Journal - YouTube](https://www.youtube.com/watch?v=fm15cmYU0IM)

Its very concise and explains the journaling methodology which is minimalist and easy to visualize.

**Comment by xeruf** [comment]
@Haze-sh the idea of leveled headlines for year/month/day I like very much, but I can't see the bullet journal functionality in here.

jrnl files are not meant to be edited by hand, and checking off bullets via CLI would turn jrnl into a task-manager, which I would classify as feature-creep. I think there are two kinds of journaling: Reflective and proactive, and you want to do the latter while jrnl is built for the former.
I would recommend you to look into Emacs org-mode instead.

**Comment by wren** [comment]
@xeruf @Haze-sh The example from @micahellison above already has the leveled headlines. Here's an example:

```markdown
# 2009

## June

### 2009-06-26 09:00:00 AM Planet?

Earth. Year? 2009.

# 2013

## May

### 2013-05-10 09:00:00 AM I saw Elvis.

He's alive.

## November

### 2013-11-30 03:42:00 PM Project Started.


# 2020

## January

### 2020-01-01 09:00:00 AM Test.

```

Does that do what you're asking for?

Also, I agree with @xeruf that turning jrnl into a task manager is out of scope for this project. As mentioned above, we'll be implementing more plugins (which will eventually include storage format plugins), so then someone could make a plugin to help jrnl support task managers.

**Comment by viegasfh** [comment]
To be honest, initially I kind of wanted to be able to discard the timestamps, but I found many instances where the timestamp is useful. If we could configure it to disable the timestamp, I may use it.

However, the proposal for task management, I agree with others. You alread have "topydo" for that. It does a pretty good job at it. It uses the Getting Things Done methodology in plain text. That's what I use.

As for the bullet journals, they just don't work for me. I am pretty happy with how jrnl works as is. I can export to Markdown whenever I need to, and all my entries include Markdown markup. But making it default, is just a lot of writing. I prefer the default jrnl format. Less typing.

I haven't really tried it, but doesn't the display_format option already allow you to enable MD as default format?

**Comment by micahellison** [comment]
> I haven't really tried it, but doesn't the display_format option already allow you to enable MD as default format?

Yes, it does. It's what I use, actually. And even without using markdown as a "format", one could still journal in markdown just fine without any issues with the jrnl data format.

**Comment by viegasfh** [comment]
Exactly! I love the jrnl data format. Simple and effective.

**Comment by wren** [comment]
Ok, sounds like this is working for everyone. I'm closing this, but feel free to comment if there's still anything to do here.
