### ISSUE TITLE
Weird file locking problem

### ISSUE THREAD

**Issue by Octelly** [jrnl-org/jrnl#1237]
### Environment
  - `jrnl --diagnostic` output:
jrnl: v2.8
Python: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
OS: Linux 5.11.0-7612-generic
  - Install method: pipx

### Current Behavior
Doesn't save diary entry

### Expected Behavior
Saves diary entry

### Repro Steps
1. start writing diary entry in one terminal
2. open an older one for reference in another terminal
3. save your new entry
4. close the reference entry
5. your new entry didn't save

### Other Information
This made me wanna smash my laptop against the wall

**Comment by sriniv27** [comment]
Similar issue as #1106 and #1107 possibly?

**Comment by wren** [comment]
I'm sorry this happened to you.

I think you're right about the linked issues. I don't have time until Saturday to dig into this, but I'll give more details then. Thanks for your patience!

**Comment by micahellison** [comment]
Yes, this is the same issue as #1107. I'm closing this as a duplicate, but I do appreciate it being filed. We'll continue discussing it in that issue, and we're evaluating our roadmap to see if we can find  a solid long-term fix to this issue sooner.
