### ISSUE TITLE
Multiple entries with same timestamp should be grouped together

### ISSUE THREAD

**Issue by drax10** [jrnl-org/jrnl#1247]
### Use Case/Motivation

I use jrnl to log what happened that day. On occasion, I will add more than one record for the same day using `jrnl today: blah blah`. The end result is:

```
[2021-05-17 09:00] Something amazing happened
You'll never guess what that was

[2021-05-17 09:00] Some other cool thing happened today
```

Since these have the same exact timestamp I expected the second record to be appended onto the previous one like so:

```
[2021-05-17 09:00] Something amazing happened
You'll never guess what that was

Some other cool thing happened today
```

**Comment by minchinweb** [comment]
This is a possible use case for a custom exporter. See #1216 for development work on implementing then. 

For output, are you concerned about telling the two entries apart?

For usability, is there a reason you're creating two entries in the first place and not editing the first one instead? (`jrnl -1 --edit` will pull up the last entry to edit it)

**Comment by drax10** [comment]
Perfect! Once that's merged I can try my hand in making a custom exporter to accomplish this.

I am not concerned about telling the two apart. My use case is to journal what happened in each day, so I'd like one record each day.

The reason I haven't done `jrnl -1 --edit` is I didn't know that I could do that! Although it isn't a perfect solution because I need to remember if I have already logged something or not that day,

**Comment by micahellison** [comment]
Since this is going to be handled with a plugin, I'm closing this issue. Feel free to let us know and/or link your plugin from this issue when you're done.
