### ISSUE TITLE
Need help to build/package jrnl on i386/Alpine Linux docker image for iPad running iSH app

### ISSUE THREAD

**Issue by legacy-code** [jrnl-org/jrnl#1249]
## Support Request
I am running iSH on my iPad (it's an Alpine Linux emulator) and would like to figure out a way that would work with getting a version of *jrnl* working with the *i386* Alpine image.

I have been able to create a docker image on my Mac that can install jrnl without having to figure out exactly what to copy from my docker image to the iPad image in iSH (if that make sense).  

I have been able to compile and use other apps/tools and transfer the binary to my iPad and have it work, so I think it *should be possible*, I'm just not sure the best way to go about it.

Most likely would probably be to build it (on the docker image) "locally" and then use the resultant directory and move that to the image.  I am unsure on how to do that.  As noted below, copying the `site-packages` files didn't work (I didn't have high hopes, but ...).

If it's as easy as cloning the repo and running `make build` (or something like that) then this could probably be closed after a confirmation.  Or, if there is a pre-built binary for the i386/Alpine distro, that would also work, but I couldn't find one.  This probably is beyond the scope of a usual support request, so ...  If you can give me any tips on building or after looking at the output below, that would be appreciated.

Anyway, the rest is what I've tried and the error I'm currently getting.  

### Environment

  - Jrnl `--diagnostic` output: 

```bash
jrnl --diagnostic
jrnl: v2.8.1
Python: 3.8.10 (default, May  6 2021, 00:05:59)
[GCC 10.2.1 20201203]
OS: Linux 5.10.25-linuxkit
```

  - Install method: 
      - pip3 install jrnl 

### What are you trying to do?

As stated above, I want to get jrnl copied from my docker image (ran on my Mac) that has built jrnl and copy all the necessary bits over to the Alpine Linux filesystem that resides in the iOS/iPadOS app iSH.

This Dockerfile (shown below) is able to create a docker image and create jrnl without any issue.

```text
# Alpine >3.13 breaks stuff on many host OSes! For details see:
# https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0#faccessat2
# FROM    alpine:edge
FROM    i386/alpine:3.13
RUN     apk update.                  \
        && apk upgrade               \
        && apk add --no-cache  \
        curl gcc make tcl              \
        musl-dev                           \
        openssl-dev zlib-dev       \
        openssl-libs-static zlib-static
		
RUN 	apk add python3	                                                                               
RUN	apk --update --upgrade add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev
RUN 	apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo
RUN	pip3 install setuptools_rust docker-compose
RUN	pip3 install jrnl
```

This is done with the docker command:

```bash
docker build -t alpine_i386_jrnl .
```

Then, you can run the image by 

```bash
docker run -it alpine_i386_jrnl
```

It runs and I get version 2.1.8.

### What have you tried?

I've tried to copy portions (and then all) of the /usr/lib/python3.8/site-packages to my image (on my iPad) and some of the files in /usr/bin (most important here is the *jrnl* command).  When I have done that, I get a import error

```text
ImportError: Error relocating /usr/lib/python3.8/site-packages/_cffi_backend.cpython-38-i386-linux-gnu.so: __dlsym_time64: symbol not found
```

so, copying the files is probably not a way that is going to work.  I am wondering if actually building it on the image like I was going to contribute to the project, if that would be a better way to do it.  My guess is yes, but I'm not sure how to do that yet.  

Where would I find instructions to do that?  I *should* be able to copy the built files from the *dist* or *prod* directory that the project would create, correct?

Any help would be greatly appreciated!

Thanks!
Mike

**Comment by legacy-code** [comment]
Here is an update:

After looking at the repo, I was able to clone and build the project from my docker image.  Here is the updated Dockerfile:

```text
# Alpine >3.13 breaks stuff on many host OSes! For details see:
# https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0#faccessat2
# FROM    alpine:edge
FROM    i386/alpine:3.13
RUN     apk update							\
        && apk upgrade						\
        && apk add --no-cache				\
			cargo							\
        	curl 							\
			gcc 							\
			libc-dev						\
			libffi-dev						\
			make tcl						\
        	musl-dev						\
        	openssl-dev 					\
        	openssl-libs-static 			\
			py-pip 							\
			python3							\
			python3-dev						\
			zlib-dev						\
			zlib-static
		
RUN		pip3 install setuptools_rust docker-compose
RUN		pip3 install jrnl

RUN		curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
RUN		apk add git
RUN		mkdir /code

RUN		git clone https://github.com/jrnl-org/jrnl.git /code/jrnl

RUN		cd /code/jrnl 		\
		&& /root/.poetry/bin/poetry install	\
		&& /root/.poetry/bin/poetry build
```

That give me the following files in the `dist` directory:

* jrnl-2.8.1-py3-non-any.xhl
* jrnl-2.8.1.tar.gz

I'm not sure what to do with them, so ...  I explored some other things while waiting and contemplating.

I ran across this link [Docker: Installing python cryptography on alpine linux distribution](https://stackoverflow.com/questions/50619166/docker-installing-python-cryptography-on-alpine-linux-distribution) and the *cryptography module is the one that I've always had trouble compiling* on the iPad, so ...  I did the following in my Alpine Linux image/emulation in iSH:

```bash
apk add gcc musl-dev libffi-dev openssl-dev python3-dev
pip install cryptography -vvv --no-binary=cryptography
pip install jrnl -vvv --no-binary=cryptography
```

and then tried `jrnl -v` and got the correct response, rather than it throwing an exception. 

So, I *think* I might have it working, but not totally sure what helped.  I had zipped up the whole `site-packages` and unzipped them in the iSH image.  That caused the ImportError noted above.  The steps above seemed to have fixed that, so ...  Maybe it set some privileges that were incorrect or ...

I did not try to do this on a "new" image, as I have other things installed that I don't want to wipe out, so it might be that with installing the cryptography library as noted in the link, it might have worked just fine.  Or, not ...  I really don't know.

Anyway, with it seemingly working and a (sort of) method of getting it in the image, I'm not sure that this needs to be kept open, unless it has some interest to others in the community.

Out of curiosity, how do you use the files in the `dist` directory on a *nix machine?  I've never needed to do that, so any pointers or links would be great so I can close that knowledge gap!  Thanks!

Anyway, thanks for the great app - I use it all the time and really enjoy using it!

**Comment by wren** [comment]
Looks like you got it sorted out, so I'm glad to see that. From the link you posted about cryptography on docker (specifically on the Alpine distro), it says that you have to use the `--no-binary` flag. I believe that's what fixed it for you.

As for dist directory and poetry, the short answer is that you don't have to do anything with that unless you are building jrnl from source. The poetry stuff we handle for you when every time we release jrnl, and when you `pip install jrnl` it's doing all the dist directory stuff for you behind the scenes.

If you're interested in how Python packaging works, [this](https://packaging.python.org/tutorials/packaging-projects/) is a good place to start (although I have to warn you that the learning curve can be quite steep if you're not already familiar with some of these concepts).

**Comment by legacy-code** [comment]
Thanks Wren!

I've not ever done much with Python packaging, but it is interesting, so I'll give it a look!
