### ISSUE TITLE
Output after composition can be more useful and user friendly

### ISSUE THREAD

**Issue by lamyergeier** [jrnl-org/jrnl#1253]
### Use Case/Motivation

To be sure what I wanted to add is correct interpreted by `jrnl`, and that I didn't make a mistake.

### Example Usage

Instead of the current behavior

```bash
$ jrnl time 2 hours ago: @Dinner
[Entry added to time journal]
```

the desired behavior is

```bash
$ jrnl time 2 hours ago: @Dinner
Added (time journal): [2021-05-31 12:21] @Dinner
```

**Comment by lamyergeier** [comment]
A bad fix that I am doing is

```bash
ErrorP="$(mktemp)"
JournalCode='time'
jrnl "${JournalCode}" "${@}" 2> "${ErrorP}"
if [[ $(cat "${ErrorP}") == '[Entry added to time journal]' ]]; then
	TimeCommand="$(echo "${@}" | sed -r -e 's/(.*):.*/\1/')"
	Time="${TimeCommand:-now}"
	jrnl "${JournalCode}" -from "${Time} -1 minute" -to "${Time}"
fi
```

**Comment by micahellison** [comment]
Hi @anishmittal2020, thanks for the suggestion. I do want to output more useful information when jrnl writes, however, I am hesitant to display the title of the entry by default. In particular, it's a security risk for users that use editors on encrypted journals, as it would output part of the jrnl's content to the terminal after writing, which does not sound desirable for sensitive information.

However, this could possibly be implemented through additional plugin support or a config key.

What is your goal here? It looks like you're interested in viewing the timestamp of your most recent entry, so you can quickly see when you entered it? I like to do the same thing with my terminal, but I just do it for every command by adding the timestamp to my prompt.

**Comment by lamyergeier** [comment]
May be `jrnl` can identify if the particular journal is encrypted or not, and if it is not encrypted then it could display the time stamp and the message

---

> What is your goal here? It looks like you're interested in viewing the timestamp of your most recent entry, so you can quickly see when you entered it?

No, for the most recent entry I can do `jrnl -1`, this I knew. I hoped to see the time stamp when the entry that I am making is in the past and I want to make sure that it got entered correctly.

--- 

Try the following:  `j.sh 2021-06-01 13:29: Lunch`

```bash
$ cat j.sh
ErrorP="$(mktemp)"
JournalCode='time'
jrnl "${JournalCode}" "${@}" 2> "${ErrorP}"
if [[ $(cat "${ErrorP}") == '[Entry added to time journal]' ]]; then
	TimeCommand="$(echo "${@}" | sed -r -e 's/(.*):.*/\1/')"
	Time="${TimeCommand:-now}"
	jrnl "${JournalCode}" -from "${Time} -1 minute" -to "${Time}"
fi
```

**Comment by micahellison** [comment]
Maybe the best way to approach this is to add a verbose argument and/or configuration option. It could probably be merged in with the existing `-debug` option with various levels (e.g. `-v` vs. `-vv` and `-vvv`).

**Comment by micahellison** [comment]
I'm closing this and spinning off the verbose output idea to #1312.
