### ISSUE TITLE
Habit Formation: Visualize days with no entry in a month

### ISSUE THREAD

**Issue by lamyergeier** [jrnl-org/jrnl#1255]
## Feature Request

Visualize days with no entry in a month or days with entry

### Use Case/Motivation

To be able to visualize the progress in habit formation of journalling. 
Can motivate people to do more journalling.
Can also be used to send reminders (daily) at a particular time if there are no entry made.

### Example Usage

It can show a month, with a circle around dates that have journal entries!

**Comment by wren** [comment]
Hello! This is a great suggestion. This actually came up awhile ago (discussed in #743, and implemented in #1146). Please give those a look and feel free to comment here again if those don't meet your needs.
