### ISSUE TITLE
Remove duplicate entries

### ISSUE THREAD

**Issue by lamyergeier** [jrnl-org/jrnl#1256]
## Feature Request

Remove duplicate entries

### Use Case/Motivation

Sometimes I merge two journal files into one, is it possible to remove duplicate entries from the journal. 

This is useful as sometimes the two journals are in different devices and the contents have diverged and would be good if we could sync both of them or just one of them.

### Example Usage

I append the second journal into the first like

```bash
cat Journal2 >> Journal1
```
Now, there might be duplicate entries in Journal 1.  Can the duplicate entries removed?

**Comment by wren** [comment]
Ooh, this is an interesting idea. I'm not sure what the implementation would look like, but maybe a search term? Maybe something like `-duplicate` or `-dupe`, and then you could do something like `jrnl -dupe --delete`. I'm not sure how that would interact with other search terms, so we'd have to take a close look at that to make sure there are no weird edge cases.

**Comment by wren** [comment]
Or maybe it would be part of using `--import`?

**Comment by lamyergeier** [comment]
`--import` is not documented in the [Documentation - jrnl](https://jrnl.sh/en/stable/overview/). Could you please tell if it merges 2 journals? What is its purpose?

In the `jrnl -h`

```
 --import              Import entries from another journal.
```

But how to use it?

**Comment by micahellison** [comment]
Hi @anishmittal2020, `--import` takes data in from a pipe and imports that into a particular jrnl. For instance, you can pipe any output into your default jrnl like so:
```
echo "new entry" | jrnl --import
```
Or, to import today's entries from one journal to another, you can use `--format text` then pipe it to another jrnl:
```
jrnl jrnl1 -from today --format text | jrnl jrnl2 --import
```
I did a little testing and I discovered that `--import` does not accept duplicates - if the title, description, name are exactly the same, it won't import that entry.

I think that actually covers this use case, though as you mentioned, we do need to document this better, and I've made a note in the relevant issue (#995).

**Comment by wren** [comment]
Oh, ha! Even better! My favorite kind of feature request is the kind that we've already fulfilled. 😁

@anishmittal2020 Please try out `--import` and let us know if you still have trouble with duplicates.

**Comment by lamyergeier** [comment]
@micahellison  I tested a simpler solution:

```bash
cat  jrnl1.txt  | jrnl jrnl2 --import
```

Can you recommend this?

**Comment by wren** [comment]
@anishmittal2020 That can work if you use the simplest options for jrnl (single file storage, no encryption), and don't want to filter the entries that you are importing to jrnl2 (just take the whole of jrnl1). Otherwise, though, you're better off using @micahellison's example  above.
