### ISSUE TITLE
Create security.md

### ISSUE THREAD

**Issue by zidingz** [jrnl-org/jrnl#1284]
Hey there,

As there isn't a `SECURITY.md` with an email on your repository, I am unsure how to contact you regarding a potential security issue.

Would you kindly add a `SECURITY.md` file with an e-mail to your repository? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this as the best way to ensure security issues are responsibly disclosed, and it would massively help security researchers get in touch next time.

Thank you so much and I look forward to hearing from you!

**Comment by wren** [comment]
@zidingz Hi! The best way to contact us is to [email the maintainers](mailto:jrnl-sh@googlegroups.com). That link is normally only in our code of conduct, but you raise a very good point that we should add an explicit security policy. Thanks for reporting this! We'll be adding one soon.

**Comment by zidingz** [comment]
Thanks so much! Expect an email soon.
