### ISSUE TITLE
Exception when providing folder name of folder that does not exist as journal path

### ISSUE THREAD

**Issue by viegasfh** [jrnl-org/jrnl#1293]
### Environment
  - `jrnl --diagnostic` output: 
  - Install method: 
jrnl: v2.8.1
Python: 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
OS: Linux 4.4.0-19041-Microsoft
### Current Behavior

When providing a folder name as opposed to a file name in the journals configuration, I get an IsDirectoryException.

### Expected Behavior

Although the documentation does not provide examples, I have looked into the source code and found some examples of how to use a folder for multiple files grouped by date, month and day, but the examples provided presume that you have created the folder.

When providing a folder name for the journal name, the app should create the folder and then create the journal entry using the year, month and day.

When I executed the jrnl command after the error, everything worked without an issue. So, the program should create the folder and the journal entry without throwing the exception.

### Repro Steps

In the config file add the following entry or similar one. Make sure the / is found in the end of the folder name. This way jrnl treats is a folder as opposed to a file.

```
test: /home/user01/.local/share/jrnl/test/
```

Once this is configured, just run:

```
jrnl test today: My First Entry. This is an entry I am using to test the folder based journal
```

### Other Information

Here is the stack trace of the error:

```
[Directory /home/user01/.local/share/jrnl/test created]
Traceback (most recent call last):
  File "/home/user01/.local/bin/jrnl", line 8, in <module>
    sys.exit(cli())
  File "/home/user01/.local/lib/python3.8/site-packages/jrnl/cli.py", line 35, in cli
    return run(args)
  File "/home/user01/.local/lib/python3.8/site-packages/jrnl/jrnl.py", line 62, in run
    journal = open_journal(args.journal_name, config)
  File "/home/user01/.local/lib/python3.8/site-packages/jrnl/Journal.py", line 418, in open_journal
    return PlainJournal(journal_name, **config).open()
  File "/home/user01/.local/lib/python3.8/site-packages/jrnl/Journal.py", line 85, in open
    self.create_file(filename)
  File "/home/user01/.local/lib/python3.8/site-packages/jrnl/Journal.py", line 110, in create_file
    with open(filename, "w"):
IsADirectoryError: [Errno 21] Is a directory: '/home/user01/.local/share/jrnl/test/'
```

**Comment by wren** [comment]
I was genuinely surprised to hear that we don't mention directory-based journals in the docs. 🤦 

We should definitely add that. Thanks for pointing this out!

And we should have an established way to let jrnl know you want a directory journal other than creating the directory up front. I think ending with a slash seems like a reasonable heuristic. What do you think @micahellison?

**Comment by viegasfh** [comment]
Hi, @wren !

The docs does mention that it supports multiple files. However, doesn't provide any example. All the examples are based on a single file.

If you don't add the / at the end and there isn't a folder with that name, jrnl treats as a file and creates it. When this happens, you don't get any exception. The exception only happens when it creates the directory and then tries to interpret it as a file, because when you run the command a second time, it already reads it as a directory and works as it should.

Right now, the general rule is for us to manually create the directory and then add the name in the config file. Now, if the directory exists, it doesn't matter if you add a / at the end or not, because jrnl will treat it as a directory.

**Comment by micahellison** [comment]
I like the notion of jrnl being able to identify directory journals by a slash at the end. We should be sure to check for both forward and back slashes to ensure it works for Windows users.
