### ISSUE TITLE
Will adding arbitrary text to jrnls break anything?

### ISSUE THREAD

**Issue by Serif-7** [jrnl-org/jrnl#1295]
I have a very long jrnl with only ASCII characters, but some entries are just text I inserted in. Will this break anything? In what situations does jrnl rely on the formatting, besides searching?

**Comment by micahellison** [comment]
Hi @Alekhine51, the only real delimiter in jrnl is a new line starting with [ and followed by some digits. It's used to identify the date. So you should be able to do add anything else without messing with the structure of your journal entries.

That said, if you're editing your journal directly, I still recommend backing it up before doing so, just in case.
