### ISSUE TITLE
Entries from directory based journals do not get deleted

### ISSUE THREAD

**Issue by viegasfh** [jrnl-org/jrnl#1316]
### Environment
  - `jrnl --diagnostic` output: 
  - Install method: 
jrnl: v2.8.1
Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]
OS: Linux 4.4.0-19041-Microsoft

Installed using pip

### Current Behavior

Today I added an entry to one of my directory journals by mistake and when I tried to delete the entry, it was just not deleting it.

### Expected Behavior

When running the command to delete entries, it is expected that entries for both file based and directory based journals should be removed uppon confirmation. Unfortunately, only file based entries are deleted.

### Repro Steps

1) Add the entry to the directory based journal
2) Try to remove the entry with jrnl two -n 1 --delete (here I am using two as directory based journal)
3) List the last entry and it should still be there

### Other Information

There isn't really much to be added here. It is just silent. You expect the entry to be removed, but it isn't.

**Comment by viegasfh** [comment]
Just wanted to add that if we edit the entry and delete it from the text editor, it does get deleted from the journal. That is,

If you do the following steps:

1. Add entry to journal: jrnl two Test Entry. This is the body of the entry
2. jrnl two -n 1 --edit
3. Remove the date with timestamp, title and body of the entry and then save
4. jrnl two --export short
5. The entry shouldn't be there any more

This is the workaround I found at the moment. In the command line it doesn't remove the entry.

**Comment by micahellison** [comment]
Thanks for filing this bug, and for commenting on the workaround. I just verified the workaround works for me as well (jrnl v2.8.2).

**Comment by viegasfh** [comment]
Great! The workaround has been working for me. It is more work, but it works until you guys get it fixed.
