### ISSUE TITLE
Document folder journal and DayOne journal types

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1326]
## Documentation Change

I don't see documentation about the folder journal and DayOne journal types.

### Affected Page(s)

Maybe this should be a new section?

### What Could Be Better?

It would be good to document:
- [x] the methods jrnl uses to identify journal types
- [x] folder journals and DayOne journals can't be encrypted
- [x] the path/filename structure of the folder journal

### Other Information

Maybe mention and/or link to a couple known issues re: folder journals.

**Comment by viegasfh** [comment]
I wish this documentation was there when I started using jrnl. It was all trial and error and looking at the source code. So, thumbs up to this addition to the documentation.

I agree with you on creating a separate section for this.
