### ISSUE TITLE
"jrnlsh" similar to "tasksh" in TaskWarrior?

### ISSUE THREAD

**Issue by darkpixel** [jrnl-org/jrnl#1336]
## Feature Request
I would love to see a jrnl script sorta like 'tasksh' from taskwarrior.
In tasksh, I can just type "add blah" or "list" or "done 5".
In my imaginary 'jrnlsh', I could simply start typing "I worked on xyzproject" or "Received a phone call" and it would automatically add a journal entry.
If it were an ncurses-like interface, it could automatically 'refresh' and display ```jrnl -from today``` above the prompt.
Maybe have a few 'reserved' words that when entered perform actions (like 'edit', 'today', etc...)

### Use Case/Motivation
* It would save typing (it adds up over time)
* It could automatically handle things that would mess up the shell--like: ```jrnl Today I'm going to conquer the world```. (The apostrophe would cause bash to wait for more input.)

### Example Usage
```
$ jrnlsh
jrnl> Received a phone call
[Entry added to default journal]
jrnl> I'm working to solve a problem
[Entry added to default journal]
jrnl> today
2021-09-08 08:03 Received a phone call

2021-09-08 08:08 I'm working to solve a problem

jrnl> edit
*brings up configured editor for making adjustments*
* close editor and save *
[2 entries deleted]
jrnl>
```

**Comment by micahellison** [comment]
Hi there @darkpixel, thanks for filing this. I can imagine that having an interactive mode like this would be very useful.

It could be extra useful for people with multiple journals if it could "open" a journal in your session then treat it as the default journal for the rest of the session:
```
jrnl> open phonecalls
jrnl phonecalls> got another spam call from 555-555-5555
[Entry added to phonecalls journal]
```

As far as implementation goes, I think the most pressing question is: should it be built into jrnl, or should it be an external tool that uses jrnl as a dependency? I could see it being useful either way, though each approach has its own issues. Building it into jrnl could mean significantly expanding the maintenance burden of this application, whereas building it as a separate tool could mean having to deal with version mismatches and all the fun (not fun) issues that come with inter-process communication in a cross-platform app.

**Comment by darkpixel** [comment]
I think if ```jrnlsh``` were an external tool and was just making a few simple calls to ```jrnl``` it wouldn't be that difficult to manage version differences.  While I haven't been using ```jrnl``` for very long, I'm guessing the basic syntax for adding, editing, and deleting entries hasn't changed much.  Maybe I'll take a stab at stubbing something out.

**Comment by darkpixel** [comment]
Here's an extremely simple example:
https://github.com/darkpixel/jrnlsh

**Comment by darkpixel** [comment]
Packaged it up and published it.
```pip install jrnlsh```

**Comment by viegasfh** [comment]
This is an interesting idea. To have a jrnl shell sort of tool. I work mainly with vim for editing my journal entries, so interactive would be more useful for querying for me. But it I could launch vim from this tool and then vim return control to this jrnlsh, I'd probably use it.

**Comment by darkpixel** [comment]
Maybe I'm misunderstanding @viegasfh, but it does that already if you type ```edit```, although it can probably use some improvement, like limiting it to just today's entries.

Or are you talking about when you just type ```jrnl``` and get vi for creating a new entry?

**Comment by viegasfh** [comment]
Sorry, @darkpixel ! I missed that part. You even described it in the Example usage, but somehow I totally missed it. Sorry for misinterpretation.

I have installed it and will try to play around with it whenever I have time.

Thanks for sharing it!

**Comment by micahellison** [comment]
Very cool! I'm going to close this issue, but feel free to comment back here when it's more stable or if you have any more questions about jrnl as you work on it.

**Comment by darkpixel** [comment]
No worries @viegasfh!  Hopefully it works well for you.

Thanks @micahellison!
