### ISSUE TITLE
Support tzlocal v4

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1338]
## Feature Request

We use [tzlocal](https://pypi.org/project/tzlocal/) for some time-related logic in the DayOne class. v3.0 came out recently (as seen in #1319) but it breaks our tests. [I commented on the PR with a little research as to why](https://github.com/jrnl-org/jrnl/pull/1319#issuecomment-903180040).
Update: tzlocal has already moved up to v4.1, however it's still failing here: #1369.

### Use Case/Motivation

I'm not sure that v3.0 adds anything particularly useful for jrnl, but it's nice to stay on top of new releases for repos like AUR that prefer not to isolate their Python environments for each application.

### Example Usage

n/a

### Other information

A resolution to this issue should include tzlocal v3 or greater with passing tests but no functionality changes.

**Comment by dotlambda** [comment]
The tests run fine on tzlocal version 4. See https://github.com/regebro/tzlocal#api-change

**Comment by micahellison** [comment]
It does look like it'd be best to just move to 4.0+ instead of 3, and I'll change the issue accordingly. But the tests for tzlocal 4.1 are failing on every platform but the Mac in PR #1369. If anyone would like to fix these issues, feel free to submit a PR.

**Comment by micahellison** [comment]
I'm starting to wonder if we need tzlocal at all. A lot of changes have happened to the Python stdlib when it comes to time zone handling, and maybe we can just use that built-in functionality instead of regularly adapting to changes in this library.

**Comment by outa** [comment]
Hi! I'm a happy jrnl user and I would like to contribute here.
I did some googling and it seems like you cannot use just the stdlib. You can get the UTC offset like [describe here](https://discuss.python.org/t/get-local-time-zone/4169/3), but I didn't find a way to get the timezone name (e.g. "Europe/Berlin"). The name in the linked code snippet just prints "CEST" for me.

So I would try to make it work with tzlocal v4.x.
