### ISSUE TITLE
Prompt to include colors in config when first running jrnl

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1372]
### Use Case/Motivation

The colors are a relatively new feature that can be modified in the config file, but we never enabled them in the default configuration. It seems like a good question to ask new users about, with a default to "yes".

### Example Usage

When you first run jrnl and there is no config file found, you encounter a wizard with a couple prompts like this:
```
Path to your journal file (leave blank for /home/micahadmin/.local/share/jrnl/journal.txt):
Do you want to encrypt your journal? You can always change this later [y/N]
```
I imagine this feature adding another line, like:
```
Do you want the jrnl interface to use colors? You can always change this later [Y/n]
```
(that's defaulting to "Y" here)

### Other information

I think this is a good default color config (thanks @wren for these), though I'm open to discussion on this:
```
colors:
  body: none
  date: black
  tags: yellow
  title: cyan
```

Thanks to @dufferzafar for raising this question in #1352.

**Comment by apainintheneck** [comment]
I like this idea but I think that using black as a default color would be a bad idea. It should be some color that shows up well on light and dark colored terminal backgrounds like for example green.

**Comment by wren** [comment]
@apainintheneck That's a good point. On a related note, we'll be switching colors to use the `rich` library soon (instead of `colorama`), so we'll have more options available to choose from.

**Comment by micahellison** [comment]
I tried it out with a green date but I felt it clashed with the cyan title a little bit. However, magenta looks nice to me for the date:

![image](https://user-images.githubusercontent.com/4383304/220719876-f8d46549-e572-443a-9fcf-ed2cea26b128.png)
