### ISSUE TITLE
Tab complete on tags

### ISSUE THREAD

**Issue by mcbennet** [jrnl-org/jrnl#1376]
### Use Case/Motivation

A useful feature would be to allow users to tab complete any defined tags. For instance, if the user creates todo lists with jrnl, with entries such as:

```
> jrnl @todo @inprogress Take out the trash.
> jrnl @todo @inprogress Walk the dog.
```

Since the tags `@todo` and `@inprogress` are typed for every such entry, it would be convenient if the user could start to type a tag `@to` then use tab to auto-complete it (`@todo` in this case) if there are no ambiguities with other tags.

### Example Usage

`jrnl @to<TAB> @inp<TAB>` would expand to `jrnl @todo @inprogress` if there are no ambiguities with other tags.

**Comment by micahellison** [comment]
Hi, thanks for filing this. I agree that this would be nice, and we actually have an older issue on this with slightly different wording in #618. I'm going to close this issue as a duplicate, but anyone interested in this feature is welcome to submit a PR.
