### ISSUE TITLE
Maintainers are on vacation until January 8, 2022

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1388]
We'll be on vacation for the rest of December and early January. We'll back on January 8 to review any new PRs or issues.

**Comment by wren** [comment]
![Vacation dog](https://media0.giphy.com/media/j0QzDgFZRX2njRxxtP/giphy.gif)

**Comment by wren** [comment]
![Vacation dog](https://media0.giphy.com/media/J546wv1ja2LkrAwRBm/giphy.gif)

**Comment by micahellison** [comment]
We're back!
