### ISSUE TITLE
Customize bracket style in --timeformat option

### ISSUE THREAD

**Issue by sebhahn** [jrnl-org/jrnl#1402]
### Use Case/Motivation

I would like to customize the style (brackets) used for the timeformat (e.g. *" <date>: title" to create a .org (emacs org mode) compatible journal file)

### Example Usage

jrnl --timeformat '[%Y-%m-%d %H:%M:%S]: %entry'
jrnl --timeformat '%Y-%m-%d %H:%M:%S: %entry'
jrnl --timeformat '* %Y-%m-%d %H:%M:%S: %entry'

### Other information

https://github.com/jrnl-org/jrnl/blob/5463476a00218810590965e763e13866d2faa397/jrnl/Entry.py#L83

https://github.com/jrnl-org/jrnl/blob/5463476a00218810590965e763e13866d2faa397/jrnl/Journal.py#L134

**Comment by wren** [comment]
Hi! Thanks for submitting this issue. I have a few questions. 

So, we currently have the `--config-override` option that can be used to override the `timeformat` option (e.g. `jrnl --config-override timeformat 'some timeformat %Y-%m-%d etc'`). Does that do what you need?

If not, can you explain in a bit more detail what's missing? I'm not very familiar with org mode, so I'm not sure what the spec is. We've had other users mention before that jrnl already works with org mode, so I'm curious what the difference is. Is it just the colon that's missing?

**Comment by micahellison** [comment]
Closing this since it's gone stale.
