### ISSUE TITLE
Does jrnl support multiple tag symbols?

### ISSUE THREAD

**Issue by manoelpqueiroz** [jrnl-org/jrnl#1403]
### Environment
```
jrnl: v2.8.3
Python: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
OS: Linux 5.16.3-arch1-1
```
  - Install method: `pipx`

### What are you trying to do?

I'm wondering if jrnl allows for multiple tags so I could, for instance, use <kbd>@</kbd> for people and <kbd>+</kbd> for places. I haven't seen anything in the documentation mentioning this and the config file *leads* the user to think this is possible, since it has a `tagsymbols` (plural) key.

### What have you tried?

Just to see if this was implemented, I've tried using YAML arrays in the configuration, but neither of those worked and tag identification was broken when outputting the journals:

```yaml
tagsymbols: ['@', '+']

tagsymbols:
  - '@'
  - '+'
```

### Other Information

If this is not implemented, have you ever considered adding this feature? I've searched through the open and closed issues here in the repo, but a discussion around it doesn't seem to have ever existed. I think it would be a nice feature, jrnl is already great with its simplicity and allowing the user to better organize their tags would be a nice enhancement.

**Comment by wren** [comment]
Yup! Just put multiple characters like this:

```yaml
tagsymbols: '@+#^'
```

Maybe we should add support for an array, though; I can see why that would make sense.
