### ISSUE TITLE
Document flags for filtering entries by date

### ISSUE THREAD

**Issue by DanaKirsh** [jrnl-org/jrnl#1411]
### Affected Page(s)
https://jrnl.sh/en/stable/usage/#viewing-and-searching-entries

### What Could Be Better?
Documentation is missing for flags introduced in https://github.com/jrnl-org/jrnl/pull/1145
Also would be good to document `-today` https://github.com/jrnl-org/jrnl/issues/1391

**Comment by micahellison** [comment]
HI @DanaKirsh, thanks for filing this. These issues were resolved in our beta but have just been pushed over to the main site with our latest release today. The resolution to this issue is in the new command line reference page here: https://jrnl.sh/en/stable/reference-command-line/
