### ISSUE TITLE
Warn user when there are duplicate keys in the config file

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1415]
### Use Case/Motivation

If there are duplicate keys on the same level of the config file (e.g. "editor" shows up twice at the top level), our loader just picks one of them (currently the first, though I'm investigating replacing the loader with another loader that is picking the last). I think this is fine, and we should be permissive when it comes to loading the YAML file, but it would also be good to give some feedback to the user since this could be tough to troubleshoot otherwise.

### Example Usage

Maybe the warning could say something like: "Warning: the [key name here] key appears twice at the same level in your configuration file."

### Other information

It's NOT a problem if a key appears once at each level - for instance, if I have an "editor" specified at the top level, but a different "editor" specified for a particular journal. Don't warn the user in this case.

To resolve this issue:
- [ ] Add the warning when the config file loads
- [ ] Add BDD tests to ensure that the duplicate key warning:
  - [ ] appears with top level duplicates
  - [ ] appears with journal-level duplicates
  - [ ] does not appear with a value appearing once at the top level and once at the journal level
  - [ ] does not appear when using --config-override on an existing value
  - [ ] does appear when using --config-file to point to a config file with duplicate keys

**Comment by jonakeys** [comment]
Please assign this issue to me. I have the code ready, but need to create the tests. After that I'll create the PR.
Edit:
PR filed
