### ISSUE TITLE
Add --change-time command to change the timestamp of an entry

### ISSUE THREAD

**Issue by richardjs** [jrnl-org/jrnl#1429]
## Feature Request

Hello! I'm proposing an amend entry command, similar to `--edit` but that updates the timestamp for the entry.

(Or, if you prefer, if could be a flag that changes the behavior of the edit command.)

### Use Case/Motivation

I keep an entry for the day that tracks tasks completed, pomodoros logged, etc. Right now I write down the information apart from jrnl and enter it into jrnl at the end of the day. It would be a smoother (and less forgettable) task to enter information directly into a jrnl entry.

I could use `--edit`, but that doesn't update the entry timestamp. For this sort of usage, it seems the timestamp should reflect the last time the entry was edited.

### Example Usage

`jrnl --amend -1`

Perhaps it could default to the last entry (which is different than `--edit`):

`jrnl --amend` (equivalent to above)

### Other information

I'm happy to implement this myself. And I also understand this is a small tweak that may not warrant the code for it.

Thanks!

**Comment by wren** [comment]
Hi, @richardjs! Thank you for filing this issues; it's an interesting idea.

I like the idea of being able to edit the timestamp, but I'm not sure tying it to `--edit` functionality is the right approach. What about something like `--change-date` or `--update-time` (not sure about the exact name)? It could work like our current timestamps functionality when you are adding a new entry (`now` if no text is entered, or parses text as a date). So, it might look something like:

- `jrnl --change-date -1` (update the most recent entry to "now" as a timestamp; same as your example)
- `jrnl --change-date now -1` (same as previous example, but with explicit "now" is an argument)
- `jrnl -on yesterday --change-date now` (change all entries from yesterday to now)
- `jrnl -contains "some text" -and -starred --change-date "last saturday"` (it should work with any search terms)

What do you think? Would that meet your needs?

**Comment by richardjs** [comment]
That makes sense. You're right that the editing function and the date update function are two separate things, and so it makes sense to implement them separately (and we already have the edit function). And as you also point out, a user may have some reason to adjust the date to some other time than `now`.

So yeah, that works for me! I'm still happy to implement (but also have no territoriality about it).

**Comment by wren** [comment]
> So yeah, that works for me! I'm still happy to implement (but also have no territoriality about it).

@richardjs: Sounds good to me. PRs are always welcome. Thank you!

@micahellison: Do you have anything to add?

**Comment by micahellison** [comment]
Nothing to add from me, except feel free to let us know if you have any questions or want any help with the tests. We generally review PRs on Saturdays.

**Comment by micahellison** [comment]
Looks like we hadn't settled on the parameter name. I think `--change-time` would be best, since it's not "updating" per se and the word "time" encompasses both dates and times within days.

**Comment by richardjs** [comment]
OK, great. I'll get to work. Thanks!

**Comment by richardjs** [comment]
Thinking about bug in the initial version of #1452, where `--change-time` with no selectors changes time on the whole journal, I got to thinking about how this feature should function.

In a sense, changing time is a destructive action. For many or most journals, the timestamp of an entry is a very important part of its context. Erroneously changing an entry's time isn't quite as bad as outright deleting it, but it is still a destructive action we'd like to prevent.

Moreover, the most common uses of `--change-time` that I can think of only involve one entry. I have a hard time imagining why a user would want to set even a small number of entries to the same timestamp, and it seems totally unlikely that a user would ever want to change, say, the last 100 entries all to the same time.

Right now, changing one entry and changing numerous entries are just as easy to do. It's also not hard to imagine a user messing up some search parameters and accidentally changing times for more entries than they intended. Given how destructive changing times can be, I'm wondering if we should put some safeguards around the feature. But I'm unsure how.

Perhaps the most natural thing would be to require confirmation when `--change-time` changes more than one entry. The disadvantage of that is if someone **does** have a workflow that involves commonly changing times for multiple entries, they have to deal with the confirmation. We could make the confirmation threshold configurable or implement a `--no-confirm` flag, but those all could be criticized as added complexity for niche cases.

@wren and @micahellison, what do you think?

**Comment by micahellison** [comment]
Hi @richardjs, thanks for your careful consideration on this issue. I also like the notion of having a confirmation -- and in fact, we already have this behavior with our `--delete` parameter. I think using the same behavior in `--change-time` would be a good practice.

For now, I don't think the `--no-confirm` is necessary for this feature to roll out, but it could be nice later for the reasons you mentioned. We've also had some discussion around this yes/no confirmation happening for the whole set of entries, with an option to interactively confirm each one (#978). Nice to have, but please don't feel like you have to scope that into your PR.
