### ISSUE TITLE
Add machine-readable format for --list

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1445]
### Use Case/Motivation

Currently, the only guaranteed way to know the location of your config file and journals is to run `jrnl --list`. Without that command, you'd have to either reimplement the [basedir XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) or use something simpler that's specific to your machine's configuration. Not ideal.

However, the command's output is optimized for human reading and doesn't really have a guarantee that it can be consistently parsed by a machine. We could get around this by adding an argument to view its output in a machine-readable format like JSON or YAML.

The end of #1444 mentions using a feature like this to discover journals when diffing/merging encrypted journals. I think it could be useful for a wide variety of situations, for instance, an "application-aware" backup that backs up configuration along with journal data.

### Example Usage

```
jrnl --list --format json
```
```
jrnl --list --format yaml
```

### Other information

Just a minor note that --format is also used to format journals, but would have a very different meaning in this case. If you disagree with the use of the term "format" here, feel free to chime in with other suggestions.

**Comment by thetayloredman** [comment]
Maybe a syntax like:

```
jrnl --list       Normal listing
jrnl --list=human Normal listing
jrnl --list=json JSON-based list
```
etc.?

**Comment by micahellison** [comment]
Running into an issue with this -- it won't display the machine-readable format if there is no default journal specified in the config. We need to add a test case and solution for this before resolving again.

**Comment by thetayloredman** [comment]
> Running into an issue with this -- it won't display the machine-readable format if there is no default journal specified in the config. We need to add a test case and solution for this before resolving again.

I believe the issue is resolved and this could be a new issue or comment on #1592

**Comment by micahellison** [comment]
> I believe the issue is resolved and this could be a new issue or comment on #1592

I opted to re-open it instead since this has not made it into an official release and we'd like it fixed before it does. We're working on it right now so it should be re-closed soon.
