### ISSUE TITLE
Add support for org-mode export

### ISSUE THREAD

**Issue by jgarte** [jrnl-org/jrnl#1457]
## Feature Request

Add support for org-mode export.

### Use Case/Motivation

The motivation is to have a supported way to get jrnl notes into and out of emacs with tags and all. 

I'd like to get jrnl notes into [org-roam](https://github.com/org-roam/org-roam), for example, and vice versa.

### Example Usage

 jrnl --format org

```
TODO add longer ~org-mode~ export example here
```

### Other information

There is a python library for parsing org mode called [orgparse](https://github.com/karlicoss/orgparse).

It is used by [agenda](https://github.com/rougier/agenda), a python command line application that parses an org-agenda file and creates a command line interface from it.

Maybe we can use it to implement this feature?

**Comment by micahellison** [comment]
Hi @jgarte, thanks for filing this.

From what I can see, the org mode format starts with some metadata, then goes into content. The only metadata we have for a journal entry is the title and date, so I would expect an org mode export from jrnl to look like:
```
#+title:  Title of entry
#+date:   2020-10-27

Body of entry
```
Does this sound like what you're asking for? I'm not an org-mode user so I'm not deeply familiar with what it would be like to receive this data.

**Comment by micahellison** [comment]
I'm closing this as stale, but feel free to add to this if you have any thoughts.
