### ISSUE TITLE
Pass template from comand line

### ISSUE THREAD

**Issue by jgarte** [jrnl-org/jrnl#1464]
The manual [shows](https://jrnl.sh/en/stable/tips-and-tricks/#1-command-line-arguments) how to import a template as follows:

> The template.txt file could be used to create a new entry with these command line arguments:

```
jrnl < template.txt     # Imports template.txt as the most recent entry
jrnl -1 --edit          # Opens the most recent entry in the editor
```

Could we support a feature to do the following in one step?

```
jrnl --edit --template template.txt
```

I imagine we can have a short flag also like `-t template.txt`

I'd like to be able to write a script to leverage fzf to fuzzily choose a template, kind of like org capture templates.

Having a simpler way to specify a template could simplify the code I'm trying to write.

WDYT?

**Comment by micahellison** [comment]
Hi @jgarte, sounds like a cool project. You can do this with `--config-override`, which lets you set any config value (including template) for that particular invocation of jrnl, like so:
```
jrnl --config-override template ./test-template.txt
```

**Comment by jgarte** [comment]
@micahellison 

> Hi @jgarte, sounds like a cool project.

Thanks! 

With your suggestion now, I was thinking something simple like this:

```
ls -d templates/* | fzf --multi | xargs -ro jrnl --config-override template
```

The `templates` directory contains a ton of templates that the user can fuzzy select from to use with `jrnl`.
