### ISSUE TITLE
How to rename default jrnl name and create new multiple jrnls?

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#1481]
### Environment
 Created a new jrnl on macOS. I've read the documentation and I can't find how to change the default file name as well as create new multiple jrnls. 

Please help? Thanks. (I'm new to the command line and new to being this tech savvy).

**Comment by micahellison** [comment]
Hello @dpct-fs, welcome to jrnl and the wonderful world of the command line.

To create new journals, or rename them, you'll need to open your jrnl config file in a text editor. This file is how jrnl knows where to look for journals.

To find your config file, run `jrnl --list` and look at the first line, which starts with "Journals defined in". That's the path of the config file you'll need to open in your text editor.

Once you're editing that config file, you can define your journals in the format mentioned in [this documentation page](https://jrnl.sh/en/stable/advanced/). You can also change the name of that "default" journal there. Save your changes when you're done, then run `jrnl --list` again to confirm that everything is correct.

Let me know if that works out for you, and if not, feel free share any error messages or the contents of your config file. I'd like someday to write a jrnl guide (or maybe a short video) for people new to the command line, so anything you share here could help others down the road.

**Comment by micahellison** [comment]
I'm closing this since it's getting old. Feel free to chime in if you want any more help with this.
