### ISSUE TITLE
Adding new entry with date only works with format m.d.Y

### ISSUE THREAD

**Issue by thmsklngr** [jrnl-org/jrnl#1509]
### Environment
```
jrnl: v2.8.4
Python: 3.10.4 (main, Mar 23 2022, 20:25:24) [GCC 5.4.0 20160609]
OS: Linux 5.13.0-48-generic
```

Installation method: Homebrew (on Linux)
### Current Behavior
Whenever I add a new entry specified with full date, it is always treated as `%m.%d.%Y`. As far as I have seen there is no note about this and it is not configurable as well.

### Expected Behavior
Adding an entry should also work with format `%d.%m.%Y`, maybe by adding a new option in `config.yaml`

### Repro Steps
See above.

### Other Information
EDIT: this happens only, if the day is >=1 and <=12. If I enter 13.06.2022 as example, it works as expected.

**Comment by micahellison** [comment]
Thanks for the bug report - this has been filed under another issue #696. I'm closing this as a duplicate, though I appreciate the extra info about the 13th+ day of the month.

To help with this bug, would you mind running `locale` and sharing the output? I think that reading the locale is going to be part of the solution to this and it'd be good to have a test case.
