### ISSUE TITLE
"[Nothing saved to file]" when using Sublime-Text

### ISSUE THREAD

**Issue by qazip** [jrnl-org/jrnl#1517]
### Environment
```

❯ jrnl --diagnostic
jrnl: v2.8.4
Python: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
OS: Linux 5.18.5-arch1-1
```

### Current Behavior
I edited jrnl.yaml and added 'subl' as the editor (sublime-text). When doing "jrnl", sublime opens a file correctly, however, the terminal imediately outputs the "[Nothing saved to file]". If I write something on sublime-text and save the file, it seems like it's ignored by jrnl.

### Expected Behavior
I would like to be able to use Sublime-Text as my editor.

**Comment by qazip** [comment]
Doing ` "subl -w"` as the editor seems to work.

**Comment by wren** [comment]
Looks like you already worked it out. 👍

For anyone else finding this with the same question, please see our documentation:

https://jrnl.sh/en/stable/external-editors/#sublime-text
