### ISSUE TITLE
Create an environment variable when jrnl is called

### ISSUE THREAD

**Issue by manoelpqueiroz** [jrnl-org/jrnl#1537]
### Use Case/Motivation

I am using Neovim as my editor for jrnl and I would like to disable most of my plugins to have a minimalist editor whenever I'm adding or editing entries.

As far as I know, the easiest way to enable such behaviour would be to make jrnl create a temporary environment variable when it's called.

The exact behaviour I'm trying to achieve when dealing with jrnl I am already able to achieve when I write commit messages with Git, thanks to the `GIT_EXEC_PATH` [environment variable](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) they create when calling `git commit` on the shell.

While my specific use case for this feature deals with an external program (Neovim), I do believe implementing something like this could benefit other users who could leverage the existence of this variable in their workflows.

### Example Usage

If jrnl implements an environment variable, it would be extremely simple to configure my editor to be minimal when launching from jrnl:

```vim
if !exists('GIT_EXEC_PATH') && !exists('JRNL_VARIABLE')
    " Disable plugins
endif
```

### Other information

This [answer](https://vi.stackexchange.com/a/10865) to a Stack Exchange questions seems to indicate a way to create a "dummy" environment variable whenever calling `$EDITOR` without having to expect the application to implement their own, but I haven't been able to configure it properly and it ends up setting the variable whether I call Neovim from another program or directly in the shell.

**Comment by micahellison** [comment]
Hi there @manoelpqueiroz, thanks for the thoughtful and well-elucidated feature request. This is getting me to rethink how I use editors with jrnl as well. Though I think that the way for jrnl to accomplish something like this might be a bit less specific, such as using an application hook as discussed in #921 (which, interestingly enough, is also inspired by git).

However, I also think that this is probably possible in jrnl's current state. The jrnl config file "editor" field is just a system execution call with a temporary file's path tacked on as its final argument, so you could write a shell script that sets this environment variable for you, then calls your editor while passing along the script's arguments so the editor knows where the temporary file is. You'd replace your jrnl config file's editor field with the path to this shell script.

Or, more simply: if there is a way to get your editor to do what you want via arguments, you can add those arguments onto your editor field.

Please let me know your thoughts on either of these approaches. Even if this doesn't lead to a change in jrnl's code, it could be nice to document something like this in the [tips and tricks](https://jrnl.sh/en/stable/tips-and-tricks/) section of the docs.

**Comment by wren** [comment]
> Or, more simply: if there is a way to get your editor to do what you want via arguments, you can add those arguments onto your editor field.

I think this is the ticket. ⬆️ 

The way I have my personal jrnl config file set up, it looks like this:
```yaml
editor: nvim +PencilSoft
```

Which runs the `PencilSoft` command as soon as Neovim opens. This command is from a plugin, but there's no reason you couldn't make a custom command, if you prefer.

But if you're really set on using an environment variable, you can also use the same syntax to set that variable. It might look something like this.
```yaml
editor: nvim +'let $JRNL_VARIABLE="some value"'
```

Also, by setting the variable in your `jrnl` config instead of the `EDITOR` variable, you ensure that only `jrnl` sets the value.

**Comment by viegasfh** [comment]
> > Or, more simply: if there is a way to get your editor to do what you want via arguments, you can add those arguments onto your editor field.
> 
> I think this is the ticket. ⬆️
> 
> The way I have my personal jrnl config file set up, it looks like this:
> 
> ```yaml
> editor: nvim +PencilSoft
> ```
> 
> Which runs the `PencilSoft` command as soon as Neovim opens. This command is from a plugin, but there's no reason you couldn't make a custom command, if you prefer.
> 
> But if you're really set on using an environment variable, you can also use the same syntax to set that variable. It might look something like this.
> 
> ```yaml
> editor: nvim +'let $JRNL_VARIABLE="some value"'
> ```
> 
> Also, by setting the variable in your `jrnl` config instead of the `EDITOR` variable, you ensure that only `jrnl` sets the value.

This is exactly I have mine configured, and it works fine. I use Goyo with PencilSoft.

**Comment by manoelpqueiroz** [comment]
Sorry for the latency, but thank you all for the replies, guys! I think this is the way to go as well and I hadn't thought it should be possible by simply changing the YAML configuration. Simple, practical and effective.

@micahellison, I'm closing this issue, but I'd love to make my first actual contribution here in GitHub by improving the documentation with this tip, should we create a new issue to handle this?
