### ISSUE TITLE
How to I use a text editor for creating a new entry for yesterday

### ISSUE THREAD

**Issue by NeveIsa** [jrnl-org/jrnl#1545]
`jrnl` will open the configured text editor.

But how do I use something like `jrnl yesterday:` and get the editor so that I can write my entries for yesterday?
I haven't been able to achieve this. Is there another way to do it?

**Comment by micahellison** [comment]
Hi @NeveIsa, it should work if you run this:
```
jrnl yesterday: --edit
```
Your editor will open with an entry that starts with "yesterday:" which you can finish from there.

I'm closing this, but feel free to comment here if that doesn't work on your system.
