### ISSUE TITLE
.lnk files not working when calling external editors.

### ISSUE THREAD

**Issue by Baquant** [jrnl-org/jrnl#1548]
## Bug Report

I dont know if it is right to call this a bug. I was using an external editor called "Left" and it refused to start as fullscreen. So i created a shortcut and set the startup to fullscreen. Problem is; jrnl doesn't recognize .lnk files, probably because "subprocess.call()" is being used.

### Current Behavior

jrnl produces error: "WinError 193 %1 is not a valid Win32 application"

**Comment by micahellison** [comment]
Hello @Baquant, I don't see supporting LNK files for editors as within jrnl's scope. However, you should be able to get around this by opening the properties of the LNK file to find the path to your editor, then entering that path in your config file instead.

**Comment by Baquant** [comment]
@micahellison The only reason i used shortcuts was to force the application into fullscreen. I switched to sublime text though, so there is no problem.

If anyone somehow sees this, you can probably solve this with AutoHotkey like:

```
WinWait, C:\Users\User\AppData\Local\Temp\jrnl ; (Portion of handle's title for the external editor you are using)
WinMaximize
```
