### ISSUE TITLE
DayOne issue and improvement

### ISSUE THREAD

**Issue by hs6705gc** [jrnl-org/jrnl#159]
Hi!

Thanks for the solution with the previous issue!
I now manage to list and add entries to the DayOne journal.

There is an issue however:
When a new entry is added a CRLF is added to the entry! DayOne recognizes
such entries as headers and display them in bold text! So all entries added 
with jrnl displays in bold!                                                 

Then I have a feature request! There is a location added to each entry.
Obviously jrnl does not implement this but it would be nice if there was an
option in the .jrnl_config to set a static location that was added to the
entry each time! Parameters to consider is:
Administrative area
Country
Latitude
Locality
Longitude
Place Name

Code inserted if the parameters exists in then .jrnl_config file:

``` xml
    <key>Location</key>      
    <dict>
        <key>Administrative Area</key>
        <string>Ostergotlands lan</string>
        <key>Country</key>            
        <string>Sverige</string>          
        <key>Latitude</key>
        <real>58.383400000000000</real>
        <key>Locality</key>
        <string>City</string>          
        <key>Longitude</key>
        <real>15.577170000000000</real>
        <key>Place Name</key>
        <string>Street</string>     
    </dict>
```

Thanks in advance,
Henrik

**Comment by MinchinWeb** [comment]
Currently, if you edit a Dayone entry, any existing location metadata is dumped. At a minimum, it would be nice to keep this existing metadata.
