### ISSUE TITLE
Documentation of "display_format" incorrectly states that it can be used to change date display format 

### ISSUE THREAD

**Issue by DSiekmeier** [jrnl-org/jrnl#1617]
### Diagnostic output

```shell
jrnl: v3.2
Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
OS: Linux 5.4.72-microsoft-standard-WSL2
```

### What are you trying to do?

I want the time and date of my journal entries to be displayed in a format that I am used to (day-month-year). I do not want to change the timeformat of an existing journal file or the config.

### What have you tried?

The documentation of the [Configuration File](https://jrnl.sh/en/stable/reference-config-file/) says with regard to the timeformat:

> If you would just like to change how jrnl displays dates, use display_format instead.

This is what I did, leading to an attribute error when trying the show journal entries.

### Other Information

The documentation also mentions the display_format option in combination with the formatter, so I guess the point is wrong, that it changes the output format of the time and date only. If so: this would be a great new feature.

**Comment by micahellison** [comment]
Hi @DSiekmeier, thanks for filing this. You're right that the documentation is wrong here. Currently there's no way to change how the time is displayed without also changing how this is stored. We have an open issue for that in #1098.

I'll keep this open as a docs issue so we can at least correct the docs by the next release.

**Comment by DSiekmeier** [comment]
Thanks for your reply! If you like, I can do the changes and fill in a merge request.

Best regards, Dennis

**Comment by micahellison** [comment]
> If you like, I can do the changes and fill in a merge request.

Yes, absolutely, feel free to submit a PR. Thanks for offering!
