### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by wfloydiv** [jrnl-org/jrnl#1634]
### Diagnostic output

jrnl: v3.3
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
OS: Windows 10

### What are you trying to do?

I am trying to make it so that jrnl saved my entries to my Documents, and a sub-folder in my documents, called Journals. 

### What have you tried?

I have not tried anything as I am not sure what my next steps are with the error I have been given. Error is:

FileNotFoundError
┃  [WinError 3] The system cannot find the path specified: 'C:\\Documents\\Journals\\2022'
┃
┃  This is probably a bug. Please file an issue at:
┃  https://github.com/jrnl-org/jrnl/issues/new/choose

Also attached is a screen capture of the folder in my file explorer where I want the files to go to. I see nothing in there and don't know why the error mentions '2022' at the end, because there is not another folder inside 'Journals'. 

Thanks for your time!

![image](https://user-images.githubusercontent.com/67798553/200036585-413fd294-e3ee-47a8-868f-48cdecf83a15.png)

**Comment by micahellison** [comment]
Hi @wfloydiv, I'm not sure what is happening exactly. I just tried to reproduce this issue on my Win 10 machine and it created the folders without an error.

I wonder if maybe the user you're running as doesn't have access to C:\Documents and your screenshot is actually pointing to a different documents folder (which you can find by right-clicking your Documents "smart folder" in the window in your screenshot, then Properties, then Location). If the path there differs to the path in your [config file](https://jrnl.sh/en/stable/reference-config-file/) then maybe that is the issue.

If you're still getting the issue, it could help us troubleshoot to see the debug output so we can see exactly where it's failing. You can do so by running:
```
jrnl --debug
```

**Comment by micahellison** [comment]
Hi @wfloydiv, I'm going to close this now but feel free to respond here if you're still having problems.
