### ISSUE TITLE
Can't pipe password to console

### ISSUE THREAD

**Issue by talleyhoe** [jrnl-org/jrnl#1641]
### Diagnostic output

~ →jrnl --diagnostic
jrnl: v3.3
Python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
OS: Linux 6.0.8-arch1-1

### Current Behavior

Pipe input isn't being consumed. I've also tried with 'echo -e' but for some reason it doesn't detect the stdin??

### Expected Behavior

I should be able to pipe the password into the prompt.

### Repro Steps

Encrypt journal, put password in pass (or a text file will work), then send the password down a pipe into jrnl.

### Debug output

~ -> pass journal | jrnl --debug

DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False, config_override=[], config_file_path='', text=[])
DEBUG    root         Reading configuration from file /home/ronald/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': True,'highlight': True, 'indent_character': '|', 'journals': {'default': {'encrypt': True, 'journal': '/home/ronald/.local/share/jrnl/journal.txt'}}, 'linewrap': 79, 'tagsymbols': '#@', 'template': False, 'timeformat': '%F %r', 'version': 'v3.3'}"
DEBUG    root         Using journal name: default
DEBUG    root         Updating configuration with specific journal overrides {'encrypt': True, 'journal': '/home/ronald/.local/share/jrnl/journal.txt'}
Password:

### Other Information

I'm not too familiar with python inputs, but I've traced the input to print_msg -> get_pw -> decrypt_content -> open (EncryptedJournal). This is all called on the last line of jrnl.py. 

Print_msg gets it's input via line 110
  return str(console.input(prompt=decorated_text, 
                           password=hide_input))

Maybe we can do some checks like we do in jrnl.py fn write_mode before defaulting to a console? Idk what's the best way to handle this, but I'd be happy to implement it.

**Comment by talleyhoe** [comment]
Now that I'm thinking about this, the behavior makes sense since jrnl accepts entries via stdin. Without even asking I'm sure nobody wants to remove this. So what if we added in a --password flag so we can read from stdin or provide via cmd line? Then you can pipe the entry via '(pass, entry body) | jrnl' or script with 'jrnl --password $(pass)'

**Comment by micahellison** [comment]
Hi @talleyhoe, I agree, we wouldn't want to remove the existing functionality. And we'd want to use an approach that doesn't involve passing the password in the command line, but instead passes a command to retrieve the password. That's mostly documented inthe existing issue #1303, though I'll add a note there about a possible command line argument.
