### ISSUE TITLE
Is the content of my journal visible via "jrnl -year 2022" even though it's encrypted?

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#1643]
### Diagnostic output

N/A

### What are you trying to do?

I have my journal file encrypted but when I type `jrnl -year 2022` all my entries are shown publically. Is this not vulnerable? Shouldn't those entries be hidden, like the TXT file is?

![image](https://user-images.githubusercontent.com/51487203/204325044-4feacddb-fc07-49f3-89ec-41b8731c789f.png)

### What have you tried?

N/A

**Comment by micahellison** [comment]
Hi @iamSedulous, there is no way for jrnl to unencrypt your journal without a password. When you first encrypted your journal, you were prompted to store your password on your keychain, and it looks like you entered "yes". As long as you're running as your user, it will use your keychain, though you should be able to change it by running `jrnl --encrypt` again, after which you'll receive the same prompt.
