### ISSUE TITLE
Maintainers on vacation

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#1649]
We're taking some much-needed time off to rest and recharge, so we won't be regularly reviewing PRs until January 2023. After that, we'll plan on getting back to our "most Saturdays" schedule.

You still might hear from us in the issues, but please don't expect prompt responses or in-depth reviews until next month. Thanks everyone for your patience and understanding.

**Comment by wren** [comment]
![image](https://user-images.githubusercontent.com/9453067/205512851-49cef053-b7b0-4143-b8b4-8909ee3f5b66.png)

**Comment by wren** [comment]
And we're back! Thanks for your patience, everyone.
