### ISSUE TITLE
Journal Notes before December 4 18:19 CAT Gone.

### ISSUE THREAD

**Issue by kraithus** [jrnl-org/jrnl#1650]
### Diagnostic output

jrnl: v3.3
Python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
OS: Linux 5.15.78-1-MANJARO

### Current Behavior

Journal Notes before December 4 18:19 CAT Gone. I checked the journal.txt file and all the notes dating as far back as June are not here

### Expected Behavior

That all my notes are kept intact and never go missing

### Repro Steps

No info for this

### Debug output

DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False, config_override=[], config_file_path='', text=['lorem', 'ipsum'])
DEBUG    root         Reading configuration from file /home/xord/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': '/home/xord/.local/share/jrnl/journal.txt'}, 'linewrap': 79, 'tagsymbols': '#@', 'template': False, 'timeformat': '%Y-%m-%d %H:%M', 'version': 'v2.8.4'}"
DEBUG    root         Using journal name: default
DEBUG    root         opened PlainJournal with 21 entries
DEBUG    root         Write mode: starting
DEBUG    root         Write mode: cli text detected: ['lorem', 'ipsum']
DEBUG    root         Write mode: appending raw text to journal "default": lorem ipsum
DEBUG    root         Write mode: completed journal.write()

**Comment by micahellison** [comment]
Hi there, I'm really sorry to hear you lost all that data. If there's any more information you can give us about how this might've happened, please let us know. I'm happy to help try to find steps to reproduce the issue if you have more information, but we'll need to find those steps if we're going to be able to prevent this from happening in the future.

**Comment by micahellison** [comment]
I'm closing this now, but feel free to respond back if you have any information.
