### ISSUE TITLE
Documentation Change

### ISSUE THREAD

**Issue by pconrad-fb** [jrnl-org/jrnl#1651]
### Affected Page(s)

/docs/external-editors.md or maybe /docs/usage.md—or both!

### What Could Be Better?

I can't figure out if it's possible to specify a time (`yesterday` for example) when using an external editor. If I say `jrnl yesterday: Something happened` then it skips the external editor and creates an entry directly. If I just say `jrnl` then I get the external editor, but I'm not sure how to specify a time. And of course if I say `jrnl yesterday` or `jrnl yesterday:` then I get the strange little entries you'd expect.

**Comment by micahellison** [comment]
Hi @pconrad-fb, thanks for filing this. I think there's a place in the "Usage" docs for a note about this.

You can specify the time and/or the start of an entry by adding the `--edit` argument to the `jrnl` call. For instance, if you type:
```
jrnl yesterday: all my troubles seemed so far away --edit
```
Then your editor will open with the text:
```
yesterday: all my troubles seemed so far away
```
You can add whatever you like (maybe the lyrics to a whole Beatles song), and after you save and close your editor, jrnl will add an entry with yesterday's date with everything after `yesterday:`

If anyone would like to submit a PR for this docs change (maybe referencing a less cliché song) feel free to.

**Comment by micahellison** [comment]
It turns out this duplicates #1072, which is much older, so I'm closing this issue, and we'll link the PR to that older issue as well. Still, thank you for filing this and the PR!
