### ISSUE TITLE
Cannot create an entry

### ISSUE THREAD

**Issue by jbecker7** [jrnl-org/jrnl#1665]
### Diagnostic output

jrnl: v3.3
Python: 3.11.1 (main, Dec 23 2022, 09:39:26) [Clang 14.0.0 (clang-1400.0.29.202)]
OS: Darwin 22.2.0

### Current Behavior

I installed jrnl via homebrew and am trying to run a test entry, but I am being told there is an issue with the encoding.

### Expected Behavior

It should create an entry for yesterday based on the website's instructions.

### Repro Steps

$ jrnl yesterday: Test.

### Debug output

DEBUG    root         Parsed args: Namespace(debug=True, preconfig_cmd=None, postconfig_cmd=None, filename=None, on_date=None, today_in_history=False, month=None, day=None, year=None, start_date=None, end_date=None, contains=None, strict=False, starred=False, limit=None, excluded=[], edit=False, delete=False, change_time=None, export=False, tags=False, short=False, config_override=[], config_file_path='', text=['yesterday:', 'Test.'])
DEBUG    root         Reading configuration from file /Users/JCB/.config/jrnl/jrnl.yaml
DEBUG    root         Using configuration "{'colors': {'body': 'none', 'date': 'none', 'tags': 'none', 'title': 'none'}, 'default_hour': 9, 'default_minute': 0, 'editor': '', 'encrypt': False, 'highlight': True, 'indent_character': '|', 'journals': {'default': {'journal': '/Users/JCB/Documents'}}, 'linewrap': 79, 'tagsymbols': '#@', 'template': False, 'timeformat': '%F %r', 'version': 'v3.3'}"
DEBUG    root         Using journal name: default
DEBUG    root         Updating configuration with specific journal overrides {'journal': '/Users/JCB/Documents'}
  File "/usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/cli.py", line 39, in cli
    status_code = run(args)
                  ^^^^^^^^^
  File "/usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/jrnl.py", line 61, in run
    journal = open_journal(args.journal_name, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/Journal.py", line 459, in open_journal
    return FolderJournal.Folder(journal_name, **config).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/FolderJournal.py", line 36, in open
    journal = f.read()
              ^^^^^^^^
  File "<frozen codecs>", line 701, in read
  File "<frozen codecs>", line 504, in read
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/cli.py: │
│ 39 in cli                                                                    │
│                                                                              │
│   38 │   │                                                                   │
│ ❱ 39 │   │   status_code = run(args)                                         │
│   40                                                                         │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/jrnl.py │
│ :61 in run                                                                   │
│                                                                              │
│    60 │   # Get the journal we're going to be working with                   │
│ ❱  61 │   journal = open_journal(args.journal_name, config)                  │
│    62                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/Journal │
│ .py:459 in open_journal                                                      │
│                                                                              │
│   458 │   │   │                                                              │
│ ❱ 459 │   │   │   return FolderJournal.Folder(journal_name, **config).open() │
│   460                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/3.3/libexec/lib/python3.11/site-packages/jrnl/FolderJ │
│ ournal.py:36 in open                                                         │
│                                                                              │
│    35 │   │   │   with codecs.open(filename, "r", "utf-8") as f:             │
│ ❱  36 │   │   │   │   journal = f.read()                                     │
│    37 │   │   │   │   self.entries.extend(self._parse(journal))              │
│ <frozen codecs>:701 in read                                                  │
│ <frozen codecs>:504 in read                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 6038: 
invalid start byte
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  UnicodeDecodeError                                                         ┃
┃  'utf-8' codec can't decode byte 0xa0 in position 6038: invalid start byte  ┃
┃                                                                             ┃
┃  This is probably a bug. Please file an issue at:                           ┃
┃  https://github.com/jrnl-org/jrnl/issues/new/choose                         ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by micahellison** [comment]
Hi @jbecker7, I'm not 100% sure what the problem is, however, I noticed in your config that your default journal's path is set to: `/Users/JCB/Documents` so jrnl is likely trying to open existing files in that folder and read them as journal entries. There may be some binary files that it can't parse as text.

If that's the problem, you should be able to fix it by editing your config file (which you can locate by running `jrnl --list`) so that the path is somewhere else, like `/Users/JCB/Documents/jrnl/`.

**Comment by jbecker7** [comment]
@micahellison I had not even considered that, but that fix worked perfectly! Thanks so much for your quick fix :)
