### ISSUE TITLE
Password entry mistake

### ISSUE THREAD

**Issue by SatijnDoorman** [jrnl-org/jrnl#1672]
### Diagnostic output

 ~ % jrnl
Password: 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Wrong password, try again  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Password: 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Wrong password, try again  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Password: 
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Too many attempts with wrong password  ┃

### What are you trying to do?

Dear developers,

I am trying to get into my jrnl. I just started today and I encrypted my first entry. After exiting and reentering, it appears I have made a mistake with my password entry. The chosen password appears not to be the password. Since it was a very obvious password to me, I did not store it in the password key chain :S

I am fairly new to coding / using the terminal and wonder how I could start over? 

### What have you tried?

I have tried uninstalling en reinstalling.

**Comment by micahellison** [comment]
Hi @SatijnDoorman, welcome to jrnl!

To start over, first run `jrnl --list` to find the path of your default journal. Then delete that that journal and run `jrnl` again. You'll be prompted to create a new one.

**Comment by SatijnDoorman** [comment]
Hello @micahellison,

Thank you for the help!
