### ISSUE TITLE
Visual Studio Code may store unencrypted temporary files

### ISSUE THREAD

**Issue by giuseppedandrea** [jrnl-org/jrnl#1675]
### Affected Page(s)

https://jrnl.sh/en/stable/external-editors/#visual-studio-code

### What Could Be Better?

Visual Studio Code supports local file history. A local history entry is a copy of the file at the time it was saved with some associated metadata. Local history entries persist in the `<user-data-dir>/User/History` folder.
Therefore, if Visual Studio Code is configured as external editor, unencrypted temporary files remain stored on disk.
It is possible to exclude files from local file history by using the `workbench.localHistory.exclude` setting with the following exclude pattern: `**/jrnl*.jrnl`.
Do you think it is useful to add this information in the documentation?

**Comment by wren** [comment]
Hi, @giuseppedandrea! Thanks for filing this issue. I think this is useful information, and definitely worth adding to the documentation.

I don't think VSCode is the only editor this applies to, so maybe it would be helpful to have a general section warning users about temp files in editors. And then a section about how to fix in specific editors (like VSCode).
