### ISSUE TITLE
does jrnl communicate with Dayone? How to set it up?

### ISSUE THREAD

**Issue by amelchi** [jrnl-org/jrnl#1734]
### Diagnostic output

no problem here

### What are you trying to do?

does jrnl communicate with Dayone? How to set it up?

### What have you tried?

the setting are disappeared from DayOne site

**Comment by micahellison** [comment]
Hi @amelchi, jrnl supports the DayOne Classic format, but not the more recent formats. See the ["Journal Types" docs page](https://jrnl.sh/en/stable/journal-types/#day-one-classic) for info on using jrnl to read and write to a DayOne Classic journal.
