### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by jemostrom** [jrnl-org/jrnl#1755]
### Diagnostic output

jrnl: v4.0
Python: 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)]
OS: Darwin 22.5.0

### What are you trying to do?

Newbie, trying out jrnl. I was trying export a few test entries to YAML format. My problem is that I don't get the result I was expecting. My test entry is 

```
[2023-05-31 21:05] This is the title
This is the body line 1
This is the body line 2
```

I then used `jrnl --format yaml --file tet/` to export the entries. My test entry looked like this

```
---
title: This is the title
date: 2023-05-31 21:05
starred: False
tags: 
body: |		
	This is the body line 1
	This is the body line 2
...
```

which doesn't really look like YAML to me (unless I'm misunderstanding something). The example in the documentation suggest that it should look like this

```
title: This is the title
date: 2023-05-31 21:05
starred: False
tags: 
	
This is the body line 1
This is the body line 2
```

I had expected that it would look like this

```
---
title: This is the title
date: 2023-05-31 21:05
starred: False
tags: 
	
This is the body line 1
This is the body line 2
---
```

I assume I'm missing something, but what?

### What have you tried?

Reading the manual, trying to understand what I'm doing wrong.

**Comment by piero-vic** [comment]
I think that is just how multi-line string are stored in YAML. Take a look at [this article](https://www.baeldung.com/yaml-multi-line#literal-style). Apparently that syntax is used to preserve the line breaks.

**Comment by jemostrom** [comment]
I was thinking wrong here, what I said was what I expected should actually be

```
---
title: This is the title
date: 2023-05-31 21:05
starred: False
tags: 

---

This is the body line 1
This is the body line 2
```

And that's not YAML, it's a YAML header with a body text. This is a "common" blog format used by for example Hugo and Blot. So I was completely wrong here, I was so into the possibilities of writing in jrnl and then publish it as micro post to a blog that I wasn't thinking straight. Sorry about that.

**Comment by piero-vic** [comment]
@jemostrom You could [yq](https://github.com/mikefarah/yq) to parse the YAML files and generate the output you want. A script like this should do the trick.

```bash
#!/bin/sh

frontmatter=$(yq "del(.body)" "$1" -y)
body=$(yq ".body" "$1" -r)

cat <<EOF
---
${frontmatter}
---

${body}
EOF
```

Make sure to install yq on your machine.

**Comment by micahellison** [comment]
Thanks @piero-vic for answering this. @jemostrom, I'm closing this issue but feel free to respond if you have any more questions on this.
