### ISSUE TITLE
Can't encrypt/decrypt journal when installing jrnl v4.0.1 from Homebrew

### ISSUE THREAD

**Issue by porterbhall** [jrnl-org/jrnl#1783]
### Diagnostic output

jrnl: v4.0.1
Python: 3.11.4 (main, Jun 20 2023, 16:52:35) [Clang 13.0.0 (clang-1300.0.29.30)]
OS: Darwin 20.6.0

### Current Behavior

I have an encrypted journal. I updated this morning via Homebrew, and now when I try to open that journal with the --edit flag, as in jrnl work --edit, I get this error

Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  ModuleNotFoundError                                 ┃
┃  No module named 'cryptography'                      

### Expected Behavior

It should open in my editor

### Repro Steps

1. Open an encrypted jrnl

### Debug output

[12:24:04] DEBUG    Logging start                                     main.py:32
           DEBUG    Parsed args:                                      main.py:42
                    Namespace(debug=True, preconfig_cmd=None,                   
                    postconfig_cmd=None, filename=None,                         
                    template=None, on_date=None,                                
                    today_in_history=False, month=None, day=None,               
                    year=None, start_date=None, end_date=None,                  
                    contains=None, strict=False, starred=False,                 
                    tagged=False, limit=None, excluded=[],                      
                    edit=False, delete=False, change_time=None,                 
                    export=False, tags=False, short=False,                      
                    config_override=[], config_file_path='',                    
                    text=['work', 'lorem', 'ipsum'],                            
                    exclude_starred=False, exclude_tagged=False)                
           DEBUG    Reading configuration from file                install.py:91
                    /Users/###/.config/jrnl/jrnl.yaml                       
           DEBUG    Using configuration:                          install.py:117
                    "{                                                          
                        'colors': {                                             
                            'body': 'none',                                     
                            'date': 'none',                                     
                            'tags': 'none',                                     
                            'title': 'none'                                     
                        },                                                      
                        'default_hour': 9,                                      
                        'default_minute': 0,                                    
                        'editor': 'subl -w',                                    
                        'encrypt': False,                                       
                        'highlight': True,                                      
                        'indent_character': '|',                                
                        'journals': {                                           
                            'default':                                          
                    '/Users/###/Documents/default.txt',                     
                            'work': {                                           
                                'encrypt': True,                                
                                'journal':                                      
                    '/Users/###/Documents/work.txt'                         
                            }                                                   
                        },                                                      
                        'linewrap': 79,                                         
                        'tagsymbols': '@',                                      
                        'template': False,                                      
                        'timeformat': '%Y-%m-%d %H:%M',                         
                        'version': 'v4.0.1'                                     
                    }"                                                          
           DEBUG    Using journal name: work                       config.py:205
           DEBUG    Updating configuration with specific journal   config.py:110
                    overrides:                                                  
                    {'encrypt': True, 'journal':                                
                    '/Users/###/Documents/work.txt'}                        
           DEBUG    Scoped config:                                 config.py:119
                    {                                                           
                        'colors': {                                             
                            'body': 'none',                                     
                            'date': 'none',                                     
                            'tags': 'none',                                     
                            'title': 'none'                                     
                        },                                                      
                        'default_hour': 9,                                      
                        'default_minute': 0,                                    
                        'editor': 'subl -w',                                    
                        'encrypt': True,                                        
                        'highlight': True,                                      
                        'indent_character': '|',                                
                        'journals': {                                           
                            'default':                                          
                    '/Users/###/Documents/default.txt',                     
                            'work': {                                           
                                'encrypt': True,                                
                                'journal':                                      
                    '/Users/###/Documents/work.txt'                         
                            }                                                   
                        },                                                      
                        'linewrap': 79,                                         
                        'tagsymbols': '@',                                      
                        'template': False,                                      
                        'timeformat': '%Y-%m-%d %H:%M',                         
                        'version': 'v4.0.1',                                    
                        'journal':                                              
                    '/Users/###/Documents/work.txt'                         
                    }                                                           
           DEBUG    open_journal 'work'                           Journal.py:471
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/main.py", line 44, in run
    status_code = controller.run(args)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/controller.py", line 69, in run
    journal = open_journal(args.journal_name, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 511, in open_journal
    return Journal(journal_name, **config).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 133, in open
    text = self._decrypt(text)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 94, in _decrypt
    self._get_encryption_method()
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/journals/Journal.py", line 89, in _get_encryption_method
    encryption_method = determine_encryption_method(self.config["encrypt"])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/encryption/__init__.py", line 36, in determine_encryption_method
    return getattr(import_module(f"jrnl.encryption.{my_class}"), my_class)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/encryption/Jrnlv2Encryption.py", line 7, in <module>
    from cryptography.fernet import Fernet
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/mai │
│ n.py:44 in run                                                               │
│                                                                              │
│   43 │   │                                                                   │
│ ❱ 44 │   │   status_code = controller.run(args)                              │
│   45                                                                         │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/con │
│ troller.py:69 in run                                                         │
│                                                                              │
│    68 │   # Get the journal we're going to be working with                   │
│ ❱  69 │   journal = open_journal(args.journal_name, config)                  │
│    70                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/jou │
│ rnals/Journal.py:511 in open_journal                                         │
│                                                                              │
│   510 │   │   return LegacyJournal(journal_name, **config).open()            │
│ ❱ 511 │   return Journal(journal_name, **config).open()                      │
│   512                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/jou │
│ rnals/Journal.py:133 in open                                                 │
│                                                                              │
│   132 │   │   text = self._load(filename)                                    │
│ ❱ 133 │   │   text = self._decrypt(text)                                     │
│   134 │   │   self.entries = self._parse(text)                               │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/jou │
│ rnals/Journal.py:94 in _decrypt                                              │
│                                                                              │
│    93 │   │   if self.encryption_method is None:                             │
│ ❱  94 │   │   │   self._get_encryption_method()                              │
│    95                                                                        │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/jou │
│ rnals/Journal.py:89 in _get_encryption_method                                │
│                                                                              │
│    88 │   def _get_encryption_method(self) -> None:                          │
│ ❱  89 │   │   encryption_method = determine_encryption_method(self.config["e │
│    90 │   │   self.encryption_method = encryption_method(self.name, self.con │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/enc │
│ ryption/__init__.py:36 in determine_encryption_method                        │
│                                                                              │
│   35 │                                                                       │
│ ❱ 36 │   return getattr(import_module(f"jrnl.encryption.{my_class}"), my_cla │
│   37                                                                         │
│                                                                              │
│ /usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/ │
│ 3.11/lib/python3.11/importlib/__init__.py:126 in import_module               │
│                                                                              │
│   125 │   │   │   level += 1                                                 │
│ ❱ 126 │   return _bootstrap._gcd_import(name[level:], package, level)        │
│   127                                                                        │
│ in _gcd_import:1204                                                          │
│ in _find_and_load:1176                                                       │
│ in _find_and_load_unlocked:1147                                              │
│ in _load_unlocked:690                                                        │
│ in exec_module:940                                                           │
│ in _call_with_frames_removed:241                                             │
│                                                                              │
│ /usr/local/Cellar/jrnl/4.0.1_3/libexec/lib/python3.11/site-packages/jrnl/enc │
│ ryption/Jrnlv2Encryption.py:7 in <module>                                    │
│                                                                              │
│    6                                                                         │
│ ❱  7 from cryptography.fernet import Fernet                                  │
│    8 from cryptography.fernet import InvalidToken

**Comment by micahellison** [comment]
Hi @porterbhall, thanks for reporting this. It looks like the brew formula is no longer including `cryptography`. I've reported it to the person that made the change. I think that installing an earlier version or revision from brew would help in the meantime.

**Comment by micahellison** [comment]
This is resolved in Homebrew now.
