### ISSUE TITLE
jrnl PermissionError "Operation not permitted" on iOS

### ISSUE THREAD

**Issue by plt-prx** [jrnl-org/jrnl#1800]
### Diagnostic output

```
jrnl: v4.0.1
Python: 3.11.0 (heads/3.11-dirty:2af28c9018, Apr 23 2023, 19:57:1
4) [Clang 14.0.3 (clang-1403.0.22.14.1)]
OS: Darwin 23.0.0
```

### Current Behavior

I am trying to set up a jrnl in an iCloud directory on my iOS device (using a-shell) so I can write to it from various devices. I have read / write access to the folder but when I try to import an existing or create a new journal I get the following error. I got access to the folder through a-shell‘s pickFolder function. 

```
[~jrnl]$ jrnl
┏━ Error
┃  PrermissionError                                             
┃  [Errno 1] Operation not permitted:                          
┃  '/private/var/mobile/Library/Mobile                         
┃  Documents/com~apple~CloudDocs/jrnl-cloud'                   
┃                                                               
┃  This is probably a bug. Please file an issue at:             
┃  https://github.com/jrnl-org/jrnl/issues/new/choose
```           

### Expected Behavior

Import an existing or create a new journal. 

### Repro Steps

Using jrnl in a-shell to make a journal in the iCloud directory.

### Debug output

[debug.log](https://github.com/jrnl-org/jrnl/files/12708127/debug.log)

**Comment by micahellison** [comment]
Hi @pltprx, I don't use iOS, but based on the error and the debug log, it looks like the something running jrnl doesn't have permission to the path that the journal is stored in. The "operation not permitted" message looks similar to [this issue](https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update) that fixed it by manually setting some Terminal (or in your case, a-shell?) "Full Disk Access" permissions in System Preferences. Does that help fix the issue?

**Comment by pltprx** [comment]
Hi @micahellison thank you for you quick response. I am afraid this is not possible due to the strict iOS restrictions. I switched to iSH (Alpine) and now got it working.

**Comment by plt-prx** [comment]
Hi @micahellison thank you for you quick response. I am afraid this is not possible due to the strict iOS restrictions. I switched to iSH (Alpine) and now got it working.

**Comment by micahellison** [comment]
Sorry to hear about those restrictions. Thanks for following up about them.

**Comment by wisscot** [comment]
Hello @plt-prx , how did you install jrnl in iSH?  I am trying to install jrnl with pip3 in iSH in my iphone but failed with "can't find Rust compiler" error.  The Python3 I installed in iSH is v3.9 not sure if that matters.  Thank you.
