### ISSUE TITLE
Is it possible to change filetype to .md in config file?

### ISSUE THREAD

**Issue by vinoff** [jrnl-org/jrnl#1801]
### Diagnostic output

```
❯ jrnl --diagnostic
jrnl: v4.0.1
Python: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
OS: Linux 6.5.5-arch1-1
```

### What are you trying to do?

By default, it seems like new diary/journal entries are saved in .txt. I am using an external editor. Is there any config parameter for the jrnl.yaml that changes the filetype from .txt to .md (markdown)?

### What have you tried?

I tried searching the issues but couldnt find anything.

**Comment by VirbickasGytautas** [comment]
Yes, you can change the default file type for new diary/journal entries in Jrnl from .txt to .md (markdown) by modifying your jrnl.yaml configuration file. If you don't have a jrnl.yaml file, you can create one in your Jrnl configuration directory.

Follow these steps to configure Jrnl to use Markdown:

1. Open or create the jrnl.yaml configuration file in your Jrnl configuration directory. You can usually find it in your home directory.
2. Add the following lines to the jrnl.yaml file to specify that you want to use Markdown as the default file type for new entries:

yaml
```
editor: your_external_editor_of_choice
file_extension: .md
```

Replace your_external_editor_of_choice with the actual command or path to your external text editor. The file_extension option is set to .md to specify the file type as Markdown.

3. Save the jrnl.yaml file.

Now, when you create new diary/journal entries using Jrnl, they should be saved with the .md file extension, and you can use your preferred external Markdown editor to edit them.

Make sure to adjust the configuration to your liking, including specifying the correct path to your external editor if it's not in your system's PATH.

**Comment by vinoff** [comment]
Oh, thank you! I didn´t see file_extension in the user-guide. I searched for that but got no results:

https://jrnl.sh/en/stable/search.html?q=file_extension

**Comment by vinoff** [comment]
`file_extension: .md` this does not work. Was I just chatGPTd?

**Comment by VirbickasGytautas** [comment]
Chatgpt offers the same thing. You can try to do it manually

```
cd ~/jrnl_entries

for file in *.txt; do
    mv -- "$file" "${file%.txt}.md"
done
```

**Comment by micahellison** [comment]
> By default, it seems like new diary/journal entries are saved in .txt. I am using an external editor. Is there any config parameter for the jrnl.yaml that changes the filetype from .txt to .md (markdown)?

Hi @vinoff, it is possible to do what you want through the `template` config key. You create a template file with the extension that you prefer, then add the `template` key to your YAML file with the path. Even if it's just a blank file, jrnl will use the template's extension as the extension of the temporary file you're editing.

I'm closing this as resolved, though if you run into any trouble with this approach, feel free to respond here.

@VirbickasGytautas, I am hiding the incorrect answers you posted. Please don't use chatbots to answer questions here.

**Comment by vinoff** [comment]
@micahellison, thank you for the reply.

I do that and it is not working, it seems. Here is my config:

```
colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: neovide --nofork --multigrid
encrypt: false
highlight: true
indent_character: "|"
journals:
  default: /home/vinoff/docs/journal/
linewrap: 80
tagsymbols: "#@"
template: /home/vinoff/docs/journal/template.md
timeformat: "%Y-%m-%d %H:%M"
version: v4.0.1
```

As you see, the template has the .md extension. When I do `jrnl`, it does open an .md file with the appropriate syntax. However, when saved, it saves as .txt. 

Can you reproduce?

The issue is that I wanted it saved as .md, not as .txt.

**Comment by micahellison** [comment]
Hi @vinoff, apologies, I misunderstood the question (now *I* feel like a chatbot!!!).

When it comes to actual data storage, [the file extension can be set to anything for a single-file journal but not a folder journal](https://jrnl.sh/en/stable/journal-types/), which is the type of journal you're using.

We do have an open issue to allow you to do change the extension for a folder journal (#1289), though I'm not sure if the current contributor is actively working on it still. However, you can follow that issue if you'd like to know when you can use this in the future.

**Comment by vinoff** [comment]
Ah, I see. Thank you @micahellison!
