### ISSUE TITLE
Support alternative date formats when inputting

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#183]
First of all, thanks a lot for this project. I like it a lot so far, except for one thing. I am Dutch, and here we use either yyyy-mm-dd or dd-mm-yyyy, but never mm/dd/yyyy and as such this format can be confusing for me (and most people outside the US). This is no problem for the output which can also be configured, but when inputting entries the following both do not seem to work as expected:

`jrnl 1-12-1990 at 12:00: a long time ago` => `2014-06-25 12:00 a long time ago`
`jrnl 1990/12/1 at 12:00: a long time ago` => `2014-06-25 12:00 a long time ago`

**Comment by nylki** [comment]
This was apparently closed in #49f67df in 2014, yet I can't find any documentation  on how would I change the language format to something other than English. Is the functionality implemented but not documented (or have I missed the relevant part?) or is there still some part left to be implemented.
