### ISSUE TITLE
How can I set macOS TextEdit as external editor?

### ISSUE THREAD

**Issue by rghedin** [jrnl-org/jrnl#1841]
### Diagnostic output

jrnl: v4.1
Python: 3.11.7 (main, Dec 11 2023, 23:15:04) [Clang 15.0.0 (clang-1500.0.40.1)]
OS: Darwin 23.2.0

### What are you trying to do?

I really like journaling on TextEdit, the default macOS text editor, and I'd like to use it with jrnl.

### What have you tried?

I tried some weird/quirk commands to summon TextEdit via CLI, but none worked.

**Comment by utopiatopia** [comment]
> I tried some weird/quirk commands to summon TextEdit via CLI, but none worked.

Could you please tell us what commands you have tried to use to summon TextEdit?

---

Using the iA Writer documentation except with TextEdit’s bundle identifier, TextEdit (un)blocks correctly when run in the terminal, however fails to unblock after it’s closed when using jrnl.

**Comment by utopiatopia** [comment]
After looking into this further, I’m suddenly unable to replicate this issue. `editor: 'open -b com.apple.TextEdit -Wn'` works as I would expect. Although, you have to terminate TextEdit, not just close the window.

**Comment by rghedin** [comment]
Thanks, @utopiatopia!
