### ISSUE TITLE
How to update jrnl from the version 2.8.4 to the last one (4.1)

### ISSUE THREAD

**Issue by ludetie** [jrnl-org/jrnl#1869]
### Diagnostic output

jrnl: v2.8.4
Python: 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]
OS: Linux 5.4.0-174-generic

### What are you trying to do?

I am trying to update from the version 2.8.4 to the last one (4.1)

### What have you tried?

I did "pipx upgrade jrnl" but it does not upgrade and reinstall the version 2.8.4

**Comment by ludetie** [comment]
ludetie@xxxxx~$ pipx upgrade jrnl
jrnl is already at latest version 2.8.4

**Comment by micahellison** [comment]
Hi @ludetie, jrnl 2.8.4 is the latest version of jrnl that still supports Python 3.8, which is the current version of Python that you have installed. Once you upgrade Python, then pipx, you'll be able to use pipx to upgrade jrnl to the latest version.
