### ISSUE TITLE
Feature Report : Custom save location

### ISSUE THREAD

**Issue by IkelAtomig** [jrnl-org/jrnl#1891]
### Use Case/Motivation

It would be better to have a save location apart from the default `~/Documents` such as Cloud Storage drives for syncing across devices.

### Example Usage

jrnl --save-location <--directory-->

**Comment by micahellison** [comment]
Hi there, jrnl already allows you to have a custom save location. You can enter the journal's path in first prompt when you first run jrnl, and you can edit a journal's location by editing your config file, whose path you can find after running: `jrnl --list`

**Comment by IkelAtomig** [comment]
You need to write the help pages clearly I think regarding this.

**Comment by matthiasbeyer** [comment]
Reviving this: The documentation says nothing about this. Also it does not say how I can set this in the configuration.
I came across this issue when searching for how to set a location per journal.
