### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by Anja93728** [jrnl-org/jrnl#1907]
### Diagnostic output

Hi, I can't find the android App for jrnl. 
Even the link on the website to google Play Store is not working...
Is this a german isssue?
Btw the link to Apple App Store and jrnl ias IOS app is working correctly...
Thanks for helpdesk!

### What are you trying to do?

Download google App for jrnl

### What have you tried?

Link on Signatur in Page, Google store  directly...

**Comment by micahellison** [comment]
There is no Android app for jrnl. Maybe you're looking for a different application with a similar name?
