### ISSUE TITLE
Writing a journal entry with tomorrow's date

### ISSUE THREAD

**Issue by galloramiro** [jrnl-org/jrnl#1909]
### Use Case/Motivation

Usually I tend to prepare my day in advance, so the night before I try to write all the things that I wanna do. 
Today I tried to create a note for tomorrow and I wasn't able to do that.

I tried:
```bash
❯ jrnl $(date --date="next day" +"%Y-%m-%d") --config-file ~/dotfiles/jrnl/jrnl_linux.yaml --template ~/dotfiles/jrnl/templates/day_start.md
❯ jrnl "$(date --date="next day" +"%Y-%m-%d")" --config-file ~/dotfiles/jrnl/jrnl_linux.yaml --template ~/dotfiles/jrnl/templates/day_start.md
❯ jrnl 2024-07-24 --config-file ~/xxxx/jrnl/jrnl_linux.yaml --template ~/xxxx/jrnl/templates/day_start.md
❯ jrnl 2024-07-20 --config-file ~/xxxx/jrnl/jrnl_linux.yaml --template ~/xxxx/jrnl/templates/day_start.md
❯ jrnl 2024-07-24 at 08:00 --config-file ~/dotfiles/jrnl/jrnl_linux.yaml --template ~/dotfiles/jrnl/templates/day_start.md

```
And neither of this works. 

### Example Usage

```bash
jrnl tomorrow --edit
```
So I can have all the task for tomorrow just there. 
Thanks!

**Comment by galloramiro** [comment]
I also tried to do it like this:
```bash
❯ jrnl 2024-07-24: a --config-file ~/xxxx/jrnl/jrnl_linux.yaml --template ~/xxxx/jrnl/templates/day_start.md
```
And creates something but ignores the template

**Comment by micahellison** [comment]
Hi @galloramiro, sorry for the slow response. To start an entry for tomorrow, this should work:
```
jrnl tomorrow: This is the start of an entry --edit
```
Your editor will appear with the text "tomorrow: This is the start of an entry" which you can continue writing. Once you save, the entry will appear in your journal for tomorrow.

You can also write you entry without `--edit` if you are writing your entire entry on the command line:
```
jrnl tomorrow: This is everything I have to write about tomorrow
```
