### ISSUE TITLE
Feature: provide more ways to install

### ISSUE THREAD

**Issue by github2099** [jrnl-org/jrnl#1954]
### Use Case/Motivation

please publish a flatpak app or include in APT , the need to install homebrew only for jrnl isn't justified 😆

### Example Usage

sudo apt install jrnl

flatpak install jrnl

**Comment by github2099** [comment]
or AppImage is also a good choice

**Comment by github2099** [comment]
on Fedora, you can install via more "_standard_" ways:

dnf:
https://packages.fedoraproject.org/pkgs/jrnl/jrnl/

snap:
https://snapcraft.io/install/jrnl/fedora


for dnf, dependencies are as follow:
python3 = 3.13
   [ python3](https://packages.fedoraproject.org/pkgs/python3.13/python3/fedora-41.html)-colorama >= 0.4
   [ python3-cryptography](https://packages.fedoraproject.org/pkgs/python-cryptography/python3-cryptography/fedora-41.html) >= 3
   [ python3-keyring](https://packages.fedoraproject.org/pkgs/python-keyring/python3-keyring/fedora-41.html) >= 21
   [ python3-parsedatetime](https://packages.fedoraproject.org/pkgs/python-parsedatetime/python3-parsedatetime/fedora-41.html) >= 2.6
   [ python3-pyxdg](https://packages.fedoraproject.org/pkgs/pyxdg/python3-pyxdg/fedora-41.html) >= 0.27
   [ python3-ruamel-yaml](https://packages.fedoraproject.org/pkgs/python-ruamel-yaml/python3-ruamel-yaml/fedora-41.html) >= 0.17.22
   [ python3-tzlocal](https://packages.fedoraproject.org/pkgs/python-tzlocal/python3-tzlocal/fedora-41.html) >= 4


so using package manger like dnf (and apt) is a cleaner way to install jrnl. :smile:

**Comment by github2099** [comment]
on Fedora, you can install via more "_standard_" ways:

dnf:
https://packages.fedoraproject.org/pkgs/jrnl/jrnl/

snap:
https://snapcraft.io/install/jrnl/fedora


for dnf, dependencies are as follow:
python3 = 3.13
   [ python3](https://packages.fedoraproject.org/pkgs/python3.13/python3/fedora-41.html)-colorama >= 0.4
   [ python3-cryptography](https://packages.fedoraproject.org/pkgs/python-cryptography/python3-cryptography/fedora-41.html) >= 3
   [ python3-keyring](https://packages.fedoraproject.org/pkgs/python-keyring/python3-keyring/fedora-41.html) >= 21
   [ python3-parsedatetime](https://packages.fedoraproject.org/pkgs/python-parsedatetime/python3-parsedatetime/fedora-41.html) >= 2.6
   [ python3-pyxdg](https://packages.fedoraproject.org/pkgs/pyxdg/python3-pyxdg/fedora-41.html) >= 0.27
   [ python3-ruamel-yaml](https://packages.fedoraproject.org/pkgs/python-ruamel-yaml/python3-ruamel-yaml/fedora-41.html) >= 0.17.22
   [ python3-tzlocal](https://packages.fedoraproject.org/pkgs/python-tzlocal/python3-tzlocal/fedora-41.html) >= 4


so using package manger like dnf (and apt) is a cleaner way to install jrnl. :smile:

**Comment by micahellison** [comment]
Hi @github2099, as you've found, [there are a lot of package managers that distribute jrnl](https://repology.org/project/jrnl/versions), though the only that we support directly is pipx/PyPI. We've even changed our docs to stop recommending brew (see #1886, #1888) though that change is only now just live due to the latest jrnl 4.2 release. 

I'm closing this as won't-fix since we're not going to take any action on this as jrnl maintainers, though I definitely still encourage package manager maintainers to get involved if they're interested, and to file any issues here if they run into trouble building packages.

**Comment by github2099** [comment]
do you have a guide to build from source?

**Comment by micahellison** [comment]
> do you have a guide to build from source?

We don't have a guide for that specifically, but the [contributing page](https://jrnl.sh/en/stable/contributing/) should cover most of it, and the [poetry docs](https://python-poetry.org/) should take care of the rest.

But to sum it up: after you install poetry, you should be able to run `poetry build` to build the source distribution and wheel.
