### ISSUE TITLE
Feature: Add 24 hour time to the journal

### ISSUE THREAD

**Issue by github2099** [jrnl-org/jrnl#1956]
### Use Case/Motivation

while 12 hour is good, some people (me) prefers the time to be displayed in 24-hour format.

### Example Usage

jrnl -on "today" --format fancy

the time displays in, eg. 21:00:00 instead of 09:00:00 PM

**Comment by micahellison** [comment]
Hi @github2099, this is already possible through the `timeformat` [configuration](https://jrnl.sh/en/stable/reference-config-file/) key. The main caveat is that it affects how the date is stored, not just how it is displayed, so I recommend only setting it on new journals.

Here's an example configuration using day/month/year and 24-hour time:
```
journals:
  twentyfour:
    journal: ~/twentyfour.txt
    timeformat: "%d/%m/%y %H:%M:%S"
```
And an example of how that works in the command line:
```
>jrnl twentyfour Testing new entry
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Entry added to twentyfour journal  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

>jrnl twentyfour -1 --format fancy
┎─────────────────────────────────────────────────────────────╮17/11/24 15:43:43
┃ Testing new entry                                           ╘════════════════╕
┖──────────────────────────────────────────────────────────────────────────────┘
```
