### ISSUE TITLE
Feature: Calendar view

### ISSUE THREAD

**Issue by github2099** [jrnl-org/jrnl#1957]
### Use Case/Motivation

Add a calendar grid view, indicating on which day there is/are entries

### Example Usage

something like jrnl --calendar

**Comment by github2099** [comment]
this might be the feature planned https://github.com/jrnl-org/jrnl/pull/1759

I will close this issue after I try it out, thanks @wren @micahellison

**Comment by micahellison** [comment]
Thanks for linking to the original issue, @github2099. This is live in the latest release (v4.2). Feel free to file any bugs/enhancements for issues regarding it, but otherwise I'm closing this as duplicate.
