### ISSUE TITLE
Is there any way to specify the time of a journal entry upon import?

### ISSUE THREAD

**Issue by grplyler** [jrnl-org/jrnl#221]
I originally wrote my journal in plain text files in a git repository, but I would like to move to jrnl as I like the traditionalist style and under-the-hood sophistication of it. As well as its support and active community.

How ever upon importing my old text file journals with:
jrnl < ../some_file.txt

I found nothing in the documentation that allowed you to specify a date for the imported text.

For instance, if some_file.txt was written on Christmas Day 2013, I would like to do something like:
jrnl 25 dec 2013: < ../some_file.txt
or
jrnl < ../some_file.txt --date "25 dec 2013"

Is this possible now? Am i just missing this functionality or is it not available?
Thanks.

**Comment by gimzmoe** [comment]
either I'm running an odd version of stat or that syntax isn't supported.  (not really familar with the tool)

It seems like the goal is to get the string "28 Jun 2014 10:06 <text from file> "  then pipe it into jrnl.  
When I do that I get 
> [<current stamp>]  28 Jun 2014 10:06 <text from file> 

I've found you have to cram it directly into the jrnl file/database (which wouldn't work if it was encrypted) 

Is there something wrong or is it just me? :)

UPDATE:  maybe it's a new feature, but if you " | jrnl --import " it seems to behave as described.

**Comment by wren** [comment]
@gimzmoe Yup, just use `--import`. This issue is 6 years old, and we've since added features to jrnl.
