### ISSUE TITLE
Import?

### ISSUE THREAD

**Issue by mfiers** [jrnl-org/jrnl#257]
First - "thanks for the code" - but really - thanks for the code!

The manual mentions Import & Export but apart from piping in a text file for a single entry, there seems to be no real import facilities. 

Import would be nice so I could merge journals from a number of different servers into one. Ideally, jrnl would then ignore duplicate messages.

thanks
Mark

**Comment by flight16** [comment]
@mfiers @maebert What do you imagine the jrnl command would look like for importing?

**Comment by maebert** [comment]
I'm thinking of something like

```
jrnl --import ~/path/to/journal.txt
```

to import the contents of `journal.txt` into your default journal, or

```
jrnl work --import ~/Dropbox/Apps/Day One/
```

to import all entries from Day One into your work journal. Or

```
jrnl -from june 20 --import source.json
```

To import only entries written on or after June 20 of that year.

The important bits are:

* Let's auto-detect what kind of journal we're dealing with.
* We'll then load the journal into a `Journal` object of the appropriate class.
* Afterwards apply filters and ranges
* Then load the journal we want to write to. Expand `journal.entries` by all entries in the imported journal that are NOT already in it (ie. don't import the same entry twice!)
* Save and tell user how many entries got imported.

**Comment by flight16** [comment]
I really like everything you have suggested above.  I'd love to be able to import a Day One journal into jrnl format.

As a side-note, see my latest comment in #282 regarding some ideas about import cli usage, and jrnl usage in general.

**Comment by wren** [comment]
Yup! We need to take a closer look at this functionality before committing to anything, but importing would very useful.

**Comment by micahellison** [comment]
This isn't currently scheduled, but could be useful down the line when working with plugins.

**Comment by wren** [comment]
This in the ideas bucket. We'll revisit, but closing for now to clear up the backlog.
