### ISSUE TITLE
Feature Request :  Simple TODOs.

### ISSUE THREAD

**Issue by harshnisar** [jrnl-org/jrnl#263]
Hi,

I was recently meddling with the idea of having a simple todo list which could be accessed using the terminal. A place where you can simply scribble down a todo and maybe a date and retrieve them in one command. 

I thought I would make it from scratch, but I think it can really go well with jrnl. Is adding a todo feature against jrnl's philosophy? If so, I'll just make something standalone, or else we could work on it for jrnl itself.

**Comment by NicholasMerrill** [comment]
Hi all,

I like the basic idea of "Todos" for jrnl.  Though I think that generic tasks shouldn't be tightly linked with jrnl, it seems to me there are certain todos/reminders that would be useful in any journalling application.

Specifically, I wanted a simple means of reminding myself to look back at certain entries (with a little more detail than the star feature).  There are times that I want to check back in on a goal I'd set, or an experiment I started.  Without something to remind me to check back, I can easily forget.  This is especially the case when there are a lot of entries to go through, and it takes time to read everything to find the items you've marked.

Tried using a `@todo` tag initially, but kept finding I wanted to set that reminder date, especially for things I just want to check back in on after a long time (like a week, month, or year).

Here's a [basic implementation](https://github.com/NicholasMerrill/jrnl-todos/commit/eddea56e2d8badd9e4930a4683759c687010556f) of this.  The [updated doc](https://github.com/NicholasMerrill/jrnl-todos/blob/eddea56e2d8badd9e4930a4683759c687010556f/docs/usage.rst#using-todos) shows how it could be used.

Not really suggesting a merge, but thought I'd share just the same, in case anyone was thinking of writing something in this vein.
