### ISSUE TITLE
Different password behaviour for Compose vs Edit

### ISSUE THREAD

**Issue by jfunction** [jrnl-org/jrnl#293]
When I do `jrnl` and compose a message, my editor pops up, I compose, I close the editor and it prompts for my password before commiting changes.
When I do `jrnl -1 --edit` and edit an entry, my password asked for first, I edit, I close the editor and it commits the changes.

Although the use cases are slightly different, couldn't the password be prompted for BEFORE composing? Two advantages of this are:
- If I forget my password, this is made clear to me before I compose an entry, so the entry can not be lost.
- The usecase for edit and compose are more "symmetric". This makes sense to me, since composing is a special case of editing.

Thoughts?

**Comment by wren** [comment]
I like this. Consistency is good!

**Comment by eshrh** [comment]
working on this.

**Comment by eshrh** [comment]
This was fixed by #951 so this should be closed.
