### ISSUE TITLE
Pickleing?

### ISSUE THREAD

**Issue by schollz** [jrnl-org/jrnl#334]
Hi maebert!

I love this code. I was about to write my own, but I think yours accomplishes everything I could possibly want! 

I'd like to help out to improve, if I can. I was thinking about contributing something to help speed up the code. I found that a 600k file took about 11 seconds everytime I wanted to access it. I dropped in a bunch of printed time statements, but couldn't find the main culprit. Do you know the limiting step?

My guess is that that the slow step might be the loading/sorting of the entries. In this case I think it may be useful to store/load a "state" file via Pickle to help the loading speed.

Thanks!!

**Comment by maebert** [comment]
Hi, thanks for your feedback! Is your journal encrypted?

I think parsing and sorting takes a lot of time indeed. If you're familiar with profiling in python, go right at it! If not, great time to learn it! Huy Nguyen had a nice article on line-by-line profiling a while back: http://www.huyng.com/posts/python-performance-analysis/

**Comment by flight16** [comment]
I just tried using jrnl with my DayOne journal of 2500 entries on a brand new, 2015 MacBook Pro.  4 seconds of CPU time to list the most recent entry:

<pre>
$ time jrnl dayone --short -n 1
2015-05-18 13:41 I played with Eston today and made him lunch.

real	0m4.469s
user	0m4.007s
sys	0m0.225s
$
</pre>

I agree that some sort of caching could be done.  In my opinion, sqlite would be best, because it could be selectively updated when entries change.  The solution would be such that it could be applied to any journal type.

I will start poking around at this, but don't expect anything in the next couple weeks.

**Comment by maebert** [comment]
Hmmm. I think for journal types with individual files it maybe makes more sense to build an index file with the dates and filenames. Currently writing an entry or loading the most recent ones requires loading ALL entries into memory, which is entirely unnecessary.

**Comment by flight16** [comment]
I'm with you on there being no need to load everything into memory like is happening now.

I think that by using sqlite, dates, tags, etc could be added and the filtering method could be made very efficient.  You would essentially duplicate the entire journal in the temporary database file, but I doubt anybody's journal would exceed an order of 100MB, and it would make reading much, much quicker.  If the single file journal changes outside of jrnl, jrnl will notice the timestamp and re-load the .txt into .sqlite (it would have loaded the entire thing into memory anyway, so the only overhead we're adding is writing it out to .sqlite whenever it changes outside of jrnl.  For changes inside jrnl, jrnl can be intelligent and write to the .txt file and .sqlite both).  If DayOne gets new .xml files with a timestamp newer than the latest update, they would be added to the .sqlite file.

I think it's important that the solution can be used transparently on top of any journal type to avoid special cases in the filter method in cli.py.

This would add a bit of complexity to the script, but the entire implementation would be absolutely transparent to the users, and transparent to programmers who create new journal types.  They would still have their plain text journal.

I'm not sure how much sense I'm making.  A diagram and sample code might be explain my idea better.

@maebert In your suggestion of an index file, how would it be used during the filter?  Could it be used to alleviate the slowness in @schollz's single file journal, too?

**Comment by flight16** [comment]
I'm with you on there being no need to load everything into memory like is happening now.

At first I was imagining an sqlite layer that wraps all journals and is essentially stores the entire journal, including entries.  It would add the complexity of another layer, but it would be an implementation detail, so to users jrnl is still a plain text journal.  It would be intelligently updated when entries are added and deleted, and would be rebuilt if the journal changes outside of jrnl.  The benefit of this approach is it would increase the performance of DayOne, plain text journals that @schollz originally wrote about, and any future types.

**Comment by maebert** [comment]
We'd run in all sorts of synchronicity issues there. 

That said, I'm all for having SQLite as an optional back-end for people who need performance! So the options now would be

- plain text journal
- encrypted journal
- individual plain text files
- individual encrypted files
- DayOne
- SQLite

**Comment by flight16** [comment]
An SQLite back-end is ok, but I don't see it solving this issue with slow plain text journals, or my issue with slow DayOne journals.

I think the synchroncity issues you will encounter storing a copy of the journal in SQLite will be the same as those you would encounter using an index file that contains only dates, tags, and filename pointers.

When thinking through the design, it actually seems straight-forward:

Event | Result
----------|------------
Entry is created/edited/deleted using jrnl | SQLite is updated in addition to the real Journal file
Journal file changes outside of jrnl | When jrnl runs, it notes the timestamp on the .txt has changed and reloads the .txt into SQLite.

@maebert Am I oversimplifying things?

If you're still not a fan of bunging all entry text in the SQLite I will make an index file (SQLite) for DayOne journals and see how much I can share with plain text files to address the speed problem in this post.

**Comment by dufferzafar** [comment]
Um, Why is SQLite being given a secondary status? I mean, what would be the problems in just having a SQLite database and storing all the data there?

We would still have the export functions, so users can easily export all their entries in whatever format they want.

I think a SQLite db indexed with the timestamp of jrnl entry will be the best way to store the data. 

Thoughts?

**Comment by flight16** [comment]
The way I see it is that one of the big features of jrnl is that it's plain text.  People like that.  If you make the primary storage SQLite, one of the main selling points of jrnl is lost.  maebert has previously supported the idea of somebody making an additional jrnl type of SQLite.  What I was suggesting in this thread was using SQLite internally, transparent from the user, for speed increases.
