### ISSUE TITLE
Clarify usage output between export and reading sections

### ISSUE THREAD

**Issue by flight16** [jrnl-org/jrnl#344]
When reading the usage output, I didn't expect to be able to use --short while reading a journal, but it worked.  This makes sense knowing the code, but just from reading the usage it is unexpected.

I think '--short' and '--tags' should be listed under 'Reading' with a note under 'Export' that 'Reading''s options can also be used.

<pre>
usage: jrnl [-h] [-v] [-ls] [-from DATE] [-until DATE] [-on DATE] [-and]
            [-starred] [-n [N]] [--short] [--tags] [--export TYPE] [-o OUTPUT]
            [--encrypt [FILENAME]] [--decrypt [FILENAME]] [--edit]
            [[...]]

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         prints version information and exits
  -ls                   displays accessible journals

Composing:
  To write an entry simply write it on the command line, e.g. "jrnl
  yesterday at 1pm: Went to the gym."

  

Reading:
  Specifying either of these parameters will display posts of your journal

  -from DATE            View entries after this date
  -until DATE, -to DATE
                        View entries before this date
  -on DATE              View entries on this date
  -and                  Filter by tags using AND (default: OR)
  -starred              Show only starred entries
  -n [N]                Shows the last n entries matching the filter. '-n 3'
                        and '-3' have the same effect.

Export / Import:
  Options for transmogrifying your journal

  --short               Show only titles or line containing the search tags
  --tags                Returns a list of all tags and number of occurences
  --export TYPE         Export your journal. TYPE can be json, markdown, or
                        text.
  -o OUTPUT             Optionally specifies output file when using --export.
                        If OUTPUT is a directory, exports each entry into an
                        individual file instead.
  --encrypt [FILENAME]  Encrypts your existing journal with a new password
  --decrypt [FILENAME]  Decrypts your journal and stores it in plain text
  --edit                Opens your editor to edit the selected entries.
</pre>

**Comment by micahellison** [comment]
Relates to #866 - any change to arg parsing is probably going to have an affect on the usage output.
