### ISSUE TITLE
Dayone (non-)Editting deleting entries

### ISSUE THREAD

**Issue by MinchinWeb** [jrnl-org/jrnl#351]
If you go to open up a dayone entry to edit it and don't make any changes, and close the editor, `jrnl` will delete the entry!

To reproduce:
1. `jrnl dayone -1 --edit`
2. your editor will display the entry. Close the editor without making any changes
3. `jrnl` will tell you that one entry has been deleted, and indeed the file corresponding to the entry is deleted.

The issue will likely be fixed by a small change in line 130 to 149 of [DayOneJournal.py](https://github.com/maebert/jrnl/blob/2.0-rc1/jrnl/DayOneJournal.py#L130), but I can't quite figure it out...

**Comment by maebert** [comment]
Hm.... I can't quite reproduce that on `2.0-rc1`

```console
$ python -m jrnl dayone This is a test
[Entry added to dayone journal]
$ python -m jrnl dayone -1
2015-05-18 09:21 This is a test
$ python -m jrnl dayone -1 --edit
# Quit editor without making changes
[1 entries modified]
$ python -m jrnl dayone -1
2015-05-18 09:21 This is a test
```

**Comment by MinchinWeb** [comment]
Try edit it again. It seems to only delete the entry if it is exactly the same. I've discovered that if you do this with a entry created in DayOne (the app), the first time you edit it (without editing it), it will just strip a bunch a metadata, but the next time you edit it (without editing it), it will delete the entry.

Here's what I just did:

```
C:\Users\X>jrnl dayone This is a test
[Entry added to dayone journal]

C:\Users\X>jrnl dayone -1
2015-05-18 12:53 This is a test

C:\Users\X>jrnl dayone -1 --edit
# Quit editor without making changes
[1 entries modified]

C:\Users\X>jrnl dayone -1
2015-05-18 12:53  This is a test

C:\Users\X>jrnl dayone -1 --edit
# Quit editor without making changes
[1 entry deleted]
```

**Comment by MinchinWeb** [comment]
Let's keep this in play, and make sure it is fixed by #350.

**Comment by wren** [comment]
Keeping this while we work out the Day One maintenance.

**Comment by MinchinWeb** [comment]
bump (un-stale-ify)

**Comment by wren** [comment]
@MinchinWeb How goes the plan we outlined a while back? We got the tests PR merged in, but I haven't seen the PRs for the other steps we agreed on. Are you still interested in going forward with that?

**Comment by MinchinWeb** [comment]
@wren yes, I'm still interested in it. I'm currently working through merge conflicts, and what, if any should be broken into a separate piece.
