### ISSUE TITLE
DayOneJournal tag filtering only works for lower-case tags

### ISSUE THREAD

**Issue by flight16** [jrnl-org/jrnl#354]
The following will never work:

jrnl dayone @MyCamelCaseTag # DayOne contains a tag that has uppercase

The following will:

jrnl dayone @mylowercasetag # DayOne contains a tag that is all lower-case

The reason is that when Journal.py filters on tags, it lowercases the input.  Entry.py parse_tags() lower-cases journal tags, too.  DayOneJournal does not use parse_tags(), and does not lower-case tags.

**Comment by surindergithub** [comment]
Hi,

I wondered If this issue has already been fixed then close it.

**Comment by flight16** [comment]
The pull request is still open for 2.0, so it needs to be merged.
