### ISSUE TITLE
TaskWarrior integration

### ISSUE THREAD

**Issue by drkarl** [jrnl-org/jrnl#362]
It would be awesome to have some sort of integrarior with TaskWarrior, two great command line tools working together. Something like syncinc with Taskwarrior server to create a jrnl entry with the tasks completed in a day

**Comment by flight16** [comment]
Jrnl is simply a command-line tool that accepts plain text as its jrnl format.  If you can query and reformat Taskwarrior entries to text, you could easily write a script to add entries to jrnl (either using the command-line tool jrnl, itself, or to the .txt file jrnl operates on).

**Comment by CarlosManias** [comment]
Yes, task warrior stores the tasks in text files with this format

[description:"Description for the task" end:"1429619633" entry:"1427457382" modified:"1429619646" status:"completed" tags:"something" uuid:"02e3461a-3e72-48b5-984e-a0604306c2d0"]

So I think it shouldn't be too difficult to convert from one format to another?

**Comment by drkarl** [comment]
Yes, task warrior stores the tasks in text files with this format

[description:"Description for the task" end:"1429619633" entry:"1427457382" modified:"1429619646" status:"completed" tags:"something" uuid:"02e3461a-3e72-48b5-984e-a0604306c2d0"]

So I think it shouldn't be too difficult to convert from one format to another?

**Comment by flight16** [comment]
>>> syncinc with Taskwarrior server to create a jrnl entry with the tasks completed in a day

This sounds like you're after a way to automatically create jrnl entries.  That's very easy because it is a regular CLI tool that operates on a plain text file.  If you know any scripting language that should be an hour job.

If you wanted to be more adventurous, you could create your own Journal class in jrnl.  There are already three types: Plain text, encrypted text, and DayOne (DayOne is actually a directory of xml files, but jrnl presents them nicely because there is a special DayOneJournal class that acts as the interface).

You could accomplish the first method on your own without any help from jrnl devs.

**Comment by drkarl** [comment]
Yes, that's right, the idea would be to automate the creation of jrnl entries on the work journal for the tasks created in a day. Python is not really my strength, I know better Java, Javascript, Scala, C#, C, C++, but I've looked at the classes that you mention, Journal.py and DayOneJournal.py and I can easily read the code, so I think I could write the TaskWarriorJournal class. When I find some time I'll give it a shot and do a pull request. Thank you!

**Comment by drkarl** [comment]
You can label this as "enhancement"

**Comment by awwaiid** [comment]
I made a script that ties the two together, maybe similar to what you want -- https://github.com/awwaiid/tnote

It tags the jrnl entry with the UUID of the task, which lets you re-edit the jrnl entry and find them easily. It tags the task entry and copies tags from the task entry over into the jrnl entry.

**Comment by drkarl** [comment]
That's great @awwaiid I'll have a look, thanks!

**Comment by irl** [comment]
I believe that TaskWarrior integration is going to mean different things to different people. For me, I'm probably looking at creating journal entries when I add/modify/delete/done tasks. These are all things that could be done with a hook script in TaskWarrior, not modifications to jrnl.
