### ISSUE TITLE
Encrypted entries compatible with DayOne?

### ISSUE THREAD

**Issue by drkarl** [jrnl-org/jrnl#363]
I read in issue #329 that the Narrate android app can be used with jrnl entries as it uses the DayOne format. I'm worndering if DayOne and Narrate can read encrypted jrnl entries, or it's only compatible as long as they're not encrypted?

**Comment by flight16** [comment]
DayOne support and encrypted journals are two separate formats as far as jrnl is concerned.  DayOne itself does not support encryption.  Does Narrate support encryption?  If so, I imagine support could be added in a straight-forward manner.

**Comment by drkarl** [comment]
Ok thanks, I don't know if Narrate supports encryption, I don't think so. Ok so I understand that if you want encryption then forget about compatibility with DayOne/Narrate. Fair enough, I guess...

**Comment by flight16** [comment]
@drkarl, Let's say your journal is stored at ~/Dropbox/Narrate/, and it is encrypted.  Also, let's say jrnl is enhanced to read the encrypted ~/Dropbox/Narrate/.  How will Narrate read the encrypted file if Narrate doesn't support that file format?  Isn't that a bit like encrypting a .jpg and expecting Preview.app to read it?

**Comment by drkarl** [comment]
Yes, I totally understand that, as I said you have to choose, either compatibility with DayOne/Narrate or encryption. I choose encryption anytime... but if you don't need encryption for some of your journals you can open them with OneDay/Narrate, which is convenient :)

**Comment by drkarl** [comment]
If you want, you can label this as "question" and close it.
