### ISSUE TITLE
Random entry within other read requirements

### ISSUE THREAD

**Issue by momandine** [jrnl-org/jrnl#367]
I added a tiny feature to return a random file entry, within the date requirements. I returns 1 entry if not specified, or n entries if the -n flag is used.

You can look at my fork if you're interested: https://github.com/momandine/jrnl

Thanks!

**Comment by maebert** [comment]
Interesting! What's your use case for that?

**Comment by momandine** [comment]
I added it to my .bash_profile so I can get a random snippet of my past
every time I open my terminal. jrnl became my replacement for OhLife, which
shut down last fall. I might set up an email system too.

In any case I find happening across old entries I'd forgotten about really
interesting.

**Comment by mzfr** [comment]
@maebert 	Do we need this in our project. If yes then I can work on it

**Comment by maebert** [comment]
I'd be more interested in a clever shell script that provides that functionality. jrnl is meant to be composable!

**Comment by mzfr** [comment]
So you mean a simple bash script that just parse the .jrnl file and randomly shows you the entry ?

**Comment by gregorybodnar** [comment]
I don't think you'd need to directly parse the .jrnl file. I use fzf to filter the list provided by `--short` and grab the timestamp. That gets passed to another jrnl invocation to display the full entry. Adding a random selection in place of fzf would be simple.

**Comment by maebert** [comment]
That would be a great little script to add to the [Recipes](https://jrnl.sh/recipes.html#id1)!

**Comment by insanerwayner** [comment]
I was just thinking about this the other day. I was thinking about writing a bash script to get a random entry. I was thinking I would want the following features:

- Random entry by default
- Random entry within a date range or other filters (tags, etc)
- FlashBack: Basically like timehop, or "This Day in History", to show entries from this date from years past.

I may still write the bash script, but it'd be awesome if these features were written and encorporated into the program by much better programmers than myself. I'm a scripter(sysamin) at best.
