### ISSUE TITLE
After the pip install, pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by bachrc** [jrnl-org/jrnl#368]
Hi. I just installed jrnl via pip install jrnl[encrypted], and I just wanted to add a entry to the journal, and I have this error : 
http://i.pachattiere.net/2015-07-07_22-22-39.png
I have Python 2.7.3

**Comment by MinchinWeb** [comment]
Have you tried installing `pytz`? That seems to be the missing package...

**Comment by totorolepacha** [comment]
I already have pytz up-to-date belong to pip. :/

**Comment by totorolepacha** [comment]
I already have pytz up-to-date :/

**Comment by maebert** [comment]
Could you do 

```sh
head -1 `which jrnl`
```

and make sure this is the same python that `pip --version` uses?

**Comment by fladd** [comment]
I have the exact same issue on Debian stable.

**Comment by mzfr** [comment]
I don't think this issue comes up now. @wren 	 I think we can close it.
