### ISSUE TITLE
[feature request] simplenote intégration

### ISSUE THREAD

**Issue by xinity** [jrnl-org/jrnl#372]
hy,

been playing with jrnl which is really awesome, as i'm a user of simplenote (through vim) i was thinking how it is possible to integrate jrnl with simplenote sync ?

**Comment by maebert** [comment]
Hi @xinity, there's a [python module](https://github.com/mrtazz/simplenote.py) that integrates with SimpleNote, that would be a good starting point. It's not on the top on the priority list though.
