### ISSUE TITLE
Feature request: support -not for @tag in the command line

### ISSUE THREAD

**Issue by wakatara** [jrnl-org/jrnl#374]
Much like the -and switch, it would be really great if -not could be supported as well as the -and (even if you could only use one or the other) to provide some simple boolean querying of the entries.

**Comment by anhtuann** [comment]
I would like to see that feature implemented too ! I'm using jrnl when I code to track the bugs I'm encountering tagged with @bug. When I correct them, I like to add a @fixed tag. However, it's not possible for the moment to filter the entries with @bug that I haven't @fixed yet.

**Comment by maebert** [comment]
Cool. Would `~@tag` be an acceptable syntax?

**Comment by anhtuann** [comment]
Yes that would be even more conscise. Perfect !

**Comment by treiher** [comment]
I would still like to see that feature.

**Comment by wren** [comment]
Update: `-not` is part of jrnl and currently useable, but doesn't quite work as expected. Currently using `-not` with multiple tags (e.g. `-not @one @two`) negates both tags. Ideally, `-not` would only negate the tag it's attached to (i.e. `(-not @one) @two` but without actually using parens).
