### ISSUE TITLE
Feature Request: Ability to see journal entries for the same date across X years

### ISSUE THREAD

**Issue by throughnothing** [jrnl-org/jrnl#379]
For example, if I wanted to see what I was doing on Sept 6 for the last 3 years, I could do something like:

```
$ jrnl -from "3 years ago" -date today
$ jrnl -from "3 years ago" -date "September 6"

# Default to today
$ jrnl -from "4 years ago" -date
```

I also think the flag could be `-on-date`, or just `-on`, but I think `-date` makes sense.

**Comment by maebert** [comment]
Interesting idea indeed! Not sure what the best way to implement this is, suggestions are welcome!
