### ISSUE TITLE
Use editor when adding entries in the past

### ISSUE THREAD

**Issue by gauteh** [jrnl-org/jrnl#383]
at the moment it seems like it is not possible to add entries to the past and still get the editor up:

> jrnl last saturday: 

adds an entry with the current date and the last saturday as text.

> jrnl last saturday: asdfasd

adds the entry on last saturday, but does not open the editor.

**Comment by tundramonkey** [comment]
:+1: Yeah, I have to admit I would like it to do this also. It's thrown me a few times and I've had to go back in and edit. 

Surprisingly, compared to when I installed it, I end up using the software almost solely through vim these days for the writing rather than on the command line.

**Comment by wyne** [comment]
Also, putting a smart timestamp in the editor fails to save:

```
$ jrnl
(in editor, type "yesterday: i did something". then save and quit)
[Entry added to default journal]
$ jrnl -n 1
```

The last note was not saved.

**Comment by alichtman** [comment]
@wyne Works fine for me on `jrnl version 1.9.8`

**Comment by wren** [comment]
@alichtman There's nobody working on this that I know of. Go for it!

Please chime in if you are working on this.

**Comment by wren** [comment]
This is confirmed working. We should just add a test for it in `behave`.
