### ISSUE TITLE
Error when attempting to reference more than one journal in config file

### ISSUE THREAD

**Issue by OolonColoophid** [jrnl-org/jrnl#422]
Hi all

First github issue - this is exciting. Overall, love the program...

However, I haven't been able to add a new journal (of any type--i.e. DayOne or plain .txt--whether existing or not) to the .jrnl_config file without getting the following error from jrnl (with any arguments), which I'm finding difficult to interpret:

```
[There seems to be something wrong with your jrnl config at /Users/ianuser/.jrnl_config: Expecting property name: line 2 column 22 (char 23)]
[Entry was NOT added to your journal]
```

Any idea what might be causing this? It looks as though it's not parsing the .jrnl_config file correctly, but as far as I can tell there are no formatting issues:

```
{
  "default_hour": 9,   
  "timeformat": "%Y-%m-%d %H:%M", 
  "linewrap": 79, 
  "encrypt": false, 
  "editor": "vim", 
  "default_minute": 0, 
  "highlight": true, 
  "journals": {
    "default": "~/Dropbox/CCCU/2015-2016/Research/Creativity/Biennale/IPA/ipaJournal.txt"
    "ipa":     "~/Dropbox/tmp.txt"
  }, 
  "tagsymbols": "@"
}
```

In the above example, when I remove the line `"ipa"`, everything works as expected.

Cheers

Ian

jrnl version 1.9.7

**Comment by maebert** [comment]
Welcome to Github!

I think you're missing a `,` at the end of the line before (after `"...ipaJournal.txt"`). Here's how it should look like:

```json
{
  "default_hour": 9,   
  "timeformat": "%Y-%m-%d %H:%M", 
  "linewrap": 79, 
  "encrypt": false, 
  "editor": "vim", 
  "default_minute": 0, 
  "highlight": true, 
  "journals": {
    "default": "~/Dropbox/CCCU/2015-2016/Research/Creativity/Biennale/IPA/ipaJournal.txt",
    "ipa":     "~/Dropbox/tmp.txt"
  }, 
  "tagsymbols": "@"
}
```

**Comment by OolonColoophid** [comment]
Brilliant, many thanks! Looking forward to using jrnl for my research.

Cheers

Ian

**Comment by mzfr** [comment]
@wren I think this issue was fixed. We can close this issue.
