### ISSUE TITLE
--delete ?

### ISSUE THREAD

**Issue by thomas-vincent** [jrnl-org/jrnl#434]
Instead of using --edit then delete/save/quit editor, maybe it would be easier to have a --delete command that would show the selected entries and ask confirmation to delete them, without going through the editor.
Especially convenient when managing todo lists.

$ jrnl @todo buy bread
$ jrnl @todo wash dishes
$ jrnl @todo --delete # I'm done with today's duty
2016-07-30 11:43 @todo buy bread

2016-07-30 11:43 @todo wash dishes

Are you sure you want to delete the selected entries? [y/N]

(And jrnl is a great app by the way!!)

**Comment by BenKettlewell** [comment]
Just needed this today and was surprised it didn't already exist

**Comment by g-berthiaume** [comment]
+1 
It would be nice to quickly erase jrnl entry.

Also, could we add a confirmation check if a user wants to delete more than one message? I would prefer to be warned if I'm about to delete 100 entries.

**Comment by gregorybodnar** [comment]
I think this is important for scripting as well.

**Comment by alichtman** [comment]
> could we add a confirmation check if a user wants to delete more than one message?

I think this should probably work like `$ rm -i`. Confirmation for every message deletion regardless of how many there are. Let's make it really hard to lose data.

A `-f` flag could be added to skip this confirmation, if desired. But the default behavior should be to confirm, imo.

**Comment by alichtman** [comment]
I just opened a PR to provide the ability to interactively delete items. No scripting support yet, but it's better than nothing.

**Comment by g-berthiaume** [comment]
Any news on this @alichtman ?

**Comment by alichtman** [comment]
@g-berthiaume My work is in #850, currently waiting for review.

**Comment by wren** [comment]
@g-berthiaume This should get into the next version (v2.4) after v2.3 is out of beta.
