### ISSUE TITLE
-not or private tags

### ISSUE THREAD

**Issue by torpak** [jrnl-org/jrnl#437]
Hi, i'd really like a way to exclude all entries that contain a specific tag from a query.
Either add a -not flag with a tag parameter that supresses all entries using this tag,
or, and this is my favorite solution, allow marking a tag private in the configuration, so that entries carrying it are only shown, when the tag is explicitly searched for:
For example the `@birthday` tag is marked private in my configuration and i have an entry:
`buy a gerbil for Hannah @idea @birthday`
and another:
`make blurbalgorithm faster by cacheing intermediate results @idea`
A search for `@birthday @idea` would return both entries, but a search for `@idea` only the second.

**Comment by justinbass** [comment]
This would make tagging old non-tagged entries quicker. With 100 entries tagged @birthday, searching through the normal journal to find additional entries to tag will be mostly noise (already tagged with @birthday). It is surprisingly difficult to generate a one-time list of non-tagged entries using standard linux tools (grep, sed, diff, etc.).

**Comment by BenKettlewell** [comment]
I'm not using private tags but I would like a -not feature as well. 
My use case:
@notes tag denotes a long-form post (like lecture notes or notes on a tutorial)
I'd like to then be able to search for a topic but exclude all the entries containing the @notes tag. 
e.g. `jrnl -and @docker @aws -not @notes `

#520 would probably need to be fixed before this could be implemented

**Comment by jprof** [comment]
Hey, I really love jrnl, so thanks to all the developers!

I also would like a `-not` flag as @BenKettlewell has outlined. I took a wild stab at implementing it and opened a PR: https://github.com/jrnl-org/jrnl/pull/637

Any comments or feedback is greatly appreciated, and again, thanks for the excellent tool!
