### ISSUE TITLE
Update homebrew to latest release

### ISSUE THREAD

**Issue by steve-a-jones** [jrnl-org/jrnl#468]
Looks like homebrew is still serving 1.9.7 as the latest - 

```
brew info jrnl
jrnl: stable 1.9.7 (bottled)
Command-line note taker
https://maebert.github.io/jrnl/
/usr/local/Cellar/jrnl/1.9.7 (1,394 files, 8.8M) *
  Poured from bottle on 2017-02-23 at 11:17:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jrnl.rb
```

Not sure if the latest release fixes my issue, but jrnl fails to recognize the file close event in iA Writer (the process stays open even though I have closed the file in iA Writer) - I currently have to quit iA Writer altogether before jrnl will commit my entry.

Any ideas?

**Comment by Tafkas** [comment]
Current version on Homebrew is 1.9.8. https://github.com/Homebrew/homebrew-core/blob/7866618e64c23bd1566283ba43b5506300a8632b/Formula/jrnl.rb

Could this issue be closed?

**Comment by wren** [comment]
Yup, already updated. We'll be streamlining the deployment to Homebrew soon, too, so it'll update as soon as we have a release out.

**Comment by wren** [comment]
cc: #686
