### ISSUE TITLE
Ask to confirm password

### ISSUE THREAD

**Issue by ghost** [jrnl-org/jrnl#481]
When changing or setting the password for the first time I think it would be helpful to type it twice.

**Comment by maebert** [comment]
Absolutely, I'll add that!

**Comment by gurditsbedi** [comment]
Is this feature added?

**Comment by rvashurin** [comment]
This is absolutely crucial, not only on first time setting up, but on every call to --encrypt. 

I had some problems with gnome keyring lately and was using manual --encrypt and --decrypt for a couple of weeks. Of course eventually I fat-fingered the password and now I'll have to set up a brute force attack on my own journal.

**Comment by wren** [comment]
Yup! This is a great idea!

PRs welcome.
