### ISSUE TITLE
Markdown headers first and second level as # and ##

### ISSUE THREAD

**Issue by zaw-shinoto** [jrnl-org/jrnl#487]
Markdown export is a handy feature. Could we get an option to export first and second level headers with the more often used # and ## instead of underlines?

**Comment by maebert** [comment]
That's very reasonable - I'll change that!

**Comment by MinchinWeb** [comment]
This is address in #639. We're just waiting for the release...

**Comment by wren** [comment]
Yup, this is already merged in. Just missed closing this issue. Thank you!
