### ISSUE TITLE
Error after running: pip install jrnl[encrypted]

### ISSUE THREAD

**Issue by muygalan** [jrnl-org/jrnl#489]
`Command "c:\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\muyga\\AppData\\Local\\Temp\\pip-build-6ssnupkk\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\muyga\AppData\Local\Temp\pip-hktmg6za-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\muyga\AppData\Local\Temp\pip-build-6ssnupkk\pycrypto\`

**Comment by insanerwayner** [comment]
I'm having this issue as well. I went to the PyCrypto repository and it said [it was dead](https://github.com/dlitz/pycrypto/issues/238) and to use [PyCryptoDome](https://github.com/Legrandin/pycryptodome). But I am getting the same error. I'm running on openSUSE, looks like you are on Windows. Did you have any luck with this? This worked before when I was on Ubuntu.

**Comment by jnozsc** [comment]
fix
https://github.com/maebert/jrnl/pull/501
