### ISSUE TITLE
Writing to DayOne fails, creates files in `duplicateEntries`

### ISSUE THREAD

**Issue by nthapaliya** [jrnl-org/jrnl#493]
This is DayOne Classic, syncing to iCloud. I followed the documentation and added the default entry to the .jrnl_config file, seems to be able to read DayOne entries correctly. However, I can't *write* from the command line.

See below. (A lot of the lines in the config were automatically populated)
```
~> jrnl --version
jrnl version 1.9.8

~> cat .jrnl_config
{
  "default_hour": 9,
  "linewrap": 79,
  "encrypt": false,
  "default_minute": 0,
  "tagsymbols": "@",
  "editor": "nvim",
  "timeformat": "%Y-%m-%d %H:%M",
  "highlight": true,
  "journals": {
    "default": "~/Library/Mobile Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone",
    "work": "~/.jrnl/work_journal.txt"
  }
}
```

Adding an entry via the command line
```
~> jrnl today: Installed jrnl. Trying to configure it to work with DayOne
[Entry added to default journal]
~> jrnl -n1
2017-08-03 16:30 This is not the entry you were looking for
```

Look, a new file in `duplicateEntries`. It contains the text I added from the command line. I don't know what that folder is for, I could see no reference to any duplicate file handling in the DayOne UI.
```
~> ls ~/Library/Mobile\ Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone/duplicateEntries/
C43135C7789B11E7A57FA0999B030749.doentry

~> cat ~/Library/Mobile\ Documents/5U8NS4GX82~com~dayoneapp~dayone/Documents/Journal_dayone/duplicateEntries/C43135C7789B11E7A57FA0999B030749.doentry
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Creation Date</key>
        <date>2017-08-03T15:00:00Z</date>
        <key>Entry Text</key>
        <string>Installed jrnl.
Trying to configure it to work with DayOne</string>
        <key>Starred</key>
        <false/>
        <key>Tags</key>
        <array>
        </array>
        <key>Time Zone</key>
        <string>America/Costa_Rica</string>
        <key>UUID</key>
        <string>c43135c7789b11e7a57fa0999b030749</string>
</dict>
</plist>
~>
```

**Comment by wren** [comment]
@MinchinWeb Do you have a chance to look into this one?

**Comment by MinchinWeb** [comment]
I haven't. From what I remember, the `duplicate entries` folder is used if there is a sync error, or you otherwise end up with two entries with the same id (the id is also used as the filename). Is `jrnl` creating an entry with the same ID as an existing entry? I've never used iCloud, so is it somehow related to that?

**Comment by MinchinWeb** [comment]
not stale

**Comment by wren** [comment]
I think this should be resolved now with the recent DayOne fixes in jrnl. I can't seem to repro this anymore. Can any else?

**Comment by wren** [comment]
Closing this out for now. Please let us know if anyone actually repros this again.
