### ISSUE TITLE
Edit recent days directly in editor

### ISSUE THREAD

**Issue by karbecker** [jrnl-org/jrnl#494]
Is it possible to add entries for `yesterday` or `last thursday` directly in the specified editor? Whenever I use brackets in my text or quotes I get `zsh: unknown group`. So right now I have to do two steps:

`jrnl yesterday: Title.` and after that `jrnl -on yesterday --edit`

**Comment by insanerwayner** [comment]
you should be able to put it as this when you are in the editor:

```
yesterday: Some Title

Some text here.
```
Then once you save it should be added correctly.

**Comment by kbecker87** [comment]
Thanks @insanerwayner! It would be a good idea to add this to the documentation (or did I simply overlook it?)

**Comment by wren** [comment]
Agreed! This works, but we need to add it to the documentation.

PRs welcome!

**Comment by maebert** [comment]
Fixed in https://jrnl.sh/usage/#composing-entries
