### ISSUE TITLE
Environment Variable Configuration

### ISSUE THREAD

**Issue by allonhadaya** [jrnl-org/jrnl#505]
Hi, thanks for the code!

The other day I was looking for a way to integrate my password manager with jrnl, and found a [way to hack it](https://gist.github.com/allonhadaya/83b86c1c60834fe1799666e653795ce0) with named pipes mocking the configuration file.

Allowing users to configure jrnl with environment variables would help them compose their own workflows with fewer hacks:

```bash
$ JRNL_PASSWORD="$(pass show journal)" jrnl
```

- Does this sound like a good idea?
- What should the environment variables be named?
- Should all configuration options be supported?
- How would nested configurations be handled, like the "journals" object?

I'd be happy to work on this with some guidance 😄

**Comment by maebert** [comment]
That's a clever hack indeed :) Having passwords in environment variables makes me feel very uncomfortable though and is not something I would like to encourage... Maybe the better option is to find out how to integrate your password manager with your system's default keychain. If it's in there (the 'username' would be the name of the journal and the section name `jrnl`), jrnl will find it. Depending on OS there should be a one-liner to set the keychain item from your password manager, and, if you don't trust your keychain, delete it after use.
