### ISSUE TITLE
jrnl writes to default journal if a colon is used after a journal's name

### ISSUE THREAD

**Issue by hughowens** [jrnl-org/jrnl#512]
You can't write to non-default journals without specifying a date, and when you do, it writes to the default journal instead. For example, if I have journals "default" and "projects", I would see the following behavior:

C:\Users\Me>jrnl projects now: This will work properly...
[Entry added to projects journal]

C:\Users\Me>jrnl projects: This won't, and will write to default instead.
[Entry added to default journal]

**Comment by wren** [comment]
This still happens in v2.0. If you omit the colon (`jrnl projects test entry`), it will go into the correct journal. That seems inconsistent, though, and we should fix this.
