### ISSUE TITLE
Listing entries returns body of entry

### ISSUE THREAD

**Issue by antgonzales** [jrnl-org/jrnl#514]
If I create an entry and attempt to add body content below the title using a text editor like VIM, I often times see the body contents in the entry retrieval.

Example:

```
2017-12-04 09:00 @TODO create a list of things to do.
| Todolist:
| - Here
| - Is
| - my
| - todo
| - list
```
When I run `jrnl @TODO`, I see the body contents of the entry although the title has the correct ending`.` format to signify the title vs the body.

**Comment by stelabr** [comment]
You can accomplish this with the `--short` flag.
Example:
`bash
$ jrnl @blessed
2018-01-08 20:59 Oh wow: This is so great.
| @blessed

$ jrnl @blessed --short
2018-01-08 20:59 Oh wow: This is so great.
`

**Comment by mzfr** [comment]
@antgonzales Looks like this was solved. If so please close the issue
