### ISSUE TITLE
How to set locale?

### ISSUE THREAD

**Issue by matthjes** [jrnl-org/jrnl#521]
Hi,

For my system I'm using English as the main language (LANG=en_US.UTF-8, LANGUAGE=en_US), but German for time, numbers etc (LC_TIME=de_DE.UTF-8).

I'd like to add the name of the week day (Montag, Dienstag) to my entries, so I changed the time format to "%d.%m.%Y (%A), %H:%M". But the week days are shown in English instead of German, although the value for LC_TIME is set to German.

What do I have to change so that the days are shown in German?

**Comment by matthjes** [comment]
According to this answer: 
https://stackoverflow.com/questions/48270191/python-does-not-use-locale-from-environment
the locale needs to be set inside the app as python apparently does not use the locale settings from the environment.

**Comment by micahellison** [comment]
Closing this as a duplicate since there's more recent info in #1353.
