### ISSUE TITLE
[Question] List all the tags used till date.

### ISSUE THREAD

**Issue by baluKanattil** [jrnl-org/jrnl#523]
Hello,
Is it possible to list all the tags that have been used till date?

**Comment by dvancamp** [comment]
This should do it.
`jrnl -from 1970 | grep -o '@[a-zA-Z0-9_]\+' | sort | uniq -c`

You can drop the `-c` if you don't want a count of the number of times used.

**Comment by wren** [comment]
`jrnl --tags` should do what you're looking for.
