### ISSUE TITLE
Enhancement Request: Keep Backup Journal File

### ISSUE THREAD

**Issue by makais** [jrnl-org/jrnl#524]
Request to add an option to create a backup of the journal file upon saving, such that a specified number of previous versions are retained.  In the case of a corrupted file or crash, this would avoid catastrophic data loss by reducing it to only the most recent change.

**Comment by eshanmind** [comment]
Isn't it easier to just use a DayOne journal to constantly back up the file?

**Comment by sorsasampo** [comment]
It does not make sense to reimplement a VCS (Version Control System).

Would be better if `jrnl` could (configurably) notice that the journal file has been added to `git`, and automatically commit any changes to it.

**Comment by wren** [comment]
I like the git idea, since it seems much easier to implement. But even that--and any other versioning--could get really dicey with encrypted journals, though, since it can't properly version them. I think saving your journal in a folder that is backed up by a proper backup system is best.
