### ISSUE TITLE
Win7 64 - admin - "Access is denied"

### ISSUE THREAD

**Issue by winterlaite** [jrnl-org/jrnl#528]
Win7, 64-bit, jrnl 1.9.8.
Installing via pip or by 'python setup.py install', running as admin, jrnl.exe will not run.
Error message is always "Access is denied". Dozens of other scripts with same privileges in same directory run. Have run as admin, changed properties, opened admin cmd in folder, nothing works.
"Access denied."
![jrnl](https://user-images.githubusercontent.com/10135022/37232115-7df9cf84-23e5-11e8-8d1e-143a3587ba3c.PNG)
Edit: Installing with 'pip install --user jrnl' works, but installs in AppData. The result is that it can't be called from the command line, i.e. can't pass arguments to it yet. Will keep experimenting.
Edit: Have to open an admin prompt in C:\User\Me\AppData\Roaming\Python\Python35\Scripts to run jrnl from a command prompt. Less than ideal.

**Comment by wren** [comment]
Does this still happen with v2.0? Can you try `pip install jrnl==2.0.0rc2` and let us know what happens?

**Comment by winterlaite** [comment]
I tried to install 2.0.0rc2 via pip. It wouldn't install due to errors related to the 'cryptography' package. I'm now running Python 3.7.3 64-bit, if that makes any difference. It's been quite a while since I reported the issue, and I have lost track of what I had installed at the time.

**Comment by wren** [comment]
The latest is now `pip install jrnl==2.0.0rc3 .post2`. This has a fix for the cryptography error. And sorry about how long it's been since you reported. The project has been dormant, and I'm a new maintainer trying to get everything organized again. Of you can repro this, it would be very helpful, but I also understand if it didn't come back up anymore. Than you either way!

**Comment by winterlaite** [comment]
Installed and runs fine. I had an old journal.txt, which it is writing to. However, there are no newlines between entries. Also, the installer reports that the default file is "C:\Users\me/journal.txt" [sic], which reinforces my suspicion that I may need to do some extra configuration.
