### ISSUE TITLE
Timezone Agnostic Option

### ISSUE THREAD

**Issue by gewthen** [jrnl-org/jrnl#533]
I would like an option to have all dates in 8601 format with a GMT timezone so that when traveling I am not having to guess which timezone a particular entry was made. I also rather not record the particular timezone, making it more difficult to compare times.

**Comment by wren** [comment]
Hi, thanks for submitting an issue. A couple of questions: 

- Doesn't 8601 require a timezone included in the timestamp?
- Can't you change the time format in your config to match this format already?

Maybe I'm misunderstanding the issue, though.
