### ISSUE TITLE
Don't supply time when entering past entries.

### ISSUE THREAD

**Issue by gewthen** [jrnl-org/jrnl#534]
when I run `jrnl yesterday: I did something` I get `2018-04-15 09:00 I did something` in the journal. I would expect that because I did not supply a time, that a time would not be in the journal, yet it seemed to have arbitrarily pick 9:00, when it is completely wrong.

**Comment by stephanmax** [comment]
When you're not providing a time, jrnl falls back to `default_hour` and `default_minute` (which is `09:00`). You can configure that in a `~/.jrnl_config` configuration file (see also http://jrnl.sh/advanced.html).

**Comment by wren** [comment]
Yup! Timestamps have to have a time, so we fallback to whatever is in your config when one isn't provided.
