### ISSUE TITLE
Can't read first three bytes. after encrypting without keyring.

### ISSUE THREAD

**Issue by tsaber** [jrnl-org/jrnl#535]
Hey  I had been using the aurpackage jrnl for a while before  I read about the encryption. 

Now I didn't have a keyring installed,  so it prompted me to choose between getting a proper keyring and using their fill-in.

I chose for the former but the journal is now bricked it seems.

**Comment by wren** [comment]
Hi, can you please provide some more details about this? Can you provide a step-by-step way to recreate this problem? I'm not seeing it, but I might not be following what you're saying.
