### ISSUE TITLE
Enhancement Request: Support images

### ISSUE THREAD

**Issue by boringusername99** [jrnl-org/jrnl#536]
I realize this is almost anathema to the intent behind this command line project, but I find myself wanting to embed/attach pictures in my entries. I use jrnl for personal journaling, and I want to include one (or sometimes more) photos as a memory of a moment from the day.

I’ve discovered that writing markdown to reference images works OK so that exporting entries as markdown later and opening them in a markdown reader works fine. But, image organization starts to be a bit of a challenge over time.

A cleaner user experience would be to reference the image when writing the entry, and then jrnl would find the image, organize/index it, and then even display it if using a terminal that supports graphics.

Am I alone in wanting to hack in image support into this awesome project?

**Comment by insanerwayner** [comment]
My solution for this is to write all my entries in markdown. If I want to see it look pretty and with pictures I have a script to use pandoc to convert it to html with some nice CSS in a temporary file.

**Comment by wren** [comment]
I like this. I think we might be able to revisit if this is feasible or a road we want to head sometime  in the future. Adding this to the ideas bucket.
