### ISSUE TITLE
[Enhancement] Option to highlight dates

### ISSUE THREAD

**Issue by jontycg** [jrnl-org/jrnl#538]
Having the ability to highlight tags is fantastic. It would be amazing if there was also this ability for highlighting the timestamp at the start of an entry.

**Comment by stockphrase** [comment]
Here's a hack I worked out:
1. Make your journal file a markdown file.
2. Add a "#" to your timeformat, like this: `"timeformat": "# %Y/%m/%d %I:%M %p", `
3. Now your time stamp will stand out when you view the file later.

**Comment by jontycg** [comment]
Not a bad idea. Cheers!

**Comment by wren** [comment]
I'm putting this in the ideas bucket, since a little bit of formatting could be nice to add down the road.
