### ISSUE TITLE
Path with spaces in directory name

### ISSUE THREAD

**Issue by stockphrase** [jrnl-org/jrnl#539]
I'm trying to tell jrnl the path to a folder for storage of journal.txt. The folder has spaces in the name.

If I try to set up with this path:

    ~/Files/Office\ Briefcase/Notes/journal.txt  

Jrnl then makes a folder named "Office\ Briefcase" inside of the directory "Files".

I then just tried to use a blank space and it worked:

    ~/Files/Office Briefcase/Notes/journal.txt

This was a bit confusing.

**Comment by micahellison** [comment]
This is a non-issue in 2.0 since it uses YAML, which precludes the need for any escape characters.
