### ISSUE TITLE
Arrow Keys Print Control Characters

### ISSUE THREAD

**Issue by stockphrase** [jrnl-org/jrnl#540]
I can use arrow keys in my bash terminal, as expected. But when I enter jrnl, the arrow keys produce control characters rather than cursor movement. 

Is there some way to restore the use of the arrow keys while composing in terminal?

**Comment by stockphrase** [comment]
I just noticed that this only occurs when I call jrnl **without any arguments**. Only then do my arrow keys not function properly. If I begin an entry with arguments and compose on the prompt, however, the arrows work as expected.

**Comment by stockphrase** [comment]
Also noticing that the backspace key will work briefly, but then just freeze. Again, this only happens when I call jrnl without arguments and try to compose an entry. Otherwise if functions as expected.

**Comment by bAndie91** [comment]
this issue is not related to jrnl. when you "enter jrnl" it's your default text editor actually. check your VISUAL or EDITOR env var.

**Comment by micahellison** [comment]
jrnl's default composing interface isn't a full-fledge text editor, which is why these problems exist. Its workaround for these problems is to support a third-party editor. See the documentation about the "editor" section of the configuration file for more info: http://jrnl.sh/advanced.html

**Comment by mzfr** [comment]
@stockphrase This is not a problem with jrnl and @micahellison answer should be helpful.

@maebert 	We can close this issue.

**Comment by maebert** [comment]
@mzfr Agree, although I'd be open to improving jrnl's built-in editor's capabilities too.
