### ISSUE TITLE
Integration with RedNotebook?  Possible?  Would other people be interested?

### ISSUE THREAD

**Issue by mlncn** [jrnl-org/jrnl#541]
https://rednotebook.sourceforge.io/ stores journal data in plain text files, so it seems at least a possibility.

It's also written in Python, not that that should matter, but if jrnl could be a command-line interface to RedNotebook the maintainers may be open to supporting deeper integration than the ability to dump notes in that i'm initially looking for.

Thanks!

**Comment by wren** [comment]
Doesn't look like there's much interest in RedNotebook in particular, but I think we need to have a more wide-ranging discussion about integration(s), since Day One is also no longer working since they updated their client. Be on the lookout for that discussion!
