### ISSUE TITLE
Encryption is Vulnerable to Adaptive Chosen-Ciphertext Attacks

### ISSUE THREAD

**Issue by paragonie-scott** [jrnl-org/jrnl#549]
https://github.com/maebert/jrnl/blob/a2462ed7c36d8a4eed0bdf257703632abf21d441/jrnl/Journal.py#L43-L79

AES-CBC without HMAC (in Encrypt-then-MAC mode, with the MAC covering the IV and ciphertext, with a secure comparison mode; encryption is hard!) is vulnerable to [padding oracle attacks](https://robertheaton.com/2013/07/29/padding-oracle-attack/) which allows for decryption without access to the key.

Recommendation:
* Encryption: Calculate HMAC-SHA256 over `iv || ciphertext` (where `||` means concatenate), prepend or append it to the file
* Decryption: Recalculate the HMAC-SHA256 over the extracted IV and ciphertext, then compare it with the stored HMAC output, using [`hmac.compare_digest()`](https://docs.python.org/2/library/hmac.html)

**Comment by gautamk** [comment]
My understanding is that moving to an authenticated encryption mode could solve this issue ?
`AES GCM` ?

**Comment by paragonie-scott** [comment]
AES-GCM would work, provided you have a processor with the PCLMULQDQ instruction available to compute GHASH i constant-time.

Further reading: https://eprint.iacr.org/2013/157.pdf

AES-256-CBC + HMAC-SHA256 is secure even on older hardware, provided:

* The IV is generated from a secure RNG
  * IVs have to be unpredictable and unique, not just unique
* The HMAC is computed over the IV and ciphertext
  * Otherwise, you're giving attackers free control over the first 16 bytes of the plaintext
* The HMAC is compared in constant-time
  * Otherwise, you can use the time it takes for decryption to fail to produce a valid MAC for a chosen ciphertext, which reintroduces the padding oracle vulnerability we're trying to side-step

However, if you have a solid AES-GCM implementation available in Python, and you're fairly certain that your users have AES-NI and PCLMULQDQ available, that's definitely my recommendation.

**Comment by maebert** [comment]
Hey @paragonie-scott , thanks for pointing this out. We're changing the encryption method in 2.0, could you have a look at https://github.com/maebert/jrnl/blob/2.0-wm/jrnl/EncryptedJournal.py#L29 - I'd really appreciate your feedback on that!

**Comment by wren** [comment]
@paragonie-scott Hi! Thanks for pointing this out. The project is just getting back and up and running with new maintainers. It looks like the encryption method was changed since you filed this. Can you confirm that this is still an issue, or has it been resolved?

**Comment by paragonie-scott** [comment]
Wow, I somehow missed the email/notification on July 30!

Yes, moving to Fernet resolves this issue.

**Comment by wren** [comment]
@paragonie-scott Thanks for reporting back!
