### ISSUE TITLE
Terminal animation didn't stop after switch to another web page

### ISSUE THREAD

**Issue by chengluyu** [jrnl-org/jrnl#560]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2239547/46905115-9118eb80-cf21-11e8-94a7-8210303df0cb.png">

The terminal animation (see the screenshot above) at the index of jrnl.sh doesn't stop after you switch to another web page. Therefore when you go back to this page after a long time, it will go over quickly. Just like a time-lapse video. I also took a screen recording. You can watch the video at YouTube [here](https://youtu.be/l8tEJxScMII).

I have no idea how to fix because this is a bug about the documentation page but unrelated to documentation itself.

**Comment by maebert** [comment]
This would be something in https://github.com/maebert/jrnl/blob/master/docs/_themes/jrnl/static/js/landing.js -- noticed that a while ago, good catch though!

**Comment by mzfr** [comment]
Do we still have this issue @maebert?

**Comment by maebert** [comment]
Fixed in #611
