### ISSUE TITLE
Let temp file type be of same type as journal file

### ISSUE THREAD

**Issue by MaxMonteil** [jrnl-org/jrnl#566]
Hello!

I've been using jrnl for a few days now as I find it to be the cleanest and simplest cross platform journaling tool for me. Since I dual boot windows and linux its nice to have a shared file I could add to from either OS without having to reboot.

I have two journals currently, a default personal "journal.txt" and a dev journal "devnotes.md"
I edit and compose using vim but jrnl defaults to opening temp files in .txt thus losing the benefit of highlighting.

It would be nice if the temp file was of the same type as the journal.

I tried forking and offering a fix of my own but couldn't get it set up so here's what I would have tried:

In jrnl/util.py
```python
def get_text_from_editor(config, template=""):
    extension = "." + os.path.basename(config['journal']).split('.')[-1]
    filehandle, tmpfile = tempfile.mkstemp(prefix="jrnl", text=True, suffix=extension)
    ...
```

**Comment by stlewis** [comment]
I second this suggestion! In the meantime though, as a quick work around, when you're editing the `.txt` file, you can always issue `set ft=markdown` to get your syntax-highlighting, etc.

**Comment by MaxMonteil** [comment]
Oh! I had no idea about `set ft=markdown`.

Thanks for the tip

**Comment by zorab47** [comment]
For vim I use an autocmd to setup the markdown format for new entries based on the filename format:

```vim
augroup vimrc
  autocmd!

  " jrnl entries as markdown
  autocmd BufRead *jrnl*\.txt setlocal filetype=markdown sidescrolloff=0 spell complete+=kspell
augroup END
```
