### ISSUE TITLE
Feature Request: Parse new entries for timestamps

### ISSUE THREAD

**Issue by glvno** [jrnl-org/jrnl#568]
Hi! 

First of all, I love, love, love jrnl. 

This may be a kind of esoteric use case, but here goes: to maintain a distraction-free writing workflow, I use a standalone word processor (AlphaSmart Neo2) (there are dozens of us! dozens!) to compose entries, which I then import into jrnl at the end of the day. So jrnl opens Sublime, and I paste several manually timestamped entries from the AlphaSmart into Sublime:

> 2019-01-01 07:05 O'Hare.
>  I yelled at a cat
>
> 2019-01-01 08:30 Conrad's House.
> Then it hissed

then save and close.

The issue is that if I timestamp the first entry of the day, jrnl still automatically adds an additional, inaccurate timestamp immediately before it. Something like this:

> 2019-01-01 09:00 2019-01-01 07:05 O'Hare.
> I yelled at a cat
>
> 2019-01-01 08:30 Conrad's House.
> Then it hissed

 then when I save and close my entries end up out of order:

> 2019-01-01 08:30 Conrad's House.
> Then it hissed
>
> 2019-01-01 09:00 2019-01-01 07:05 O'Hare.
> I yelled at a cat

My workaround right now is to instead use `jrnl -1 --edit` instead of `jrnl` and then just paste the day's entries below the last entry from the day before, resulting in something along the lines of

```
MacBook-Pro:~ user$ jrnl -1 --edit
Password:
[-4 entries deleted, 4 entries modified]
```

But I (perhaps neurotically) am always worried that I might somehow screw up or accidentally delete the last of the previous day's entries, and would love not to have to use the workaround.

Hope this makes sense! If not, I'm happy to clarify.

Thanks again for this wonderful little application.

**Comment by insanerwayner** [comment]
I use an old Tandy WP-2 to do my entries and import them. I believe you have to do the top line formatted like this:
```
2019-01-01 08:30: Conrad's House.
Then it hissed
```
Notice the extra colon.

**Comment by mzfr** [comment]
@glvno 	Yes, you'll have to provide the `:` if you want your own custom timestamp. If you won't use `:` then that would be considered as a part of your entry and not as a timestamp.

If you have any other doubt then you can ask or else please close this issue :)

**Comment by glvno** [comment]
Whoops, forgot about this issue. Thanks for your help, everyone!
