### ISSUE TITLE
Filtering entries by tag doesn't work on Windows with default tagsymbol @

### ISSUE THREAD

**Issue by arisAlexis** [jrnl-org/jrnl#576]
according to the website documentation `jrnl @mytag` will display all entries of this tag.

On windows 10 this prompts for a new entry.

**Comment by x61x62x6d** [comment]
Had this issue as well. Works with different tagsymbol set in .jrnl_config, e.g. "+" instead of "@". You can try this as a workaround @arisAlexis

**Comment by mzfr** [comment]
@arisAlexis 	Were you able to fix this issue with the workaround?

**Comment by micahellison** [comment]
I can't reproduce this issue on Windows 10. I suspect that some of the changes to argument handling in the last six months have resolved this issue.

```
C:\dev\jrnl>jrnl @newtag


C:\dev\jrnl>jrnl @newtag this is an entry
[Entry added to default journal]

C:\dev\jrnl>jrnl @newtag
2020-05-30 11:03:31 @newtag this is an entry
```
