### ISSUE TITLE
multiple journal files across user accounts on macOS

### ISSUE THREAD

**Issue by tjfwalker** [jrnl-org/jrnl#577]
On my mac, I've two accounts that I use; they're for different purposes. I thought, *when in one, it'd be convenient to create `jrnl` entries in the other, without switching logins*. So, I made `/Users/accountA/.jrnl_config` to be like
```
{
    "journals": {
        "default": "/Users/accountA/journal.txt",
        "other": "/Users/accountB/journal.txt"
    },
    ...
}
```
and vise versa.

However, running `jrnl other [ENTER]` first prompted for a password —I tried the passwords of both accounts— then printed an error message, like so
```
Password:
ERROR: Your journal file seems to be corrupted. You do have a backup, don't you?
```

I went and made sure that `accountA` had `Read & Write` access to `/Users/accountB/journal.txt` then retried: same result.

So, now I'm just doing `su accountB` then `jrnl [ENTER]` but the first thing I tried seems like it ought to work and I prefer it.

Any thoughts?

**Comment by maebert** [comment]
Is it possible that your home folders are encrypted? When logged in as `accountA`, can you do `head /Users/accountB/journal.txt` and check that it's the same as when logged in into `accountB`?
