### ISSUE TITLE
Feature request: Comments

### ISSUE THREAD

**Issue by Fandekasp** [jrnl-org/jrnl#578]
Hi,

I would like to see comments when jrnl opens vim to write a journal, without having this comments displayed when querying jrnl for previous results.

At the moment, I use templates, and need to delete the comments manually everytime I write an entry.

```
2019-03-08 10:00  Entry title

My message visible when queried with `jrnl -from today`

// Seneca Meditation  (comment not visible except in `jrnl -from today --edit` )
// * Find a quiet place and close eyes to see events that took place during the day
// * Recall in detail everything from the time you got up this morning
// * At each scene & turn of event, remember how you performed as a Stoic
// * Remember everyone you met, everything you said and did - or failed to do, when your conduct was worthy and noble.
// * Consider every situation where you fell short.
```

The comment keyword could be `//`, or whatever else, I do not mind :)
Thank you for considering it
Cordially

**Comment by mzfr** [comment]
@Fandekasp 	I can look into this issue. Can you please tell me what do you mean by templates? Also how you use them for writing with jrnl.

**Comment by gregorybodnar** [comment]
Could this be handled within the editor just before sending the text back to jrnl?

If this is specific to Vim, the BufWrite event could be handled with a deletion of commented lines.

Another approach might be to set your editor to a script that invokes your actual editor and strips comments from the output before completing.

**Comment by Fandekasp** [comment]
Indeed, @gregorybodnar's suggestion makes sense. Looks like something I can get done with vim only.

I suppose I asked the question because jrnl already auto-prefixes the timestamp to the message, so it would make sense if it did a bit more like removing comments. If it's better for jrnl to not get too involved in messages post-processing, I can eventually write a small vim plugin for it.

@mzfr thanks for looking into it. It would be much more accessible if the feature was editor-agnostic.
Here's what I mean by template:

```sh
#!/bin/bash

# Randomly choose a question
day_question=$(grep -v - ~/Projects/personal/fandekasp_journal/stoic_template.txt \
    | shuf -n 1 \
    | fold -sw 80 \
    |  awk '{print "*"$0"*"}')

add_entry="jrnl \"$(echo "stoic\n$day_question")\" && jrnl -1 --edit"

if [[ -z $(jrnl -from today) ]]; then
    /usr/bin/termite --class=jrnl -e "/bin/zsh -c '$add_entry'"
fi
```

**Comment by wren** [comment]
I don't immediately see the usefulness of this feature, but I'm open to discussing it.

If you're looking back on your journal, won't it be useful to see the comments? I don't get why you want to have them there, but not displayed. 

Also, we currently don't do much processing of entries to display them, and I fear that adding comment syntax is heading down a dark road that could introduce some weird complications with people's existing journals.
