### ISSUE TITLE
"editor" command not working properly with spaces within an argument

### ISSUE THREAD

**Issue by IcaroBritto** [jrnl-org/jrnl#581]
I'm having a problem with the "editor" entry on the .jrnl_config file.
Basically what I am trying to do is start vim with the filetype defined to markdown.
The editor entry is like this:
```
{
...
   "editor": "nvim -c 'setlocal filetype=markdown'",
...
}
```
This command works fine on terminal, but this is not working on jrnl.
The problems are:
- The filetype is not set (it is empty);
- An error is shown when nvim opens like if the ' is being interpreted as a marker command.
- The jrnl temp file is not set in nvim.

I've tried double quotes (`"editor": "nvim -c \"setlocal filetype=markdown\""`) and escaping white spaces (`"editor": "nvim -c setlocal\\ filetype=markdown"`) but they didn't work either.

Can you help me with that?
Sorry for my English.

Nice piece of software by the way.

**Comment by maebert** [comment]
Internally, the commands to launch an editor are split on whitespaces and stored in an array, so `"nvim -c 'setlocal filetype=markdown'"` becomes `["nvim", "-c", "'setlocal", "filetype=markdown'"]`, causing the `'` to be misinterpreted. There's no super elegant way to fix that unfortunately, but you try to could store `'setlocal filetype=markdown'` in an environment variable and change it to something like `"nvim -c $SETMD"`

**Comment by IcaroBritto** [comment]
Hi,
Thank you for the reply.
I did just like you said, but it didn't work :/
I think the environment variables aro not being passed when the editor command is executed.
I'm not a Python developer, but I was looking into the code and, correct if I'm wrong, looks like that the process is called at the line [134 of the util.py](https://github.com/maebert/jrnl/blob/d402155878dca6901156488a96babaa84555d5a5/jrnl/util.py#L134).
Maybe if the code was like this we could use environment variables:
```
...
env_copy = os.environ
subprocess.call(config['editor'].split() + [tmpfile], env=env_copy)
...
```

Again, I'm not a Python developer, so I'm totally not sure.
Thanks again!

**Comment by wren** [comment]
I've had similar issues. There's a [PR that aims to address this bug](https://github.com/jrnl-org/jrnl/pull/435), but I haven't gotten a chance to test it out.

**Comment by gregorybodnar** [comment]
Let's keep this open. I might be able to test the PR with some contrived invocations. I'll try for the weekend.

**Comment by gregorybodnar** [comment]
I built up a test with #435 cherry-picked onto 2.0-rc3 and using this in my config:

```
  editor_test:
    editor: vim -c 'r! date' -f
    journal: /home/greg/editortest.journal
```

The PR preserves the quotes that are being passed, so it looks like this issue would be resolved. I don't have a Windows system to try with, so I'm just going to have to trust the Python docs for that case.

**Comment by wren** [comment]
Yup, I agree that the PR looks pretty good. I want to give the original author a chance to update themselves. If they don't, though, we can look at our options. I'm not sure we can just cherry-pick their commit when we factor in licensing and stuff like that, but I'm sure we can make a PR with similar functionality (and more tests, anyway). Anyway, we can cross that bridge when we get to it.

**Comment by wren** [comment]
I think subprocess is the right way to go, but passing `shell=True` is just too dangerous of an approach when the config file isn't secured. We'd basically just be executing arbitrary commands on a user's machine. Which we sort of already are, but that feels much worse.

Other than that, though. The oringinal PR looks good.

**Comment by wren** [comment]
@gregorybodnar Looks like that PR staled out. Do you still have a chance to submit an updated PR?

**Comment by gregorybodnar** [comment]
I have a long weekend just about to start, so I'll get it going.

**Comment by wren** [comment]
So, here's a thing.

On a mac: 
```
$ python -c 'import sys; print(sys.platform)'
darwin
```

And this is our editor code: 
`subprocess.call(shlex.split(config['editor'], posix="win" not in sys.platform) + [tmpfile])`

`posix="win" not in sys.platform`

`"win"`

dar**win**

😂

**Comment by wren** [comment]
Fixing the above (change to `win32` fixes all issues related to editor config values for me). I'm drafting a PR with this fix plus a few tests.
