### ISSUE TITLE
Mark stars with old journals?

### ISSUE THREAD

**Issue by leoaivy** [jrnl-org/jrnl#582]
I love features of journal very much. And there is a feature called starred journal, which is very cool. However, how could I mark stars on old journal? I tried inserting asteriks to old journal in editor (following rules there is no space around asteriks already) but when I type: "jrnl -starred", nothing is showed up.

**Comment by wren** [comment]
Hi, this seems to work for me when I do this:

```bash
$ jrnl foo
[Entry added to default journal]

$ jrnl -starred
# no output

$ jrnl --edit
# change entry from
# [Sat, 20 Apr 2019 11:34 AM] foo
# to
# [Sat, 20 Apr 2019 11:34 AM] foo*
[1 entries modified]

$ jrnl -starred
Sat, 20 Apr 2019 11:34 AM foo
```

If this isn't working for you, can you please provide some more info?

- Which version of jrnl are you using?
- Which editor are you using?
- Which OS are you using?
- Please paste your input and the line you are editing exactly, so we can see what you are doing.

Thank you!
