### ISSUE TITLE
Closing Text editor before composing leads to dump of entire journal contents in terminal.

### ISSUE THREAD

**Issue by stockphrase** [jrnl-org/jrnl#589]
I use jrnl with gedit under Ubuntu. 

When I call jrnl in my terminal, I get a blank document in gedit, as expected. If I compose something, and then close the window, I get the expected message that `[Entry added to default journal].`

However, if I don't put any characters into the gedit editor and just close it, the *entirety* of my existing journal gets printed *in my terminal*.

Odd. Is that supposed to happen?

**Comment by wren** [comment]
Unfortunately, yes. I'm personally not a fan of this behavior, though, and hope to take a closer look at it in the future. It's going to require going through to make sure a fix doesn't conflict with any other behavior, though. 

Thanks for the report!

**Comment by mzfr** [comment]
@wren 	 I think we can fix this issue just by adding `sys.exit(1)` in [get_text_from_editor#L175](https://github.com/jrnl-org/jrnl/blob/master/jrnl/util.py#L175).

In my opinion, when data is not saved we get the `prompt` saying `[Nothing saved to file]` but then it continues to return the `raw` and other processing continues which is causing the output of all the content of the existing journal.

**Comment by wren** [comment]
@mzfr That sounds like it could work. I would just want to make sure it doesn't interfere with any other functionality.

**Comment by mzfr** [comment]
If we type `jrnl` it should just open the text editor and if someone closes the file without saving anything then it should just close `jrnl` and nothing else has to be done.

If that is the functionality you are talking about then using sys.exit() won't cause any problems.

I haven't tested other functionality like export or reading.

**Comment by alichtman** [comment]
@notbalanced Will you open a PR with your change?
