### ISSUE TITLE
jrnl 1.9.8 erases default journal after editing timeformat setting

### ISSUE THREAD

**Issue by artgromov** [jrnl-org/jrnl#593]
1. edit timeformat setting
2. $ jrnl test entry
3. check that your journal file is empty

Luckily for me, I keep my journlal in the cloud and I was able to recover data.

**Comment by wren** [comment]
Hi, thanks for reporting the bug! This seems like a duplicate issue of #488.

It's already fixed in v2. Do you have a chance to update? It's not as easy as installing 1.9.8 at the moment, but you can do it with `pip`, if you're comfortable using it.
