### ISSUE TITLE
Failed export test - name 'len' is not defined

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#594]
Running the tests with behave on the 2.0-rc1 branch and found this test failing:
```
  Scenario: Exporting using custom templates  # features/exporting.feature:30
    Given we use the config "basic.yaml"      # features/steps/core.py:66
    Given we load template "sample.template"  # features/steps/core.py:100
    When we run "jrnl --export sample"        # features/steps/core.py:90
```

You can easily reproduce this by running:
```
jrnl --export sample
```
Which leads the output:
```
NameError
   "-" * len(entry.title)
          ^^^
name 'len' is not defined
```

It looks like it has something to do with the TemplateExporter class and code in template.py that is consuming code from /templates/sample.template - a line of hyphens that's supposed to be the same length as the title.

**Comment by wren** [comment]
I can confirm on my system that this test was failing before, and this PR fixes it.
