### ISSUE TITLE
cryptography is pinned to version 1.4

### ISSUE THREAD

**Issue by gregorybodnar** [jrnl-org/jrnl#610]
I was unable to build and install cryptography==1.4 using libssl-dev 1.1.1 to compile it. I was able to work around this by relaxing the version requirement by specifying cryptography>=1.4, which is using cryptography==2.7.

Is there a reason to use an older version of cryptography? I was able to read and write encrypted journals with 2.7 without issues (so far).

**Comment by wren** [comment]
Thanks for the report! There's no reason that I'm aware of to use the old version other than that's what the project was already using. We are planning to go through to update the dependencies soon, but that'll require more work to determine any conflicts. If this is just flatly failing like this, though, we'll have to get this particular one updated sooner.

We don't have the issue templates up, yet (coming soon), but can you please reply with your a few more details so we can keep an eye on similar reports?

What is your: 
- OS version
- Python version

**Comment by gregorybodnar** [comment]
OS: Linux Mint 19.1
Python: 3.6.8

**Comment by maebert** [comment]
Fixed in #612
