### ISSUE TITLE
2.0-rc2: ValueError in strftime()

### ISSUE THREAD

**Issue by zorab47** [jrnl-org/jrnl#614]
Likely a duplicate of #443. I'm using the 2.0-rc2 version of jrnl.

I'm seeing the following error on upgrade of my jrnl file and now on subsequent calls to `jrnl --edit`.

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl', 'console_scripts', 'jrnl')()
  File "/Users/charles/Code/zorab47/jrnl/jrnl/cli.py", line 276, in run
    edited = util.get_text_from_editor(config, journal.editable_str())
  File "/Users/charles/Code/zorab47/jrnl/jrnl/Journal.py", line 227, in editable_str
    return "\n".join([e.__unicode__() for e in self.entries])
  File "/Users/charles/Code/zorab47/jrnl/jrnl/Entry.py", line 63, in __unicode__
    date_str = self.date.strftime(self.journal.config['timeformat'])
ValueError: year=1 is before 1900; the datetime strftime() methods require year >= 1900
```

Editing a file that contains a line with `[1]` is causing the error. Attached is [a file that illustrates](https://github.com/jrnl-org/jrnl/files/3367975/jrnl_test.txt) the error with the contents:

    [2019-07-08 05:42] Entry with parse error
    ```
    [1] pry(main)> puts "Hello, Ruby!"
    Hello, Ruby!
    => nil
    ```
    
    [2019-07-08 05:42] Markdown link works without error
    A markdown sentence with link [elsewhere][1].
    
    [1]: http://example.com

**Comment by zorab47** [comment]
Updating the [regex parsing entries](https://github.com/jrnl-org/jrnl/blob/v2.0-rc2/jrnl/Journal.py#L104) to require an empty line before the time helps. See an [example here](https://pythex.org/?regex=(%3F%3A%5CA%7C(%5Cn%7C%5Cn%5Cr%3F)%7B2%2C%7D)%5C%5B(%5B%5E%5C%5D%5D%2B)%5C%5D%20&test_string=%5B2019-07-08%2005%3A42%5D%20Entry%20with%20parse%20error%0A%60%60%60%0A%5B1%5D%20pry(main)%3E%20puts%20%22Hello%2C%20Ruby!%22%0AHello%2C%20Ruby!%0A%3D%3E%20nil%0A%60%60%60%0A%0A%5B2019-07-08%2005%3A42%5D%20Markdown%20link%20works%20without%20error%0AA%20markdown%20sentence%20with%20link%20%5Belsewhere%5D%5B1%5D.%0A%0A%5B1%5D%3A%20http%3A%2F%2Fexample.com&ignorecase=0&multiline=0&dotall=0&verbose=0) of `(?:\A|(\n|\n\r?){2,})\[([^\]]+)\] `.

While this helps with the single example, it doesn't cover other cases. Perhaps the regex should include the specific date format somehow?

**Comment by wren** [comment]
Ah, yes, this makes sense. I suspect that the fix for some old issues (like #488) probably caused this. There's probably some better error handling we can put in around parsing lines that start with `[`.

**Comment by wren** [comment]
Also, I closed the other bug in favor of this one, because there's more info here for testing.

**Comment by wren** [comment]
Crashing on migration of an old journal to v2.0 while using common markdown syntax seems like a critical bug to me, so we'll get this into v2.0.

**Comment by micahellison** [comment]
Hi @zorab47, I think this is fixed, but I'd like to know that this is also works in the context of your journal being converted. Can you confirm? Thanks.

**Comment by zorab47** [comment]
Yep, it is fixed for my use of markdown. 👍
