### ISSUE TITLE
2.0.0rc3.post2 now interprets chat logs with bracket timestamps as new diary entries

### ISSUE THREAD

**Issue by sorsasampo** [jrnl-org/jrnl#625]
After 2.0.0rc3.post2 converted my journal, adding first entry seems to cause it to read the converted journal, and reinterpret chat log lines like this:

    [26/11, 23:32] Someone: chat line.

... as new entries, and move them to the end of the journal as new entries for "2019-07-21 23:32".

I understand the timestamp format has changed, but:

1) The parsing seems to be a little bit too greedy.
2) The journal conversion should escape this, if necessary.

**Comment by wren** [comment]
Hi, thanks for the report! Is this the first version of v2.0 that you've used? And to be clear, this is a journal that you converted from v1.9.8, right?

**Comment by sorsasampo** [comment]
@wren, yes to first v2.0 version. Not sure about the earlier v1.9.x version, but probably the latest.

**Comment by wren** [comment]
This should now be fixed with the latest in master. New release candidate coming soon.

**Comment by sorsasampo** [comment]
jrnl 2.0.0-rc4 still has this issue.

**Comment by wren** [comment]
@sorsasampo Can you please provide an example of a v1.9.* journal entry with square brackets that doesn't get upgraded properly to v2.0? We added tests to deal with the problem reported in this issue (using [this example journal](https://github.com/jrnl-org/jrnl/blob/master/features/data/journals/simple_jrnl-1-9-5.journal)), and every manual test I've done seems to work as expected now.

**Comment by sorsasampo** [comment]
@wren

```
$ cat journal.txt
2010-06-10 15:00 A life without chocolate is like a bad analogy.

[26/11, 23:32] Someone: chat line.
$ jrnl test
[Entry added to default journal]
$ cat journal.txt
[2019-08-27 12:00] test

[2019-08-27 23:32] Someone: chat line.
```

Not sure what happens to the first line in this case.

**Comment by sorsasampo** [comment]
@wren: the above was just me replacing journal.txt and running jrnl 2.0.0-rc4. Does jrnl store some indication of the journal version outside the journal file?

The actual issues I'm seeing happened when running jrnl 1.9.*, then 2.0.0rc3.post2 (which I guess did the journal upgrade), and then 2.0.0-rc4.

I reverted the erroneous changes done by 2.0.0rc3.post2 and when running 2.0.0-rc4, they are done again. Going back to pre-2.0.0rc3.post2 journal version is not an easy option, because I've been using jrnl for adding new entries between the release candidates.

**Comment by wren** [comment]
@sorsasampo Starting in v2.0, we've switched to a yaml config file (instead of json). The presence of the new yaml config is what triggers or skips the migration from v1. So, since you already ran an earlier release candidate, you likely already have gone through the migration process. If you delete the yaml config, jrnl will see the old json config, and retry the migration. 

As always, be sure to backup all your journals and config files before trying this.
