### ISSUE TITLE
Add live post-upgrade tests

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#632]
We've seen a handful of issues from testers (thank you!) when upgrading journals from 1.x.x to 2.0. I think we can handle all the issues that have been reported, but I'm still worried about but issues we can't anticipate. Working with completely arbitrary and unescaped plain text that has to be divided into records isn't easy, after all.

One way to deal with this would be to add some post-upgrade tests, and warn the user (or just print an error and crash!) if any of the tests fail.

This is the main test that comes to mind for me: If we dump the imported entries to text, then parse that text as if it's the new journal, do we end up with the same number of entries?

Feel free to comment with other ideas.

**Comment by MinchinWeb** [comment]
I think a 'count entries' test is a good basic test.

Do we make a backup of the jrnl file before upgrading?

**Comment by wren** [comment]
I agree that count is mostly good enough for this migration. Maybe we can also check that the dates line up, in order to catch if any of the dates were changed or anything like that.

For the backup file, I think warning the user to backup their journal before upgrading should be good for this. I don't want to take the burden of backing up a user's journal for them without adding way more checks and balances.

**Comment by micahellison** [comment]
So, it turns out that jrnl DOES make a backup when upgrading! It saves the old journal in the same file path with a .backup extension. It might be worthwhile for the console to let the user know when this happens, though.

As for tests, I agree that it should check the dates. That would rule out situations where the upgrade process would mangle the old dates.

**Comment by micahellison** [comment]
With help from @wren I made a pull request (#650) for this and was able to test that every entry is exactly the same after upgrading (title, body, date, etc.). It will abort the upgrade if there are any differences.
