### ISSUE TITLE
How to re-enable keyring after `--disable` ing it.

### ISSUE THREAD

**Issue by thanateros** [jrnl-org/jrnl#638]
When trying to get past encryption issues I was having, I `keyring --disable` 'ed the keyring.  

Now that my encryption issue is gone I am asked every time I make an entry to enter the encryption key.

I'm not proficient at Python and Google didn't help me, nor looking through the issues here: how do I re-enable the keyring from the command-line? `keyring --help` only tells how to disable it, now how to re-enable it.

**Comment by gregorybodnar** [comment]
I just had a quick glance at the [keyring project](https://github.com/jaraco/keyring/), and `--disable` looks like it sets the default keyring to a null keyring. I think what you want to do is set your default to a real keyring. I don't know how to do that with the command-line tool, but it's pretty easy from the seahorse GUI (usually available as "Passwords and Keys"). There should be an entry under Passwords. Right-click and set as default.

**Comment by thanateros** [comment]
Thanks for the advice @gregorybodnar ; In the next few days I'll implement your suggestion and post back here my findings/solution in case others have this issue, then I'll close it.  

Not really a jrnl issue; however I figured other python n00bs might run into this issue when using jrnl and this issue log would be a good place to aggregate such helpful side-issues related to using jrnl.

**Comment by wren** [comment]
@thanateros Did this work out? If it did, we can start aggregating these related issues into a Frequently Asked Questions section in the documentation.
