### ISSUE TITLE
No handlers could be found for logger "keyring.backend"

### ISSUE THREAD

**Issue by sidtechnical** [jrnl-org/jrnl#642]
This is possibly closely related to [issue #483 ](https://github.com/jrnl-org/jrnl/issues/483). Unfortunately, I could not run jrnl from a virtual environment. So, my quick fix was to copy `/.local/bin/jrnl` to `/usr/local/bin/`.

Now that I have resolved jrnl command not found error, I was able to add a jrnl entry, at least for the first time. Thereafter, any jrnl commands (irrespective of the flag) is giving me the `No handlers could be found for logger "keyring.backend"`error. 

I am using Ubuntu 18.04 LTS,  pip 9.0.1, and Python 2.7.15+.

**Comment by wren** [comment]
Hi, thanks for the report! Can you please specify which version of jrnl you have installed? If it's 1.9.8, can you please try with with the latest v2.0 release candidate and see if you have the same problem? Thank you!
