### ISSUE TITLE
Version 2 RC 4 released

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#651]
The latest release candidate (rc4) is now available via the following command:

`pip install jrnl==2.0.0rc4`

This resolves a variety of upgrade issues, while also adding rigorous tests to the upgrade process so unanticipated issues will cause it to fail instead of continuing as normal.

Please let us know if you run into any upgrade problems. If we don't see any major issues in the next two weeks, we'll plan on releasing this as the official v2.0 release.

**Comment by sorsasampo** [comment]
jrnl 2.0.0-rc4 still suffers from #625, please reopen that issue.

**Comment by wren** [comment]
Shipping this today! 🚢
