### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by dvyrthu** [jrnl-org/jrnl#652]
Hey! I just discovered jrnl though [a comment](https://news.ycombinator.com/item?id=20850756) in [this HN post](https://news.ycombinator.com/item?id=20849148). It looks super lightweight and like a great option for journaling, and the recent resurgence in maintenance is awesome. My only issue is that I can't seem to see a way to edit my encrypted journals via my android device. AFAICT, DayOne no longer works and I can't seem to find any other apps that are okay with the decrypting of the journal file. 

Are there any known journaling apps or text editors that work well with jrnl? Thank you!

**Comment by Jeinzi** [comment]
If you are really desperate like me, you could do the following:
- Install termux
- Install jrnl
- For sync, save the jrnl file offline via the Dropbox app and point jrnl to the cache
- Use some command line text editor like nano to edit your journal

For reference, the path to my jrnl file within the Dropbox cache is
```
/data/data/com.termux/files/home/storage/shared/Android/data/com.dropbox.android/files/u92375859/scratch/journal
```
But is suspect it might be slightly different on each device, especially that random number within the path.

**Comment by wren** [comment]
This is a very good question. I have to admit that I hadn't considered the possibility that anyone was using jrnl on mobile. I don't know of any setups that currently work, but I suspect that you should be able to make work any terminal app (as long you find a reliable way to sync to your phone). If anyone knows of good setups, please post them here.

We also have a milestone to rethink/rework the schema we use for jrnl, and have that time reserved to see how much work it would be to implement and maintain various third party integrations in jrnl (e.g. Day One, Red Notebook, etc). I think it would make sense to talk about mobile integrations at that time, too. If anyone has any ideas or recommendations, please post them in this thread.

**Comment by pablosproject** [comment]
I was thinking about a dedicated mobile app that can read jrnl log files and permit the user to add/display entries.
I personally used DayOne for such a long time and I moved to jrnl primarily because it uses open formats, but I like the geo-location and all the metadata DayOne gave me, so I think we could add that feature somehow.

That said, the idea is to save your jrnl file in:
- DropBox
- GDrive
- FTP
The app must be able to link with each service and locate the jrnl files (YNAB and other app follow the same approach using dropbox).
My 2 cents is that we do not need extra integration, but an open file format, that can be displayed  and accessed in mobile and also other ways (self hosted fronted apps, etc).

**Comment by dvyrthu** [comment]
I'm currently following @Jeinzi's suggestion and it's working "fine." The biggest offering that jrnl has over competitors is that it's file format is extremely easy to recreate and use. As things stand right now, you could totally use a normal mobile text editor to edit jrnl files but encryption/decryption and templates aren't options. Mobile app compatibility (maybe with StandardNotes?) is definitely the way to go, I just don't know how one would go about tackling the encryption / template issue.

**Comment by micahellison** [comment]
There's a lot of different ways to go about this! The solution could just involve adding various mobile platform-specific recipes in the documentation, or maybe something a bit more integrated.

**Comment by micahellison** [comment]
Closing this but keeping it in the ideas bucket.

**Comment by empireshades** [comment]
I store my journal file in Dropbox and use iOS shortcuts to append entries to it from the "Today view" screen. This is super handy for logging quick stuff like food journals. I also include automatic tagging based on the shortcut button that is pushed.

My dream would be to have a DayOne style app which can read/edit jrnl files. I sometimes use ByWord to modify it from mobile but at over 4400 lines, it's pretty unwieldy. My only concern with an app that manages a flat file is the possibility of corruption but with Dropbox's 'snapshots', the risk is somewhat less.
