### ISSUE TITLE
Can't find config?

### ISSUE THREAD

**Issue by lenusmars** [jrnl-org/jrnl#656]
I installed v2 rc4 in the hope that it would help sort out my problem with the editor command.  I think it's a permissions issue, though.  Sublime says that the file won't save because another process has it. 

I then tried to take Sublime out the editing slot, settling for manually driving to the journal file to edit it.  But it seems to have kept the configuration and I can't figure out where it's reading the config from.  I've killed the file in my home directory.  There is no config file in local/jrnl under my home directory.  I don't see one in the python base conda environment either, which is where the exe lives.

I've uninstalled and reinstalled but no new config file has appeared. 

I'm stumped on how it's retaining both the path to my journal file and the editor setting (Sublime Text.)  Can anyone enlighten me?

This is on Widows 10.  My standard Python is a conda env with Python 3.7.3

**Comment by micahellison** [comment]
Hi there, version two moves the configuration file using the XDG base directory standard but it doesn't do anything to your old config file, which is probably the source of this issue. After you upgrade, you can find the path of your new config file by running: `jrnl -ls`

**Comment by builtbyjordan** [comment]
I'm having trouble finding the config file as well. I'm running version 1.9.8.1 on macOS Mojave 
I've checked `~/.config/jrnl/jrnl.yaml` as well as `$XDG_CONFIG_HOME/jrnl/jrnl.yaml` nothing is there. I also ran a find jrnl.yaml on my machine. Nothing is coming up. somehow my config file settings are retained as I'm using an external editor iA Writer.
