### ISSUE TITLE
jrnl wont run after setup

### ISSUE THREAD

**Issue by majkaz** [jrnl-org/jrnl#661]
I have just installed the pypi version on win 10 using cygwin, and python3 installed as part of cygwin, not as standalone win app. 

The installation runs fine, the first initialisation is without any problems. The first entry in journal.txt is created.

On the next run however, following error message comes up:

```
Traceback (most recent call last):
  File "/usr/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python3.6/site-packages/jrnl/cli.py", line 146, in run
    config = install.load_or_install_jrnl()
  File "/usr/lib/python3.6/site-packages/jrnl/install.py", line 88, in load_or_install_jrnl
    config = util.load_config(config_path)
  File "/usr/lib/python3.6/site-packages/jrnl/util.py", line 144, in load_config
    return yaml.load(f, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

```

Is this a problem with the python version or it is something else?

**Comment by wren** [comment]
This is a problem with required modules. There's a PR for a fix of this (#660), that we'll test and put into a release soon.

**Comment by majkaz** [comment]
Thanks for the explanation. In my case, the solution was simply to update pyyaml.

**Comment by jrmoreau** [comment]
> Thanks for the explanation. In my case, the solution was simply to update pyyaml.

how did you do this?

**Comment by wren** [comment]
@jrmoreau `pip install --upgrade pyyaml` is the direct answer to your question. 

You shouldn't need to do this with the latest jrnl, though (this issue has been fixed for a while). What version are you running?
