### ISSUE TITLE
Directory export failing when there's no directory

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#669]
Steps to repro:
As per the documentation, I'm running:
```
jrnl --export json -o "my_entries\"
```
However, I get this error:
`[ERROR: my_entries" Invalid argument]`

When I created the directory, it worked just fine. However, "invalid argument" doesn't explain what the problem is.

Whatever the case, it's probably best to just automatically create the directory if it doesn't exist, rather than fixing the error message.

Using Windows 10, Python 3.7.4.

**Comment by peter-schmidbauer** [comment]
I think the problem here is the `\"`. You are escaping the quotes with that backslash. Does it work without the quotes?

**Comment by micahellison** [comment]
Yup, you called it! Thanks!
