### ISSUE TITLE
Idea: Create discourse community forum

### ISSUE THREAD

**Issue by metbril** [jrnl-org/jrnl#674]
A lot of open source projects host a community forum. Lately this is hosted with discourse

https://www.discourse.org/

This would be a way to move anything but bugs away from GitHub. So feature requests, user support, best practices, showcases, recipes etc. are then available at (for example) https://community.jrnl.sh/

Another way would be to publicly open the GitHub wiki for this.

**Comment by wren** [comment]
This is an interesting idea. I like Github in that it keeps everything in one place, but I have to admit that the level of discussion can sometimes clog up the backlog.

My main concern is that decisions will be made in a way that is much more difficult to search than the Github issues. Discourse does look pretty useable, though. 

@micahellison, what do you think?

**Comment by micahellison** [comment]
Sorry for missing this! I kind of like having everything in one place, and github issues are working particularly well for support, unless there's a barrier to using github that I'm not aware of. Maybe if the community gets bigger and someone wants to volunteer as a forum admin, it could be useful, though I'm not sure it's at quite the size needed for that.

**Comment by metbril** [comment]
GitHub might work well for issues (and/or feature requests) but having an active use community might increase product use, and lower the stress on the developers. User to user support becomes an option. I also useJoplin and Bitwarden who support this model. 

For the record. I don't intend to become a forum admin but am always helping others and sharing knowledge.

**Comment by metbril** [comment]
don't close please

**Comment by wren** [comment]
I'm open to doing this, but would need some volunteers to take on the burden of managing the forum. Any takers?

**Comment by wren** [comment]
[Gitter](https://gitter.im/) seems like a lower-effort way to start something like this. Maybe something like that could work? What do you think @micahellison?

**Comment by metbril** [comment]
Just my 2 cents. Gitter is more developer focused. My intention was to create more of an end user (support) community.

**Comment by micahellison** [comment]
It would be great to have an end user support community. I'm happy with troubleshooting and answering questions here on Github but I understand how having a more user-oriented platform can reduce friction and help keep the conversation focused on users. Still, I agree that, wherever this ends up being, someone who isn't a maintainer should be the admin, and they'll probably have their own ideas about where best to host it.

Is anyone out there reading this and interested in starting a jrnl user group?
