### ISSUE TITLE
Editor in config not used

### ISSUE THREAD

**Issue by metbril** [jrnl-org/jrnl#675]
After migrating to 2.0.1, I tried launching the external editor with `jrnl --edit`.

It shows this error:

```console
FSPathMakeRef(/Applications/TextWrangler.app) failed with error -43.
```

I forgot that I currently use BBEdit, it's successor, so I changed my config `~/jrnl_config` to 

```json
{
  ...
  "editor": "open -a /Applications/BBEdit.app -Wn",
  ...
}
```

However, the same error message occurs. It looks like the new value for 'editor' is not being used.

Using MacOS 10.14.6, installed through `pip3 install jrnl`, converted config/journals

```console
$ jrnl --version
jrnl version v2.0.1
```

I have already tried restarting the terminal.

**Comment by metbril** [comment]
I more or less figured this out.

The old config is in `$HOME/.jrnl_config`. During the conversion a `.jrnl_config.backup` is created. So I figured the old file would still be used. Not so. 

The configuration file for v2.x is now stored in `$HOME/.config/jrnl/jrnl.yaml`. This needs to be added to the documentation with #666 and #672.

**Comment by metbril** [comment]
More or less a duplicate of #663

**Comment by wren** [comment]
Looks like you got it worked out. You can always see which config file is being used with `jrnl -ls`, too. We're in the process of updating the documentation, so you should see that soon. We also welcome PRs for documentation updates, if there's anything you would like to see sooner.
