### ISSUE TITLE
Additional safety checks before saving

### ISSUE THREAD

**Issue by BenKettlewell** [jrnl-org/jrnl#676]
I've lost a lot of work repeatedly to various bugs in the course of using jrnl. I absolutely love the program so I can't see myself living without it but it would be amazing if there could be a safety-check to warn users about possible data-loss. I don't think it'd be too hard.

Proposal
Whenever opening a journal for editing, create a second temporary file in the following format.

/tmp/\<journalname\>-\<jrnltmpfile-number\>-shahash.txt. 

In that file store the SHA hash of the journal text file before any changes are made. 

Before inserting the entry back into the journal, obtain a SHA hash of the journal again to ensure it hasn't changed since it was opened. Compare the values and if they are the same, update the entry. If it's different, warn the user there may be a conflict and save a copy of the open entry somewhere. Maybe backup the journal file too just in case. They can then fix the conflict by hand if necessary.

ex) I open an entry and it creates a file /tmp/jrnlDvt3j2.txt from the work journal. Create a second file called /tmp/jrnl-work-Dvt3j2-sha.txt with the SHA value of the Work journal file.

This would help prevent data loss from issues like #502 which still seem to have unaccounted for edge-cases.

**Comment by wren** [comment]
Hi, @BenKettlewell. Thanks for submitting an issue. I'm sorry you've lost data. We've been trying to make sure to address any possible data loss issues as quickly as we can. They are a very high priority for us. 

In order to properly evaluate if your proposal would solve any extant issues, can you please give us some details about problems you've observed? If possible, some steps to reproduce the issues would be fantastic.

**Comment by BenKettlewell** [comment]
Hi @wren ,

#502 is what hit me this time (which I think should be re-opened). I left a comment there with the few steps to reproduce (it's pretty straightforward - edit different entries of the same jrnl simultaneously) but I don't have any additional details to provide atm.

I would recommend changing this issue to an enhancement rather than a bug as the particular data-loss issues are documented elsewhere. If implemented, this recommendation would serve as the last line of defense against any edge cases or data loss bugs that either still exist or may arise in the future.

Thanks for taking up the mantle btw :) Really glad there are people who want to keep jrnl alive 👍

**Comment by wren** [comment]
@BenKettlewell I was never able to repro this. If you can provide some step-by-step repo instructions, we can look into opening this back up. Thanks, again, for the issue!
