### ISSUE TITLE
Getting error running on Ubuntu 19.04, OSError for missing file

### ISSUE THREAD

**Issue by neurodancer** [jrnl-org/jrnl#678]
Cannot run jrnl, fresh install on Ubuntu 19.04.

I can't tell for sure where this is coming from so here is a dump from my shell window on the first run, fresh install.

> ➜  ~ jrnl
> Traceback (most recent call last):
>   File "/home/shannon/.local/bin/jrnl", line 10, in <module>
>     sys.exit(run())
>   File "/home/shannon/.local/lib/python2.7/site-packages/jrnl/cli.py", line 202, in run
>     raw = util.get_text_from_editor(config, template)
>   File "/home/shannon/.local/lib/python2.7/site-packages/jrnl/util.py", line 171, in get_text_from_editor
>     subprocess.call(shlex.split(config['editor'], posix="win" not in sys.platform) + [tmpfile])
>   File "/usr/lib/python2.7/subprocess.py", line 172, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

```

**Comment by wren** [comment]
Hi, @neurodancer . Thanks for the issue. Can you please give us some info about the version you installed, and the installation method?

If you used `pip install jrnl`, then you should know that we no longer support Python 2. So, you should update to Python 3, and try your install again.
