### ISSUE TITLE
Journal double upgrade full data-loss

### ISSUE THREAD

**Issue by BenKettlewell** [jrnl-org/jrnl#680]
I have journal files in a shared location which I access from various virtual machines.

When I upgraded from v1 -> v2 it asked me to upgrade my journal entries to the new format which I did.

When I upgraded my other vm from v1 -> v2 it asked me to upgrade a second time and wouldn't let me skip it (since the journals were already in the new format). I said yes and it blew away all my jrnl entries. A while ago I decided to keep my journals backedup in a git repo for situations like this but luckily for others the upgrade creates .backup files as well.

I restored the files before their second-upgrade and everything is working as intended.

**Comment by BenKettlewell** [comment]
I should note I also updated the .jrnl_config by hand to v2, so there was no need for that to be upgraded either but that might have had something to do with the data-loss.

**Comment by micahellison** [comment]
Hello, I'm trying to figure out the specific steps to reproduce this issue. It sounds like each vm has its own configuration files, and one on of them, it couldn't find your hand-made config file, so it upgraded over the existing one. However, we've put in checks to prevent data loss during this upgrade process, and they crash the application before saving if anything doesn't line up between the old and new journals, and I don't yet see what is bypassing that in this case.

Would you be willing to share your config files?

**Comment by BenKettlewell** [comment]
I couldn't find an old copy of the .config before the upgrade but I did compare the configs for the different vms and got the following (repeated for each journal of course.

`/root/share` and `/home/username/share` are both symbolink links to a shared folder located at `/media/sf_VM_share/`

### Diff
```
<       "journal": "/home/myusername/share/journals/cli-journal.md",
---
>       "journal": "/root/share/Journals/cli-journal.md",
```
### config
```
{
  "default_hour": 9,
  "linewrap": 79,
  "encrypt": true,
  "default_minute": 0,
  "tagsymbols": "@",
  "editor": "vim",
  "timeformat": "%Y-%m-%d %H:%M",
  "highlight": true,
  "journals": {
    "default": {
      "journal": "/root/share/journals/cli-journal.md",
      "encrypt": false
    },
    "personal": {
      "journal": "/root/share/journals/personal-journal.md",
      "encrypt": false
    },
    "pen": {
      "journal": "/root/share/journals/pentest-journal.md",
      "encrypt": false
    },
    "code": {
      "journal": "/root/share/journals/code-journal.md",
      "encrypt": false
    }
  }
}
```
### Repro
The exact steps were:
1. upgrade jrnl on VM1 - say yes to upgrading journals (journals automatically backed-up)
2. Used jrnl on VM1
3. copy jrnl_config and update paths to VM2 replacing the old config
4. upgrade jrnl on VM2 - forced to say yes to upgrading journals (even though they're already in the upgraded format)
5. original journals erased and replaced with blank files
6. Restored journals with backups/git - I'm not sure if backups were created on first upgrade, second, or both. I didn't notice any dataloss because I restored from git, not from the .backup files.

Now that I look at the config I'm not sure why encrypt is set to true because I'm definitely dealing with plaintext files (in a .md format). Maybe the upgrade got confused because the extension wasn't .txt and therefore thought it was encrypted?

**Comment by wren** [comment]
Hi @BenKettlewell . The upgrade process should change your config file from json to yaml. Seeing the json format here makes me think that maybe you copied the wrong file. The new config file will be at `${XDG_CONFIG_HOME}/jrnl/` where `${XDG_CONFIG_HOME}` defaulted to `~/.config`. Can you check if you see a yaml file there?

**Comment by BenKettlewell** [comment]
Aha, found it. Sorry for disappearing, busy month.

```default_hour: 9
default_minute: 0
editor: vim
encrypt: true
highlight: true
indent_character: '|'
journals:
  code:
    encrypt: false
    journal: /home/user/share/journals/code-journal.md
  default:
    encrypt: false
    journal: /home/user/share/journals/cli-journal.md
  pen:
    encrypt: false
    journal: /home/user/share/journals/pentest-journal.md
  personal:
    encrypt: false
    journal: /home/user/share/journals/personal-journal.md
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.0.1
```

**Comment by wren** [comment]
So, to be clear, it sounds like the wrong config was copied when in step 3 above. If the correct config had been copied, the second upgrade never would have happened. Does that make sense?
