### ISSUE TITLE
Add better developer documentation

### ISSUE THREAD

**Issue by alichtman** [jrnl-org/jrnl#693]
After beginning to work on contributing to this project, it seemed to me that many aspects of the development process were undocumented, such as ways to test the project, build it, etc. Although I was able to figure these things out, it was both an inefficient use of time and may turn off some potential contributors.

The user docs are fantastic. The developer docs should be, too :)

Off the top of my head, the following should be documented:

- Running the source: `$ python3 -m jrnl`
- Running tests: `$ make test`
- Building and installing: `$ poetry build && pip3 install dist/*.whl`
- How to write new tests

**Comment by peter-schmidbauer** [comment]
I also have a question: Why is the version in pyproject.toml on master specified as "0.0.0-source"? I have never seen another project do this.

**Comment by wren** [comment]
@peter-schmidbauer That's a placeholder. We need to finish the updates to the pipeline that will update that to the correct version as we do each release.

**Comment by wren** [comment]
That being said, we should add a separate issue for that, so people know what's up.

**Comment by wren** [comment]
Issue I'm referencing is #715

**Comment by wren** [comment]
@alichtman Agreed. The developer side of things has been in flux with our current milestone (switching to Poetry, etc). But we're definitely planning on updating this soon. Thank you for filing the issue!
