### ISSUE TITLE
Prompts display b''

### ISSUE THREAD

**Issue by sloria** [jrnl-org/jrnl#700]
## **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## Regarding bug reports:

* **Please tell us about your environment:** 
  - Jrnl version: (run `jrnl -v`):  `jrnl version v2.0.1`
  - How you installed Jrnl: `pipx install jrnl`
	
  - Operating system [MacOS, Linux, Windows?]: macOS Catalina

* **What is the current behavior?**

Prompts display `b''`

* **Please provide the steps to reproduce and if possible a minimal demo of the problem** 

Open a password-encrypted journal

* **What is the expected behavior?**

Prompt displays without `b''`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://github.com/jrnl-org/jrnl/blob/53677a9df144ebb45bd7e8f0541a6abc38574c4d/jrnl/util.py#L121-L125

**Comment by peter-schmidbauer** [comment]
This only happens for the "Password: " prompt, right?

Because I'm pretty sure it's the only place that's using bytes, starting from commit 06e3f0c1. This apparently was needed in some old versions of Python on Windows but not anymore (see #393 for example). We can definitely change that back now.

**Comment by sloria** [comment]
"Password: " is the only one I saw--didn't look into other prompts.

**Comment by peter-schmidbauer** [comment]
This is fixed by #702
