### ISSUE TITLE
Remove Python 2 compatibility code.

### ISSUE THREAD

**Issue by sloria** [jrnl-org/jrnl#701]
## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

While poking around in the code, I noticed some Python 2-compatibility code in https://github.com/jrnl-org/jrnl/blob/master/jrnl/util.py . Now that jrnl only supports Python 3.7, this code can be removed. 

I also recommend running [pyupgrade](https://github.com/asottile/pyupgrade).

**Comment by peter-schmidbauer** [comment]
Yes, util needs some cleaning up. At the same time, the stdin/stdout mocking for the tests should imho be removed and replaced with `unittest.mock` in the tests, so that the production code is clean and not littered with test stuff.
