### ISSUE TITLE
How to remove password from macos keychain?

### ISSUE THREAD

**Issue by wilrnh** [jrnl-org/jrnl#711]
Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

## **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

Hi, how do I remove the password for my journal.txt from the MacOS keychain?

## Regarding bug reports:

* **Please tell us about your environment:** 
  - Jrnl version: (run `jrnl -v`)
  - How you installed Jrnl
	
  - Operating system [MacOS, Linux, Windows?]

* **What is the current behavior?**

* **Please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

## Regarding Feature requests: 

* **What is the motivation / use case for changing the behavior?**

* **Please provide examples of the usage**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by peter-schmidbauer** [comment]
Hi, does this help?

https://support.apple.com/guide/keychain-access/delete-a-keychain-kyca2423/mac

`jrnl --decrypt` doesn't seem to do this currently, but it probably should.

**Comment by wilrnh** [comment]
Thanks for you suggestion @pspeter but it seems jrnl does not store the password in a separate keychain. I guess if the keychain, and the location in the keychain, were known, I could delete the stored password myself, and maybe jrnl will get the hint?

**Comment by pspeter** [comment]
>  it seems jrnl does not store the password in a separate keychain

You mean it does not store it in the MacOS one? 
Could you please run `keyring --list-backends` in your terminal where you installed jrnl and copy paste the output here? 

As workaround, you could also try running `jrnl --decrypt` followed by `jrnl --encrypt`, and then selecting "n" when asked whether to store the password in the keychain. That should get rid of it, too.
