### ISSUE TITLE
Version should update in repo after each release

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#715]
## Bug report

* **What is the current behavior?**
The version in our config is `0.0.0-source`.

* **What is the expected behavior?**
The version in the project should match the current release number.

* **Other information**
The current version is a placeholder. We need to update the pipeline so that travis will update the config, and commit it to the repo so that the master branch always shows the correct version.

**Comment by wren** [comment]
> One thought on VERSION.txt vs __version__.py:
> ... it could be an attack vector for code injection... hard to spot...

I'm not very worried about this, because the tag is already going through two validations before it gets committed to the repo. The first validation is from `poetry version`, which will error out when given a string that isn't a valid version. If a bad version somehow gets through Poetry, the second validation is from pypi, which will abort the deployment if the version string doesn't follow [PEP 440](https://www.python.org/dev/peps/pep-0440/). If either of those fails, the build build will fail, and the commit will never happen. I think the string is pretty well vetted by the time it gets into a file, but we can either add another check (probably a regex before commit), or if you still feel that `version.txt` will be significantly more secure with the pipeline, then I'm open to it.

> On pkg_resouces

Suggestion
@wren, what about a workflow where we add a makefile command that both updates the version in pyproject.toml and a __version__.py (since it's now part of the source), and automatically creates a git tag? In the pipeline, we can test that those three versions are congruent too to avoid any accidental version changes.

**Comment by wren** [comment]
... Continued from #719 

> One thought on VERSION.txt vs __version__.py:
> ... it could be an attack vector for code injection... hard to spot...

I'm not very worried about this, because the tag is already going through two validations before it gets committed to the repo. The first validation is from `poetry version`, which will error out when given a string that isn't a valid version. If a bad version somehow gets through Poetry, the second validation is from PyPI, which will abort the deployment if the version string doesn't follow [PEP 440](https://www.python.org/dev/peps/pep-0440/). If either of those fails, the build will fail, and the commit to `__version__.py` will never happen. I personally think the string is pretty well vetted by the time it gets into the file, but we can either add another check (probably a regex before commit), or if you still feel that `version.txt` will be significantly more secure, then I'm open to it.

> On pkg_resouces
Yup, agreed that we need to simplify the workflow for devs, and storing the version in the repo is a part of that.

> what about a workflow where we add a makefile command that both updates the version in pyproject.toml and a __version__.py (since it's now part of the source)

I am fine with using a makefile in general, although I suspect that we have different use cases in mind. It sounds like you're suggesting that an individual dev would run the update script, but I want to make sure that the pipeline is the only place that these things are ever run.

The main thing I'm trying to avoid through this is having any part of the release and distribution pipeline become dependent on independent machines. We just recently finished making it completely independent, and I'm very resistant to going back.

As it stands, the process of how to release a new version of jrnl looks like this: 

1. Merge any relevant PRs to master (all code goes through PRs)
2. Go to https://github.com/jrnl-org/jrnl/releases/new
3. Enter version into tag field
4. Click "Publish Release"

That's it.

I--or anyone else with the correct access--can manage all release and distribution without ever even cloning the repo, and can do so from any web browser on any platform (Mac, Linux, Windows, and even a phone or tablet, if needed). This greatly reduces ramp-up time, management time, and system requirements for maintaining the project, and reduces friction for getting fixes out quickly. This is a huge boon not only to current maintainers, but to anyone that that might fill in for me on vacation, or take over the project in the future.

I'm open to all of the suggestions on how to provide the best experience for contributors (like making sure the tag and the version file align properly), and for users (like reducing the start-up time of jrnl), but any solutions have to keep in mind that the pipeline also stays as seamless as possible in order to ensure the long-term success of jrnl.

**Comment by maebert** [comment]
Heya, your comments on `__version__.py` vs `VERSION.txt` make complete sense - I updated #719 to reflect that.

Completely agree with all of your points regarding the release process. That said I see two issues with it:

1. Using `0.0.0-source` as the placeholder version in `pyproject.toml` is problematic because it causes Poetry to fail on certain commands; most severely as a developer you can't run `poetry install` to set up your dev environment. Changing it to any valid version (`0.0.1-source` would be fine) would fix that.
2. That said, having the version present in the development environment is helpful too, it's an easy way to know what you're working on.

Could we possibly use a Github action that gets triggered on new releases and writes an actual commit with the tag's name into `pyproject.toml` and `__version__.py` before creating the tag?

**Comment by wren** [comment]
Yup! Sounds like we're on the same page. `0.0.0-source` is long gone. It was a placeholder while I was working out how to put the functionality in the pipeline. The correct version is already [kept up to date in toml file](https://github.com/jrnl-org/jrnl/blob/master/pyproject.toml) with every release. There is still a small issue about the tag and the update to the toml file being one commit off, but we have an issue filed (#735), so we'll take care of that soon.

And since we already keep the toml file up to date, it shouldn't be much more work to keep the `__version__.py` file also up to date. I just wanted to get your PR sorted out before adding that functionality (since we hadn't settled on which file we were using).

Also, I'm fine using Github actions if needed, but prefer Travis if we can swing it so we keep all the CI/CD in one place.

**Comment by maebert** [comment]
Yup, 100% agree - I think we can close this issue (since it's technically solved), and we can include writing into `__version__.py` in the solution to #735?

**Comment by wren** [comment]
Fixed a while ago.
