### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by velasco** [jrnl-org/jrnl#716]
Hi,

I tried to install jrnl on my Raspi without success. The installation fails saying:
`distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p6tX8c/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Pwi2Fn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-p6tX8c/cryptography
Storing debug log for failure in /home/pi/.pip/pip.log
pi@pi:/bin $ `

Do you have an idea why?

**Comment by micahellison** [comment]
Hi, thanks for the report.

Could you please provide the following:

- jrnl version
- python version
- how did you install jrnl?

It's possible that this is the same issue as #647. If this is the case, then you may be able to bypass it by installing an older version of jrnl (v1.9.8) like so:

`pip install jrnl==1.9.8`

**Comment by velasco** [comment]
This helped. Thanks
