### ISSUE TITLE
Add tests for printing multiline journals

### ISSUE THREAD

**Issue by alichtman** [jrnl-org/jrnl#717]
This journal entry being successfully printed should be tested for. I caught a bug in one of my features manually that this test would have caught.

```
2019-11-07 02:42 Multiline jrnl
| Hello
| Some text
| 
| 
| More text
| Another
```

This should be tagged `enhancement`, not `bug`.

**Comment by wren** [comment]
Great suggestion! Looks like you're already working on it in your repo. Feel free to submit PR whenever you're ready. Thank you!

**Comment by alichtman** [comment]
It’s included in the PR for the colored output, which is already ready for
review.
