### ISSUE TITLE
request: highlighted date/time for reading journals

### ISSUE THREAD

**Issue by 1dancook** [jrnl-org/jrnl#720]
## Feature Request

When reading a journal, it would be great if the printed output would have highlighted dates/times. This would just help to distinguish entries visually.

**Comment by peter-schmidbauer** [comment]
This feature is currently being worked on in #692. You are welcome to leave feedback/review the code.

**Comment by alichtman** [comment]
Sort of duplicate of #508

**Comment by 1dancook** [comment]
Okay very nice. I took a little browse through the issue before and didn't notice this. Thanks guys! Will close this.
