### ISSUE TITLE
Automatically update changelog

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#724]
## Feature Request

* **What is the motivation / use case for changing the behavior?**
It would be nice to have the changelog update automatically with a list of related Github issues and their descriptions, rather than having to manually update the changelog with each release.

**Comment by ParaplegicRacehorse** [comment]
I would also like the changelog, or at least what has changed since last release, to appear under the release tag on the GH Releases page. Not sure how other projects do this. Is it a CI thing, I wonder?

**Comment by wren** [comment]
Yup! This is a big feature for me. I've been looking into changelog generators, but if anyone had any favorites, please post them here.
