### ISSUE TITLE
Create a diagnostic command line argument

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#727]
## Feature Request

* **What is the motivation / use case for changing the behavior?**
Rather than asking users to check their python version, jrnl version, operating system, etc., it would be nice to have a general diagnostic dump that outputs all these values. Maybe it could also output certain non-sensitive values from the configuration (e.g. time format).

* **Please provide examples of the usage**
Once finished, we can edit the issue template that was recently made for bugs, and ask users to run this command.

**Comment by minchinweb** [comment]
Should something be added to point people to the issue tracker to submit issues?

**Comment by wren** [comment]
@MinchinWeb The idea is that once a version with this command is released, we'll update the issue template to ask users to run this command, instead of asking the questions we are currently asking.

It's a good point, though, that we shouldn't close this issue quite yet.
