### ISSUE TITLE
Solution for defining individual prompts

### ISSUE THREAD

**Issue by karava** [jrnl-org/jrnl#732]
Hi, I noticed in the docs they had a nice solution for including prompts. The one below.
How do we implement/use this?

function log_question()
{
   echo $1
   read
   jrnl today: ${1}. $REPLY
}
log_question 'What did I achieve today?'
log_question 'What did I make progress with?'

**Comment by alichtman** [comment]
Add this to your `.zshrc` or `.bzshrc` file:

```bash
function log_question()
{
	echo $1
	read
	jrnl today: ${1}. $REPLY
}

function jrnl_questions() {
	log_question 'What did I achieve today?'
	log_question 'What did I make progress with?'
}
```

Then, run `source ~/.{bash/zsh}rc` and use it with `$ jrnl_questions`.

**Comment by karava** [comment]
Love your work.
Thank you Aaron, much appreciated!

Kind regards,
- Kishan

**Comment by alichtman** [comment]
No problem!

**Comment by alichtman** [comment]
@wren, @maebert This can be closed.
