### ISSUE TITLE
Version updates in code after tagged release

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#735]
## Bug report

**What is the current behavior?**

The current build process is:
* We tag a release in GitHub
* The tag triggers a Travis CI deployment
* Travis sets the version number in the code to match the tag
* Travis makes a commit with the new version number; however this commit is one commit AFTER the tag release

Downstream impact:
* If you grab the source for a particular release, your version number will be off by one release.

**What is the expected behavior?**
Ideally, the version number and release tags would be on the same commit.

Maybe Travis could simply move the tag to the latest commit as the final step of its deploy process.

**Comment by wren** [comment]
This was fixed by #947.
