### ISSUE TITLE
-on today lists all entries

### ISSUE THREAD

**Issue by sorsasampo** [jrnl-org/jrnl#741]
## Bug report

`jrnl -on today` lists all entries, instead of just the ones on today. I think it used to work fine in 1.x, but is now broken in v2.0.1.

Same thing with `jrnl -from today`.

Installed using `pip3 install --user jrnl==2.0.1` on Linux.

**Comment by wren** [comment]
Confirmed. That's really no good. We need to fix this and add better tests to catch this in the future.
