### ISSUE TITLE
Markdown-like Syntax highlighting (italics and bold)

### ISSUE THREAD

**Issue by alichtman** [jrnl-org/jrnl#746]
Would be cool if you could use a subset of markdown syntax in jrnl and have it nicely displayed when printed out. I'm thinking something along the lines of what `bat` does.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/20600565/69038486-31c1c080-09ea-11ea-82dd-bfda6f171576.png">

Once #692 is merged, this shouldn't be too hard to add into the colorization pipeline. Likely just a regex to extract words contained within a pair of `**` and also a pair of `_`. Arguably, we should also support `__` and `*`.

**Comment by wren** [comment]
I'm hesitant to add any sort of syntax parsing to jrnl. Tools like `bat` already do a much better job, and we can pipe output of jrnl to them already, and even export as markdown. 

Can you please talk about what you hope this feature would accomplish that something like `jrnl -5 --export markdown | bat` doesn't already do more reliably?

**Comment by alichtman** [comment]
TIL `jrnl -5 --export markdown | bat -l markdown`
