### ISSUE TITLE
Fail Travis CI if poetry lockfile is not up to date

### ISSUE THREAD

**Issue by alichtman** [jrnl-org/jrnl#747]
In Travis, the following warning is shown:

```bash
...
$ poetry version
$ poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
```

Should we throw a `$ poetry update` before `$ poetry install`? I could see this causing issues in the future.

**Comment by pspeter** [comment]
That's not really something travis should do but whoever changes the pyproject.toml file. 

Travis should probably just fail if the lock file is not up to date, imo.

**Comment by wren** [comment]
Hrmm, not sure how the lock file got out of sync. But I agree with @pspeter that it should be committed as part of changes to pyproject.toml. Let's use this issue to get a PR to fix the lock file.

**Comment by alichtman** [comment]
> Travis should probably just fail if the lock file is not up to date, imo.

Ah, yeah, agreed.

**Comment by micahellison** [comment]
We have a regular process now to keep packages up to date, and we don't want CI to fail when they aren't (so we can keep PRs flowing in), so I'm closing this.
