### ISSUE TITLE
Documentation: Advanced Usage names wrong configuration file

### ISSUE THREAD

**Issue by johannes87** [jrnl-org/jrnl#754]
https://jrnl.sh/advanced/ says "You can configure the way jrnl behaves in a configuration file. By default, this is ~/.jrnl_config.". 

With jrnl 2.1.post2, the configuration is stored in $HOME/.config/jrnl/jrnl.yaml

Operating system is macOS

**Comment by wren** [comment]
Confirmed.

**Comment by wren** [comment]
Fixed.
