### ISSUE TITLE
Travis attempts to deploy twice

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#757]
## Bug report

This is a bug in our deployment process on tag release builds.

Currently, Travis runs tests for Python 3.6 and Python 3.7 in parallel, which is good, except that once either build succeeds, Travis deploys the successful build. Then the other build fails, because it also tries to deploy, but can't overwrite the deployed pypi files.

You can see this in action [here](https://travis-ci.com/jrnl-org/jrnl/builds/138174160).

**Comment by wren** [comment]
Ah, yup. We need to separate the deploy into a separate stage. Here's a good example: https://alexgude.com/blog/python-pypi-and-travis-staging/
