### ISSUE TITLE
Secondary journal specification bug

### ISSUE THREAD

**Issue by paxperscientiam** [jrnl-org/jrnl#758]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: jrnl version 2.1.post2
  - How you installed Jrnl: pip
  - Operating system MacOS

* **What is the current behavior?**
Given a secondary journal "clients", `jrnl clients: testing` writes to default journal

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a secondary journal
2. Try to record notes into said journal

* **What is the expected behavior?**
Said note is recorded into the secondary journal (E.G. clients journal).

So, here is the issue as far as I can tell. Notes *are* written into the secondary journal when a time is specified. In fact, notes are written into secondary journal as long as any text follows the journal name.
examples:
`jrnl clients at 10am: testing`
`jrnl clients blah: testing`
`jrnl clients : testing`

While this "works", it means that the journal becomes polluted.

Also, what works is just omitting the colon altogether.
`jrnl clients Hi There testing again # no pollution`

So, either parsing logic involving colon delimiter needs to be adjusted or there needs to be a bright note indicating not to use a colon when recording "now" notes. I suggest the former.

Thanks a lot!

**Comment by pspeter** [comment]
`jrnl clients testing` without the colon should do what you expected. Otherwise jrnl thinks you are trying to insert a date, fails at parsing said date and just puts it into the title of the new entry instead.
Having a colon at the first position of the title is not supported.

**Comment by wren** [comment]
@paxperscientiam Thanks for the bug report!

Before you filed this issue, I would've said that the preferred way to enter into a journal from the command line without a time is to leave out the colon entirely. Looking at the documentation, though, I agree with you that that's unclear. Specifically, the docs show this example as being supported: `jrnl *: Best day of my life.` It follows that `jrnl clients *: Best day...` should work, and that `jrnl clients : Best day...` should work. And if those work (they do), then maybe `jrnl clients: Best day...` should work, too. 

The syntax technically isn't what we have allowed in the past (journal name followed immediately by a colon), but it is jrnl's intent to be loose with syntax (to a point) and allow people to enter journal entries with as natural language as possible. If the only difference between the two entries is a space before the colon, then maybe we should account for it (like we already account for not specifying a journal, and not specifying a date before a lone colon).

I have to think about this one a bit (and make sure that this wouldn't complicate the journal and date parsing too much), but I really appreciate the report.

**Comment by wren** [comment]
Keeping this one for now.
