### ISSUE TITLE
Docs site has no mobile menu

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#760]
## Bug report

* **Please tell us about your environment:**
  - Website: [jrnl.sh/overview](https://jrnl.sh/overview/) (or most of the site other than the homepage)

* **What is the current behavior?**
Any browser at 768px or narrower shows no menu. This leaves the user with no way to navigate the site (wider breakpoints show the sidebar for navigation).

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
Go to [jrnl.sh](https://jrnl.sh/) and click on the "Documentation" link on the homepage.

* **What is the expected behavior?**
There should be a mobile menu of some sort (probably showing the sidebar from larger breakpoints restyled for mobile).

**Comment by wren** [comment]
@maebert Do we have any metrics on usage of jrnl.sh? It'd be helpful to have access to see any info we have in order formalize a browser compatibility matrix.

**Comment by maebert** [comment]
Easy fix, but that reminds me that we should probably track some basic analytics.
