### ISSUE TITLE
Windows build stalling in Travis on empty entry test

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#766]
## Bug report

On our Travis Windows build, it's stalling on the "Writing an empty entry from the editor" test. See the example [here](https://travis-ci.com/jrnl-org/jrnl/jobs/261828925#L221).

I'm not running into this problem locally with the same code and Python version (3.7.5).

* **Please tell us about your environment:**
  - Jrnl version: n/a, develop branch
  - How you installed Jrnl: n/a
  - Operating system [MacOS, Linux, Windows?]: Windows 10

* **What is the current behavior?**
```
 Scenario: Writing an empty entry from the editor           # features/core.feature:23
    Given we use the config "editor.yaml"                    # features/steps/core.py:67
    When we open the editor and enter ""                     # features/steps/core.py:77
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

```

Whereas, locally, I run `poetry run behave` and all tests pass.

**Comment by MinchinWeb** [comment]
Note that Travis runs Windows tests from a Git Bash shell. Personally, I would love to run the tests directly from Powershell, and I wonder if that would fix this issue...

**Comment by wren** [comment]
I think it might have a powershell option.

**Comment by micahellison** [comment]
So... here's what we've tried.

Attempts to repro the failing Travis test failed on my Windows 10 machine:
* Running git-bash locally then `poetry run behave` - the test passed
* Running PowerShell then `poetry run behave` - the test passed

Attempted to run the tests using PowerShell in Travis, and it still stalled.

Since Travis gets held up when there's a blocking process call, I was wondering if the editor in the `editor.yaml` behind the test was stalling Travis. I changed the `editor` property from `"vim"` to `"vim +qa"` and confirmed that running `vim +qa` in my terminal quits vim immediately after running. But when I had Travis build with this change, it _still_ stalled on that test.

So there's a lot that has been ruled out... but I still don't know what exactly is causing the issue or how.

**Comment by MinchinWeb** [comment]
At this point do we open a ticket with Travis directly...?

**Comment by wren** [comment]
I did open a ticket with Travis and they said "Python language is not supported by Travis CI on macOS and Windows builds." so no help there. 😞

**Comment by wren** [comment]
I'm currently planning to skip any broken tests on Windows, and re-enabling them as we fix each one.

**Comment by micahellison** [comment]
Thanks for the fix! 🎉
