### ISSUE TITLE
Markdown export bug

### ISSUE THREAD

**Issue by pggoncalves** [jrnl-org/jrnl#768]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`) : 2.1.1
  - How you installed Jrnl : Using pip3 install jrnl
  - Operating system [MacOS, Linux, Windows?] : Windows

* **What is the current behavior?**
When you export markdown, a missing new line character between the end of the last entry and the date of the next entry. This cause some markdow intrepretor to not recognize title (#) as title.
 
* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
jrnl --export markdown -> next open using a markdown viewer like ghostwriter.

* **What is the expected behavior?**
was expected that there is a new line (/n) charater between end of last entry and date of next entry.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pggoncalves** [comment]
Hi,
I make some try and find a solution on markdown_expetrt.py
I add newline to the return string.
`     if warn_on_heading_level is True:
            print(f"{WARNING_COLOR}WARNING{RESET_COLOR}: "
                  f"Headings increased past H6 on export - {date_str} {entry.title}",
                  file=sys.stderr)
""CHANGED LINE""
        return f"{heading} {date_str} {entry.title}\n{newbody}\n"

    @classmethod`

Sorry, for my english and if this is not the procedure. This is my first time in githit and i am not developer.

**Comment by wren** [comment]
Hi! Thank you for reporting this issue, and thank you for looking into it (especially since you're not a developer).

Projects tend to get a bit quiet near the end of the year due to the holidays, but don't worry, we'll take take care of this soon.

**Comment by dbxnr** [comment]
I just checked this out and it seems to be fine.

![markdown](https://user-images.githubusercontent.com/17500013/74301025-a0908a80-4d49-11ea-9c59-0f4fd9711146.png)

**Comment by pggoncalves** [comment]
Hi,

Please check raw text exported. Some markdowns interpreters do not work
without newline character between title and text.

Thanks

A quarta, 12/02/2020, 03:43, dbxnr <notifications@github.com> escreveu:

**Comment by dbxnr** [comment]
As far as I can see jrnl is emitting a form of valid markdown, however there are multiple markdown specs. Can you let me know what interpreter you're using? I'd like to investigate further.

**Comment by MinchinWeb** [comment]
I think this is the same issue as #881. @pggoncalves : the fastest way to currently fix this is to ensure your entries always have a newline at the end of them, as the current exporter does not add anything to the end of your entries. That also probably isn't very satisfying. I believe the patch you alluded to should also likely work.

c.f. #779 and #881
