### ISSUE TITLE
On error, dump crash log to local storage with option to submit it

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#771]
## Feature Request

It would be nice to make it easy as possible to report and troubleshoot fatal errors with jrnl. A crashlog submission tool could provide us with this.

Some ideas so far:

* Using a tool like [Sentry](https://sentry.io/for/open-source/) as an intake, but also just showing the path to the file if the user wants to manually submit it (or review it, etc.)
* Privacy first! Make it absolutely clear that crash logs will only be sent if the user explicitly requests it
* Might even want a config option to prevent the writing of this file, for users that want that much more piece of mind

This comes out of issue #764 regarding analytics. See also issue #727 regarding a command line diagnostic argument - similar, but not quite the same, since this issue is about error handling whereas that one is about initiating a diagnostic.

**Comment by ParaplegicRacehorse** [comment]
I was fairly vocal about #764. I am completely okay with dumping a file. May I suggest that the defaults are to dump a cleartext file if journal-file is not encrypted, and a ciphertext file if the journal-file is encrypted, using the same cipher-key as the journal-file?

**Comment by micahellison** [comment]
Thinking about this some more since it popped in stale. Maybe it's still best not to have the application dump files here and there by default. But we could still possibly implement better error handling, and output more useful information into the console for users to copy-paste if they do want to report it.
