### ISSUE TITLE
Unable to use Visual Studio Code as editor on Windows 10

### ISSUE THREAD

**Issue by haytaylan** [jrnl-org/jrnl#775]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: 2.1.1
  - Installed via pip
  - Windows 10

* **What is the current behavior?**

    I am using Visual Studio Code as my editor. When i run jrnl, the editor creates a temp file which is deleted immediately and i am unable to input anything. I have tried this on two Windows 10 PC's and it behaves the same.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Set the "editor:" field in jrnl.yaml file to use the Visual Studio Code .exe.
2. type "jrnl"
3. An editor in Visual Studio is opened but the file is immediately deleted.
4. jrnl returns the following: _[Nothing saved to file]_

* **What is the expected behavior?**

    I am able to work with vscode under my Windows 7 PC at work. The vscode editor opens and jrnl lets me edit my inputs. When i close the editor, jrnl saves my input to my actual journal.

I am guessing this might be an issue about access privileges to Windows 10 Temp folder

**Comment by wren** [comment]
Hi! Can you please paste the exact line you have put for editor from your config?

Also, did you follow the process on the following page? https://jrnl.sh/recipes/#external-editors

**Comment by haytaylan** [comment]
My sincere apologies, appearently i forgot to add the ```--wait``` argument. 
Thank you for this great app!

**Comment by g-berthiaume** [comment]
Just to clarify the solution:
You need to put the following in your config file:

```yaml
editor: 'C:\...\Code.exe --wait'
```
