### ISSUE TITLE
How to Add Typora as external editor ?

### ISSUE THREAD

**Issue by builtbyjordan** [jrnl-org/jrnl#776]
## Support request
**Environment**
  - jrnl version 1.9.8
  - installed Jrnl  homebrew
  - Operating system: MacOS

* **What are you trying to do?**
Use [Typora](https://typora.io/) as an external editor 
* **What have you tried?**
Editing the .jrnl_config and adding an external editor recipe similar to what is seen in the documentation. However I'm a bit of a novice. I'm thinking maybe something needs to be added to my bash profile or maybe a specific flag is necessary, I'm not sure how to go about finding those kind of things out. Is there a common scheme in how to go about adding any kind of editor or is it case by case? 

* **Other information** 
https://jrnl.sh/recipes/#external-editors

**Comment by wren** [comment]
I'm not familiar with that editor, but looking at their docs (http://support.typora.io/Use-Typora-From-Shell-or-cmd/), it seems you can open it from the command line with `open -a typora`. So, to use with jrnl, you should put that command in the`editor` field in your config.

**Comment by builtbyjordan** [comment]
@wren thankyou kindly for this prompt reply. Whadayaknow it worked perfectly using
 `open -a typora -w` - this allowed for it to open up a new file and updated the journal after I exited. Great app keep it up! I'll see what I can do to pitch in and do my part to keep this app going!
