### ISSUE TITLE
File locking error when editing in windows

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#790]
- Jrnl version: 2.1.1
  - How you installed Jrnl: pip
  - Operating system: Windows

Steps to repro:
* Edit the configuration yaml to specify an editor such as "subl -w" or "notepad"
* Run jrnl --edit
* Change anything
* Try to save

Expected results: The file should save just fine. Once you close the editor, the journal should be edited.

Actual results: There's an I/O error. e.g. in Sublime, it's "Error: The process cannot access the file because it is being used by another process."

Looks like this shown up before in #220, #327, #361, #390.

**Comment by wren** [comment]
Wowza. This was an old one.

Good catch!
