### ISSUE TITLE
Python 3.9 build is failing with import error ('Mapping' from 'collections')

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#793]
The tests that we run on the nightly version of Python have started failing with this error:

```
[ImportError]                                                    
cannot import name 'Mapping' from 'collections' (/home/travis/virtualenv/pyt  
hon3.9-dev/lib/python3.9/collections/__init__.py)
```

I haven't had a chance to look into this, yet, but 3.8 just came out, and 3.9 is still in alpha, so we have some time. But we should fix this soon. 

Example: https://travis-ci.com/jrnl-org/jrnl/jobs/274130952

**Comment by clbarnes** [comment]
Abstract base classes are now in `collections.abc` rather than `collections`; pretty sure is the case for all versions jrnl supports. This should have raised deprecation warnings for a few versions (`collections.abc` was new in 3.3) so you may have some warning-silencing code you can get rid of once the change is made.

**Comment by wren** [comment]
@clbarnes Thanks for looking into this! That seems like it would be an easy fix if it were in jrnl. I guess we'll have to do a dependency audit to deal with this.

**Comment by clbarnes** [comment]
My strategy was just to install the environment and grep in site-packages for `Mapping`, but I only got as far as using the version from pip as poetry disagrees with my dev setup. Does that sound like it would be a sufficient strategy? Wheels get unzipped when they're installed, right?

**Comment by dbxnr** [comment]
passlib is definitely importing `collections.Mapping` - (pwd.py:13) 
pytz is importing it as well, although it's checking for an ImportError (lazy.py:8)

There are a few others, but they're checking the python version before importing (Py2 compatibility)

**Comment by clbarnes** [comment]
Hm, it looks like passlib also has it in a `try`/`except` (in master, anyway). Are the dependency versions in pyproject up to date?

**Comment by wren** [comment]
@clbarnes The dependencies in the lock file should be up to date as of about 2 weeks ago.

**Comment by MinchinWeb** [comment]
It appears the actual issue here (or at least the first time Travis hits it) is with `virtualenv`. Upstream ticket --> https://github.com/pypa/virtualenv/issues/1449

Per the upstream ticket, this should be fixed in newer versions of `virtualenv`...

In any case, this is why the dev version of Python is on the testing matrix...

**Comment by wren** [comment]
Good find, @MinchinWeb!

**Comment by micahellison** [comment]
According to the [Python 3.9 release schedule](https://www.python.org/dev/peps/pep-0596/), 3.9 final will be out on October 5 this year. It's critical to have a fix or workaround in place by then.

**Comment by wren** [comment]
I would love to prioritize this for the next version (v2.4). If anyone wants to submit a PR, I would really appreciate it, and will make sure to fast-track it.

**Comment by ivanguy** [comment]
https://docs.python.org/3.9/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code

Aliases to Abstract Base Classes in the collections module, like collections.Mapping alias to collections.abc.Mapping, are kept for one last release for backward compatibility. They will be removed from Python 3.10.

**Comment by wren** [comment]
Fixed by #909

**Comment by honsour72** [comment]
I hope it will helps somebody...

On ubuntu 20.04 LTS I upgrade python3.8.10 up to 3.10.10

So I caught next error while use _any poetry command_:

```python
cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

I open `/usr/lib/python3/dist-packages/html5lib/_trie/_base.py` and transform this:

```python
from collections import Mapping
```
into this:

```python
from collections.abc import Mapping
```

So, after it _any poetry commands_ work clearly

**Comment by wren** [comment]
@honsour72 I don't think you should have to do that manually. Did you remember to upgrade poetry after upgrading Python?

**Comment by honsour72** [comment]
> @honsour72 I don't think you should have to do that manually. Did you remember to upgrade poetry after upgrading Python?

Yes, your are exactly right
But i had no choices at that moment
