### ISSUE TITLE
Export using custom templates does not seem to work

### ISSUE THREAD

**Issue by stavshamir** [jrnl-org/jrnl#813]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: 2.1.1
  - How you installed Jrnl: pip3 install jrnl
  - Operating system: centos 7

* **What is the current behavior?**
Custom templates don't seem to be working.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
Running `jrnl --export sample` (as documented in the tests) fails with the following output:
```
jrnl: error: argument --export: invalid choice: 'sample' (choose from 'boxed', 'fancy', 'json', 'markdown', 'md', 'tags', 'text', 'txt', 'xml', 'yaml')
```

I looked through the code and it seems that the template file should be in a specific directory. I looked in the installation dir, and it is indeed there:
```
$ ls /usr/local/lib/python3.6/site-packages/jrnl/templates
sample.template
```
* **What is the expected behavior?**
The journal is exported using a custom template.

* **Other information**
There seems to be no documentation for using custom template exports.
Related to:  Export code is a mess #713.

**Comment by wren** [comment]
Oh, ha. Well, if templates don't work, then refactoring becomes easier, since we don't have to worry as much about backward compatibility.

**Comment by wren** [comment]
Closing in favor of #713

**Comment by wren** [comment]
We should refactor this to use an established library to work.

**Comment by micahellison** [comment]
I'm not sure the templates have ever worked -- they certainly haven't in the last two years that I've been working on this project. However, we're planning on implementing similar functionality through plugins instead of templates (see #1239) so I am closing this issue.
