### ISSUE TITLE
--tags vs --export tags

### ISSUE THREAD

**Issue by krister-ts** [jrnl-org/jrnl#814]
## Feature Request

`--tags` will print tags
`--export tags` will also print tags

`--export tags` will make use `-o` output file, if specified
`--tags` does not make use of the `-o` option

**Why must `-o` be restricted to `--export`?**

I find `jrnl --tags -o file.txt` much easier to type than `jrnl --export tags -o file.txt`.

**Comment by micahellison** [comment]
The export functionality is kind of in flux right now, with a couple different layers of varying complexity that need to be fixed up (documented in #713). For that reason, I'm hesitant to start adding this `-o` parameter to parameters that aren't specifically about exporting.

However, you can still keep your commands concise by using your shell's built-in output features, like so:
```
jrnl --tags > file.txt
```

**Comment by krister-ts** [comment]
It seems to me that all `--export` does is format the output and `-o` redirects to a file.
Would it not make more sense to make `--format` an alias for `--export` and have `-o` always output to file?

**Comment by micahellison** [comment]
It would! I think this is worth looking into as we get into #707.
