### ISSUE TITLE
Missing .jrnl_config

### ISSUE THREAD

**Issue by abarl** [jrnl-org/jrnl#815]
## Support request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**

  - Jrnl version: (run `jrnl -v`)
2.1.1
  - How you installed Jrnl
pip3
  - Operating system [MacOS, Linux, Windows?]
Debian 10.2
* **What are you trying to do?**
Configure jrnl to use vim, but I can't find the .jrnl_config file.
* **What have you tried?**
I checked ~/.jrnl_config and also searched for the file but couldn't find it. I tried uninstalling and reinstalling but no luck.
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by UtahDave** [comment]
My default config was found here on Ubuntu:

```
~/.config/jrnl/jrnl.yaml
```

Hopefully that will help.

**Comment by micahellison** [comment]
Hi there, you should be able to find the path to your config file by running the following:
````
jrnl -ls
````

**Comment by abarl** [comment]
Thank you both! I found the config file where Dave specified and confirmed with jrnl -ls.
