### ISSUE TITLE
Add tags to -from / -until

### ISSUE THREAD

**Issue by krister-ts** [jrnl-org/jrnl#818]
## Feature Request

I would like to be able to view from and/or until the first/last instance of a tag with `-from` and `-until` .

**Examples:**

What did I do since last commit?
`jrnl project -from last @commit`

How did I get it working?
`jrnl project @change -from first @error -until last @error`

Did John Doe sell his calling list???
`jrnl calls @SpamCall -from first @JohnDoe`

**Comment by wren** [comment]
Hrmm, I think this is an interesting idea. The implementation as suggested doesn't quite work with our current syntax, but I think these types of queries will get a lot easier with options we're working on (like sort order, and refactoring the cli).

Not sure where that puts this ticket but stay tuned.

**Comment by wren** [comment]
Closing for now, but putting into ideas bucket to maybe revisit later.
