### ISSUE TITLE
What does the template option in the configuration do?

### ISSUE THREAD

**Issue by RaghavRao** [jrnl-org/jrnl#827]
## Support request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**

  - Jrnl version: 2.1.1
  - How you installed Jrnl: pip install jrnl

  - Operating system [MacOS, Linux, Windows?]: Fedora 31 (Linux)

* **What are you trying to do?**

What is the template option in jrnl.yaml? This is not mentioned in the Advanced Usage guide on the webpage. Is this option to be changed to use `jrnl < template.txt` ?

**Comment by heymajor** [comment]
Go one below that to [recipes](https://jrnl.sh/recipes/).

Relevant piece:

### Using templates

Say you always want to use the same template for creating new entries.
If you have an [external editor](../advanced) set up, you can use this:

```sh
jrnl < my_template.txt
jrnl -1 --edit
```

Another nice solution that allows you to define individual prompts comes
from [Jacobo de
Vera](https://github.com/maebert/jrnl/issues/194#issuecomment-47402869):

```sh
function log_question()
{
   echo $1
   read
   jrnl today: ${1}. $REPLY
}
log_question 'What did I achieve today?'
log_question 'What did I make progress with?'
```

**Comment by RaghavRao** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thank you. But do I need to change the "template" option in the yaml file? The recipe does not seem to use the yaml file and seems independent of it, so I was curious.                                                                                                                                                                                                                                                                                                                         From: notifications@github.comSent: January 31, 2020 22:46To: jrnl@noreply.github.comReply-to: reply@reply.github.comCc: raghav.rao32@gmail.com; author@noreply.github.comSubject: Re: [jrnl-org/jrnl] What does the template option in the configuration do? (#827)  Go one below that to recipes.
Relevant piece:
Using templates
Say you always want to use the same template for creating new entries.
If you have an external editor set up, you can use this:
jrnl <  my_template.txt
jrnl -1 --edit
Another nice solution that allows you to define individual prompts comes
from Jacobo de
Vera:
function log_question()
{
   echo $1
   read
   jrnl today: ${1}. $REPLY
}
log_question 'What did I achieve today?'
log_question 'What did I make progress with?'

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by heymajor** [comment]
Good question; it's not very clear.

After some tinkering, here's what I think is being said:

If you put the function text block on your `.bashrc':

```sh
function log_question()
{
   echo $1
   read
   jrnl today: ${1}. $REPLY
}
log_question 'What did I achieve today?'
log_question 'What did I make progress with?'
```
...you'll be prompted when you reload your shell (`source ~/.bashrc`). Your answers will be saved at the `default_hour` and `default_minute` you set in your config.

Commented on these two commands:

```sh
jrnl < my_template.txt     # Imports my_template.txt as the most recent entry
jrnl -1 --edit       # Opens the most recent entry in the editor 
```

So to answer your original question: The `template` setting is either false or a double quoted path to the file you want to open in your editor to start your entry like this:

```sh
...
tagsymbols: "@"
template: "/path/to/template.txt"
timeformat: "%Y%m%d %H:%M"
version: "2.1.1"
```

**Comment by micahellison** [comment]
Thanks @RaghavRao and @heymajor for the question and answer. Sounds like we need to update the documentation. I'm making some notes here on what to change when I get to it:
* Modify the "advanced" page to mention the template field
* Modify the template info in the recipes page to mention the configuration file
* And, after some quick testing - specify that it won't use the template if you enter a subject line as a command line argument

**Comment by heymajor** [comment]
> * Modify the "advanced" page to mention the template field
> * Modify the template info in the recipes page to mention the configuration file

I submitted a pull request that should hopefully take care of these

**Comment by micahellison** [comment]
Oh I see! PR #829. Like a half hour before that comment. I'll take a look.
