### ISSUE TITLE
Add new entries after old ones

### ISSUE THREAD

**Issue by davidoskky** [jrnl-org/jrnl#849]
## Feature Request

Hi,
when I add one entry for the current day, it is stored with the hour I entered it.
If another day I want to add something to that entry, I have to check the hour I entered that one in order to make it appear later, otherwise the default setting will create the entry at 09:00, and that may be before the old entry.
What I advise is to change the default behavior when adding entries without an hour.
therefore the command `jrnl yesterday:` would first check if there are entries that day.
If an entry is present it would add the new entry with a timestamp after the old one, say one minute or one hour, if no entry is present then it can default to 09:00.
If I want to enter a specific hour it's not a problem because the normal command o specify the time can be used.

This modification in the behavior of the program will make it more useful in my opinion, because I assume that what I write later, will have happened later, or that I want anyway to visualize it after.

**Comment by wren** [comment]
Hi, sorry for the slow response. Thank you for submitting a feature request. 

I've been thinking about this one, and the implementation seems like it would seriously complicate the way we currently save a journal. I can see why this feature would be useful, though. Can you tell me what you think about the following idea?

The 09:00 default time is configurable. So, if you want any entry without a time to come later in the day than ones with a time, I think you can update your config to use 23:59 as the default time That seems like it would accomplish your stated goal without changing any current functionality.

Does that work for you?

**Comment by davidoskky** [comment]
I just tried and it works exactly how I need it to; I really didn't think about it before.
Feel free to close this issue if the implementation of an alternative function is too difficult.
In that case, though, it might be good to mention this workaround in the documentation, as I'm sure I am not the only one expecting this kind of behavior.

**Comment by wren** [comment]
I think we can probably add this to the documentation. I've been thinking we should add a tips and tricks section, and this could fit well into there.
