### ISSUE TITLE
Issue with -and and @tags order  if using jrnl profiles

### ISSUE THREAD

**Issue by mandarup** [jrnl-org/jrnl#853]
## Bug report

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`)  v2.2
  - How you installed Jrnl  - pip install jrnl   in virtualenv
  - Operating system [MacOS, Linux, Windows?] : MacOS

* **What is the current behavior?**

If custom profiles are set in jrnl.yaml
```yaml
journals:
  work:
     encrypt: false
     journal: /path/to/work.txt
```

There are two issues.

1)  with tags after `-and` as specified in the documents, it throws error
```sh
$ jrnl work -n 5 -and @pineapple @lubricant
jrnl: error: unrecognized arguments:
```

Works as expected (&)  if specify `-and` flag is after the tags
```sh
$ jrnl  work @pineapple @lubricant -and
```

2) But doesn't work if `-n` flag is used before tags
```sh
$jrnl work -n 5  @pineapple
jrnl: error: unrecognized arguments:
```

Works if `-n` flag is moved to the end after tags
```sh
$jrnl  work @pineapple @lubricant -and -n 5
```

**Comment by wren** [comment]
Yup!

This looks like more issues with our arg parsing. I've made an issue (#866) to deal with this once and for all. Please move discussion there.
