### ISSUE TITLE
Jrnl website - download links

### ISSUE THREAD

**Issue by laviniageorgescu** [jrnl-org/jrnl#855]
Hi! The jrnl website, which is where one gets redirected for download, still points to home-brew as being an option for installation. However, jrnl is only being updated on pip, so using home-brew gives access to 1.9.8 or something as opposed to 2.* of Pip. Please update for future peeps to save time trying to use this nifty tool! Cheers

**Comment by wren** [comment]
Hi! Homebrew core has finally updated with v2.2. `brew install jrnl` works again, and we intend to keep it updated alongside with `pip`. 

Also, we have a brew prerelease tap if you want to try some of our beta releases (they're updated more often than the homebrew core repo). If you're interested, you can install like this:
```
brew tap jrnl-org/prerelease
brew install jrnl-beta
```

Please note, beta releases are less table, so make sure to backup your journals if you go this route.
