### ISSUE TITLE
Error creating a journal

### ISSUE THREAD

**Issue by beverlyhillz** [jrnl-org/jrnl#859]
[Error: /home/user/Documents is a directory, but doesn't seem to be a DayOne journal either.

**Comment by micahellison** [comment]
It looks like you've entered the path of a directory when creating a jrnl. To fix it, edit the default journal in your [config file](https://jrnl.sh/advanced/#configuration-file) to point somewhere else, such as `/home/user/Documents/jrnl.txt`

**Comment by wren** [comment]
Also, v2.3 (currently in beta) supports saving journals into a directory structure. If you'd like to test it out, it might have the functionality you're looking for.
