### ISSUE TITLE
Allow multiple editors in config file

### ISSUE THREAD

**Issue by jayrod** [jrnl-org/jrnl#874]
## Feature Request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **What is the motivation / use case for changing the behavior?**
Much like being able to specify a default and other set of journals to log stuff to. I would like to be able to specify a default and other type of editor that can be referenced by flag. 

* **Please provide examples of the usage**
By default I will use vim to quickly edit items. But I also would like to use Retext when I'm dealing with markdown. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wren** [comment]
So, this would be something like the below?

`jrnl --editor="vim +someflag" --edit -3`

**Comment by jayrod** [comment]
I am not sure what the +someflag would be for. But I assume 

jrn --editor"vim" --edit 3 

would open journal item 3 in the vim editor.

**Comment by wren** [comment]
We are going to implement this as part of the new arg parsing library.

**Comment by wren** [comment]
Hi! This issue got lost in the shuffle, but it's already been fixed by the new `config-override` flag. You can see the documentation here: https://jrnl.sh/en/stable/advanced/#modifying-configurations-from-the-command-line

For the example above, it would look something like this:
```sh
jrnl --config-override editor "vim" --edit -3
```
