### ISSUE TITLE
"flag is 1" in time.py

### ISSUE THREAD

**Issue by jemostrom** [jrnl-org/jrnl#878]
## Bug report

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`) 
    2.2
  - How you installed Jrnl 
    via brew
  - Operating system [MacOS, Linux, Windows?]
    macOS

On line 60 in jrnl/time.py should it really say

`if flag is 1`

and not

`if flag == 1`

???

**Comment by wren** [comment]
Confirmed. We should be able to merge a fix for this in with the current beta this weekend.

**Comment by wren** [comment]
We have a patch coming for this shortly (tests are running right now).
