### ISSUE TITLE
Question about export formats

### ISSUE THREAD

**Issue by jemostrom** [jrnl-org/jrnl#880]
## Support request

Hello! Thank you for reporting an issue!
If you would fill out the below points, that would make our process a whole lot easier!

* **Please tell us about your environment:**

  - Jrnl version: (run `jrnl -v`)
2.2
  - How you installed Jrnl
brew
  - Operating system [MacOS, Linux, Windows?]
macOS

* **What are you trying to do?**

Trying to understand how jrnl works :-)

I'm just playing around with jrnl having installed 30 minutes ago. My question if there is some plugin system for export formats or if I should write some script that convert JSON to the format I want?

More specifically I would like to have a format that is very close to the YAML format but I want to an empty line after the 'tags' line (multimarkdown format to separate meta info and content)

**Comment by wren** [comment]
Currently, we only have a few plugins, so feel free to use the JSON exporter in your script. We'll be implementing a standalone plugin system in a few versions, so watch out for that.
