### ISSUE TITLE
Electron deprecation warning when using vscode

### ISSUE THREAD

**Issue by g-berthiaume** [jrnl-org/jrnl#882]
## Bug report

This is more a heads up than a bug report:
When using vscode as my jrnl text editor, deprecation warnings are raised in the terminal:

```shell
(node:14320) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
(node:3232)  Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

* **Please tell us about your environment:**
jrnl version v2.2
pip
windows10 (using cmd)

**Comment by micahellison** [comment]
I get the deprecation warning with Visual Studio Code too, simply by running it from the command line and looking at the terminal once it loads. It's a non-issue for jrnl and hopefully should be resolved by the VS Code team soon.

**Comment by g-berthiaume** [comment]
I understand. I was hopping maybe a vscode flag could change this behavior.
Regards.

**Comment by micahellison** [comment]
Oh, I see, my apologies.

I don't think there's a solid workaround for this, though. I tried suppressing errors by piping them to `nul` in the `editor` field of the jrnl yaml config, but that doesn't seem to do anything. And I don't see any [VS Code flags](https://code.visualstudio.com/docs/editor/command-line) that would be of use.

I also tried playing around with a batch file using the [start](https://ss64.com/nt/start.html) command to invoke it with /wait, so the annoying errors would at least get piped to a different console window, but I didn't have much luck.

The next best solution I can think of feels a bit overcomplicated, but conceivably, one could create a launcher program in whatever language one is most familiar in to take the command line parameter and pass it to VS Code while suppressing the warning messages or keeping them in a separate window. But at that point, I think I would choose to just live with the warnings or pick a different editor.

**Comment by jkredzvr** [comment]
I'm getting the same warning

(node:26496) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\jrnl.exe\__main__.py", line 7, in <module>
  File "c:\python27\lib\site-packages\jrnl\cli.py", line 283, in run
    edited = util.get_text_from_editor(config, journal.editable_str())
  File "c:\python27\lib\site-packages\jrnl\util.py", line 171, in get_text_from_editor
    subprocess.call(shlex.split(config['editor'], posix="win" not in sys.platform) + [tmpfile])
  File "c:\python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 693, in wait
    _subprocess.INFINITE)

After exiting visual studio code, the program halts and doesnt return back to the console unless I terminal the program (Ctrl+C)
