### ISSUE TITLE
Version Number not updated on new version

### ISSUE THREAD

**Issue by MinchinWeb** [jrnl-org/jrnl#888]
## Bug report

The current version (2.3) had the version updated in `pyproject.toml` (which is where pip/poetry gets it's metadata), but not in `__version__.py` (which is where `jrnl --version` pulls from).

PR #887 adds a test to make sure this doesn't happen again, and fixes this time, but there is likely a bug in the release script.

* **Please tell us about your environment:**
  - Jrnl version: (run `jrnl -v`) -- Current develop branch (e489971877f28e930899962a7a64955159099baf), just after 2.3 cut
  - How you installed Jrnl -- via poetry from git
  - Operating system [MacOS, Linux, Windows?] -- Windows

**Comment by micahellison** [comment]
Confirmed from source, though with a caveat: it is reporting the version correctly in the PyPi release.

```
C:\>pipx install jrnl
...
C:\>jrnl --version
jrnl version v2.3
```

**Comment by wren** [comment]
I fixed the deploy script. We should still add these tests, though, to prevent this from happening again.

**Comment by wren** [comment]
@MinchinWeb I'm open to having this new test run along with the other tests for all PRs. I'm still concerned that it could lead to an unrelated test blocking builds, but we can change it if that starts to happen.

I'd still like to be able to run just this test for deployments, so maybe just adding a tag to it would be good enough.

For the version comparison, I'd still like to avoid adding a new library and reaching into Poetry's config file. If we change the output of `jrnl --version` (outputs `jrnl version v2.3`) to remove the "version", would that address your concerns about comparing the two? I've honestly thought about removing "version" in that anyway, so this would be a good excuse.

What do you think?

**Comment by MinchinWeb** [comment]
@wren I think changing the output of `jrnl --version` is a good answer. It still leaves us dependant on the API of poetry (specifically, the output of `poetry version`), but this seems less likely to be changed without being noticed, and keeps us from having to worry about a TOML library (which I was somewhat surprised to note wasn't in the standard library).

I'll work on the changes next time I have a chance.

**Comment by MinchinWeb** [comment]
@wren 

I've update the PR to use toml (rather than tomlkit) as toml was already being installed by black.

I've also added a tag to this test, so it can be specifically called before deployment (when it is most needed). To do so:

```
behave --tags=deployment_tests
```

This doesn't actually add this testing to the deployment script.

Re: pulling the version number from the *poetry* CLI output, rather than the *poetry* configuration file. See https://github.com/MinchinWeb/jrnl/tree/version-match-direct for my WIP (non-working) code.
