### ISSUE TITLE
New entry lost if directory missing/inaccessible

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [jrnl-org/jrnl#893]
## Bug report

* **Please tell us about your environment:**
   - jrnl version v2.2
   - brew
   - MacOS 

* **What is the current behavior?**
   - configure journals.work to ~/jrnl/work.txt without creating ~/jrnl
   - run `jrnl work`
   - write a masterpiece
   - `:wq`
   - error stack trace below
   - work in progress gone

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
   - ibid

* **What is the expected behavior?**
   - Use a non-temporary directory for work-in-progress so that failed updates are preserved
   - Create the directory when missing

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/cli.py", line 362, in run
    journal = open_journal(journal_name, config)
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 391, in open_journal
    return PlainJournal(name, **config).open()
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 80, in open
    self.create_file(filename)
  File "/usr/local/Cellar/jrnl/2.2_1/libexec/lib/python3.8/site-packages/jrnl/Journal.py", line 105, in create_file
    with open(filename, "w"):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/cbreym/jrnl/work.txt'
```

**Comment by wren** [comment]
Confirmed on v2.3. We should create directories that don't exist when checking for this and/or put the temp file back after a crash happens.

**Comment by eshrh** [comment]
I think that a temp file just adds unnecessary complications. I don't see a problem with simply creating the directory when it doesn't exist and creating the file like usual. 

I can envision a situation in which the user simply mistyped the path of their new jrnl file. Perhaps we can have a prompt asking them whether to create the new directory, enter a new path for now, or cancel and delete their entry.

I'm working on this, assuming nobody else is already.
