### ISSUE TITLE
jrnl should provide more information than "UpgradeValidationException" when upgrade from version 1.x fails

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#894]
There is a check in the 1.x -> 2.x upgrade process to compare the count of entries between the original journal and the upgraded journal. If the counts differ, the UpgradeValidationException fires and the upgrade fails with a prompt to report the issue here.

A few people have reported this exception (#862, #892, #884, #664) but we've found it difficult to lock down what the exact cause is. And it's hard to do this, especially on a public forum, when the issue is with the journal entries themselves.

Maybe jrnl could show the number of entries in the old journal vs. the new one. Or, it could show a diff of all the entry titles between the two journals so the user would have a shot at identifying which entry has the text leading to this exception.

I also don't have steps to reproduce the issue for this - I tried adding in the line mentioned in #862 but it's still upgrading successfully.

**Comment by eshrh** [comment]
not sure if this is still a problem. bump anyway
