### ISSUE TITLE
Allow --edit flag partway through an entry

### ISSUE THREAD

**Issue by rightbrace** [jrnl-org/jrnl#906]
I think it would be really helpful if the --edit flag could be invoked partway through an entry, for example:

```
$ jrnl now: I just finished homeschooling @Jane for the day. We talked about contractions, I explained that do not is often written as (oh, I\'ll need a lot of single quotes, but I really don\'t feel like escaping all of \'em) --edit
```
This would then open a file with all of the text up until the --edit already in it, so you could keep writing comfortably without copying out of your shell and pasting into your editor.

**Comment by wren** [comment]
Hi! Thanks for submitting an issue. 

It looks like the viewing flag (`-n 1` or `-1`) might already do what you're looking for. 

In your case, it might look something like this:
```sh
$ jrnl This is going to be a short entry, so I might as well just put it all on one line, although now it's getting too long and I want to move this into an editor.
[Entry added to default journal]
$ jrnl --edit -1
# Opens the above entry in your editor
```

Does that do what you're intending?

**Comment by rightbrace** [comment]
You know that is slightly less smooth than what I was intending (two commands over one) but I suppose it's close enough that adding the feature wouldn't be worth the additional complexity

**Comment by wren** [comment]
That's fair. I'll think about whether this makes sense to implement or not, but for now that should get you most of the way there.

**Comment by wren** [comment]
We're not in a great place to implement this right now (has to be done after refactoring the arg parsing code), but we've talked it over and think it makes sense for jrnl.
