### ISSUE TITLE
Searching for tags prints found entry multiple times

### ISSUE THREAD

**Issue by cschult** [jrnl-org/jrnl#926]
## Bug report

Searching for multiple tags prints the body of matching journal entrie as often as search tags were used. 

* **Please tell us about your environment:**
  - Jrnl version: v2.4
  - How you installed Jrnl: as user: pip install jrnl
  - Operating system [MacOS, Linux, Windows?] linux (archlinux)

* **What is the current behavior?**
Searching for multiple tags with flag "-and" prints header and body of each matching entry as often as search tags were used. The date of the matching entry is printed only once.

* **Please provide the steps to reproduce and if possible a minimal demo of the problem**
% ~ jrnl "note1 @tag1"
[Entry added to default journal]
% ~ jrnl "note2 @tag2"
[Entry added to default journal]
% ~ jrnl "note3 @tag1 @tag2"
[Entry added to default journal]
% ~ jrnl @tag1
2020-04-26 14:40 note1 @tag1
2020-04-26 14:40 note3 @tag1 @tag2

% ~ jrnl @tag2
2020-04-26 14:40 note2 @tag2
2020-04-26 14:40 note3 @tag1 @tag2

% ~ jrnl -and @tag1 @tag2
2020-04-26 14:40 note3 @tag1 @tag2note3 @tag1 @tag2

* **What is the expected behavior?**
jrnl -and @tag1 @tag2 should print the body of the matching entry only once.

* **Other information**

**Comment by wren** [comment]
Confirmed on: 
jrnl v2.4
macos 10.15
python 3.8.0

It looks like the output is repeated `n` times where n is the number of tags you had in your search. This is happens with `jrnl @tagone @tagtwo` and `jrnl -and @tagone @tagtwo`, so it's not exclusive to the `-and` flag.
