### ISSUE TITLE
Brew not (yet) updated to 2.4

### ISSUE THREAD

**Issue by metbril** [jrnl-org/jrnl#929]
I noticed that jrnl has updated to v2.4, but my Home-brew still only has v2.2. When will the brew recipe be updated?

```zsh
% jrnl --version
jrnl version v2.2
% brew list jrnl
/usr/local/Cellar/jrnl/2.2_1/bin/jrnl
/usr/local/Cellar/jrnl/2.2_1/libexec/bin/ (18 files)
/usr/local/Cellar/jrnl/2.2_1/libexec/lib/ (1756 files)
/usr/local/Cellar/jrnl/2.2_1/libexec/.Python
```

**Comment by wren** [comment]
Yup, sorry about this! We don't have this part of the release process automated, yet (it's a surprisingly obtuse process). We're working on it (#686), but it's slow-going. We've just been updating it by hand for a now.

If anyone wants to send over a PR to automate the brew release, we would really appreciate it!

**Comment by wren** [comment]
We'll skip brew straight to v2.4.2 when that comes out, since v2.4 had a bug.

**Comment by alichtman** [comment]
I just ran `brew install jrnl` and got `jrnl version v2.4.1`.

**Comment by wren** [comment]
@alichtman That's weird. I guess somebody updated it for us?
