### ISSUE TITLE
Running testing suite leaves extra directories in environment

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#939]
### Environment
  - Jrnl version: (run `jrnl -v`)
  - How you installed Jrnl
  - Operating system [MacOS, Linux, Windows?]

### Current behavior
After running `make test` (specifically the `behave` step), there are some directories left over after the tests are finished running (e.g. `bug768/`).

**Repro steps**
1. Run `make test`
2. Wait for tests to finish
3. Run `git status`
4. See that there are now multiple untracked files and/or directories

### Expected behavior
The testing suite should clean up after itself, and leave the dev environment like it found it.

**Comment by MinchinWeb** [comment]
...and these directories should probably be created in the system's temporary folder to avoid accidentally messing up work directory.
