### ISSUE TITLE
Ability to suppress date in display.

### ISSUE THREAD

**Issue by joshdoyle** [jrnl-org/jrnl#950]
## Feature Request
I would like the option to suppress the time when displaying jrnl entries.
The date is irrelevant to me in some contexts and takes up valuable space especially with tiled windows. I use jrnl to log many things that I am doing throughout the day as a quick reference to something I was doing earlier. It works well for getting me on track when I've been interrupted. I always know that I'm viewing jrnl entries within the context of today.

I envision it could work like this.
jrnl -dt
06:57 test jrnl
06:59 this is a test

Thanks.

**Comment by wren** [comment]
This will be doable as part of the new arg parsing, where you can override config values on the command line. So, in your case, you'd be able to make an alias for something like `jrnl --timeformat='%H:%M'` forwhen you want the shorter format.

**Comment by wren** [comment]
On second thought, my comment above won't actually help you, since that would potentially erase the dates from all of your entries.

Maybe the fixing the template functionality would help this use case?
