### ISSUE TITLE
Entries duplicated when searching for several tags.

### ISSUE THREAD

**Issue by AntoineBrunet** [jrnl-org/jrnl#966]
### Environment
  - Jrnl version: v2.4.2
  - Install method: pip install jrnl 
  - OS: Linux 

### Current Behavior

When searching for several tags, all resulting entries are duplicated.
For instance, if the log only contains the following entry:

    [2020-05-27 18:21] My @foo entry. Here goes content.

The result is the following:

    $ jrnl toto @foo @bar
    2020-05-27 18:21 My @foo entry. My @foo entry.
    | Here goes content. Here goes content.

### Expected Behavior

Only one instance of each result should be produced.

    $ jrnl toto @foo @bar
    2020-05-27 18:21 My @foo entry.
    | Here goes content.

### Repro Steps

Simply search more than one tag. It does not matter if the tags exists or not, as long as there are some results.

### Other Information

When searching for more tags (3, 4, etc...), the results are replicated as many times as the number of searched tags.

**Comment by bar** [comment]
Hi @AntoineBrunet, please don't use my handle to document your code :) thanks!

**Comment by wren** [comment]
@bar You must get this a lot.

**Comment by wren** [comment]
Closing as dupe of #926.

@AntoineBrunet The fix is already merged, and will be out soon in v2.4.3-beta.
