### ISSUE TITLE
`--move` to move entries

### ISSUE THREAD

**Issue by guydebros** [jrnl-org/jrnl#968]
## Feature Request

`--move` to move entries

### Use Case/Motivation

There were some entries that I wanted to move into a separate journal for
archival purposes. Specifically, there was a tag that I no longer wanted to use
or see, but I didn't want to delete the entries. Instead, I wanted to set them
aside for review at a future date. I figured that at a time when I was ready to
read them, I might find some useful insights in those entries. Also, I have
trouble letting go.

### Example Usage

So I ran `jrnl @tag --edit`, copied and pasted the whole thing into a new file,
and then deleted them from the original file. I suppose another alternative
could have been

```
jrnl @tag > ~/tag.md
```

or maybe I could have used `--export`, but at the time I just did it the hard
way.

Then, more recently, I noticed the new `--delete` command (very cool, nice
work). I could now do

```
jrnl @tag > ~/tag.md && jrnl @tag --delete
```

...but I still have to confirm the deletions and, optionally, go add the new
journal to my config file.

I figured there might be a way to streamline all of that and bundle it up into
an easy-to-remember command, like

```
jrnl -until yesterday --move ~/newjournal.md
```

Doing it by hand isn't outrageously difficult, but maybe it's more involved than
it needs to be. The fewer steps, the better.

You could use a flag, like `-c`, (for "create") to automatically start a new
journal in the same directory and add it to the config file. Maybe `-c -d` moves
entries and then runs `--delete`. Or maybe `-c -x` moves them and then
batch-deletes them. `-c -k` would keep only the filtered entries and move all of
the _other_ ones into a new file. And so forth. The `-c` flag is only if you
want to deal with another `jrnl` journal. Otherwise it isn't necessary.

`-c -x` might require a `y/N` confirmation. But this isn't really a delete,
because the entries will exist in the other file before the deletion. And maybe
there can be some kind of undo function that would be a shortcut for
re-importing those entries and deleting the newly-created journal.

### Other information

- it's probable that I've overlooked a very simple way to do these things that
  already exists
- those flags might be useful elsewhere, too, if they don't conflict with
  anything

**Comment by micahellison** [comment]
Thanks for contributing this idea! I'm a little hesitant to add a move argument, but I do think it should be easier to achieve this with a script that could be shared as a recipe. For that to happen, we would need to be able to delete entries without confirmation (#973) and we'd need to be able to create journals from the command line (#330).

**Comment by eshrh** [comment]
@mzfr
Are you still willing to submit your PR for command line journal creation?

**Comment by mzfr** [comment]
Hey @eshrh , no I will not be working on any kind of PR.

**Comment by eshrh** [comment]
keep this open

**Comment by micahellison** [comment]
I don't think we should add a "move" argument, but this functionality will be possible via a short script when the two linked issues (#973 and #330) are resolved.
