### ISSUE TITLE
`--convert` to convert words into tags

### ISSUE THREAD

**Issue by guydebros** [jrnl-org/jrnl#970]
## Feature Request

`--convert` to convert words into tags

### Use Case/Motivation

I imported a ton of old blog posts spanning the last 17 years. None of them is
properly tagged. I like being able to run `jrnl --tags` and see what I write
about most. It would be cool to do this with words that aren't tagged yet, and
turn them into tags.

### Example Usage

```
jrnl -contains "word" --convert
```

`jrnl` adds a tag symbol in front of every instance of the word "word."

### Other information

- this could be used in conjunction with a `--count` command, which I will
describe separately
- there might be other uses for the `--convert` command besides tags

**Comment by micahellison** [comment]
Thanks for the idea. We generally don't like to add features that directly edit the bodies of entries -- it's a big expansion of the scope of this program, which is already pretty wide for a CLI application, and adds risk to users' data.

However, if/when we add support for metadata to entries, it seems like a feature that adds tags via metadata would be nice to have. It could work with the same filtering arguments that one would use for reading and editing.

**Comment by guydebros** [comment]
Got it! Thanks for doing your part in the eternal battle against feature creep. 😄
