### ISSUE TITLE
`--count` to do with words what `--tags` does with tags

### ISSUE THREAD

**Issue by guydebros** [jrnl-org/jrnl#971]
## Feature Request

`--count` to do with words what `--tags` does with tags

### Use Case/Motivation

While describing the `--convert` idea (#970) it occurred to me that I wouldn't
want to convert hundreds or thousands of words without taking a step back and
deciding which words to convert into tags. I did it recently, using DEVONthink
to generate a frequency list (most-used words at the top). Then I realized that
`jrnl` does this for tags. Could it do the same for words that aren't tags
[yet]?

### Example Usage

`jrnl --count -w` or something like that would list the top 10/20/whatever
most-used words.

`jrnl --count -e` would tell me how many entries are in my journal.

`jrnl -contains "foo" --count` would tell me how many times I used the word
"foo," even if one entry contains many instances of the word "foo."

`jrnl -contains "bar" --count -e` would tell me how many entries contain the
word "bar" at least once. I can look at the list and decide that since I use the
word "bar" in 80% of my entries, it may not be worthwhile to `--convert` into a
tag.

And so forth.

### Other information

- maybe the output can be combined so that it says "total of X instances in Y
  entries," so you wouldn't need `-e`
- maybe I should learn python and take a look at the code myself, but, with the
  exception of a few FileMaker scripts, I have no experience whatsoever with
  software creation/modification

**Comment by eshrh** [comment]
While I do think this is cool, I don't think this belongs in jrnl. Jrnl is first and foremost a journal writing application, not a journal analysis application. 

I imagine that the first two options shouldn't be too difficult to implement, but I'm not sure how to deal with the other two usages. `--count` would have two context-dependent meanings.

Either way, this is really not very difficult to recipe. try: `jrnl -until today | grep -o "word" | wc -l` for words.

As for entries, I thing that `jrnl -until today | grep -o -P '\d{4}-\d{2}-\d{2} \d{2}-\d{2}' | wc -l` should work.

**Comment by guydebros** [comment]
OK, no worries. And thanks for the recipes. I'll add them to `recipes.md` when I get to fixing that one up. :)

**Comment by guydebros** [comment]
The second one returns `broken pipe` but I'll need to figure out what that means. New learning!

**Comment by eshrh** [comment]
Not sure what went wrong. All I can say is (works on my machine)™. The only thing I can think of is that you're not using GNU grep, in which case -P might not work. Alternatively, although dirtier IMO, this works: `jrnl -until today | grep -P '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}' | wc -l`
