### ISSUE TITLE
add a "tags" array to the JSON export schema

### ISSUE THREAD

**Issue by ms82494** [jrnl-org/jrnl#974]
### Use Case/Motivation
I plan to archive my journals to a database. I would definitely want to be able to retrieve individual entries by selecting on tag values.

I understand that it's not hard to create that functionality outside of jrnl, but I feel it would make the JSON extract more useful.

### Example Usage
Instead of this:
{
  "title": "Bayern-Duesseldorf 5:0.",
  "body": "Great performance by the team today. D'dorf was never in this one. First time in a long time to see both Hernandez (1st half) and Odriozola (2nd half) defending. They both did their job very well. Especially Hernandez really shuts down the left inside. The most noticeable defender was Pavard, though, who scored two goals, though one of them may ultimately be blamed on the D'dorf defender who deflected it into the goal. The other one was a header, where Pavard managed to get into position against two defenders and beautifully redirected the ball into the net.\n\nHappy that a bunch of young players got the opportunity to play in the second half. I have to say, though, that Cuisance was noticeably weak. His passing was off and a free-kick that was meant to be a service wound up sailing at least 15' over the goal. @soccer @bayern",
  "date": "2020-05-30",
  "time": "13:44",
  "starred": false
}

I'd like to see this:
{
  "title": "Bayern-Duesseldorf 5:0.",
  "body": "Great performance by the team today. D'dorf was never in this one. First time in a long time to see both Hernandez (1st half) and Odriozola (2nd half) defending. They both did their job very well. Especially Hernandez really shuts down the left inside. The most noticeable defender was Pavard, though, who scored two goals, though one of them may ultimately be blamed on the D'dorf defender who deflected it into the goal. The other one was a header, where Pavard managed to get into position against two defenders and beautifully redirected the ball into the net.\n\nHappy that a bunch of young players got the opportunity to play in the second half. I have to say, though, that Cuisance was noticeably weak. His passing was off and a free-kick that was meant to be a service wound up sailing at least 15' over the goal. @soccer @bayern",
  "tags": ["soccer", "bayern"],
  "date": "2020-05-30",
  "time": "13:44",
  "starred": false
}

**Comment by eshrh** [comment]
This makes sense. There is already an imbalance of features in the exporters(the xml exporter already has an array for tags and frequency), so I think this would close the gap. 

I don't think this kind of tags array should be included for the other exporters because they don't have the same defined structure. I'll try this.

**Comment by eshrh** [comment]
@ms82494 If you want this feature immediately you can pip install my fork:
`pip install https://github.com/eshrh/jrnl.git@json-tags-array`

I'm still working on the rest, and of course because it is based on develop I can't guarantee anything.

**Comment by ms82494** [comment]
Wow, that was very fast! Thank you, @eshrh. I agree with your points on the XML and YAML exporters. On the question whether to include or leave off the ```@``` symbol in the tag strings, I don't have a preference.

**Comment by ms82494** [comment]
> @ms82494 If you want this feature immediately you can pip install my fork:
> `pip install git+https://github.com/eshrh/jrnl.git@json-tags-array`

I did install it, tested your fork, and it works just as expected. Thank you, @eshrh!

**Comment by eshrh** [comment]
@ms82494 you're welcome. XML is now also done btw, waiting on a @wren or @micahellison to review and hopefully merge.

**Comment by wren** [comment]
Hi, we're in the middle of a beta right now, so this won't get merged in just yet, but it's a good idea and we'll probably merge it into the very next version.
