### ISSUE TITLE
Decryption script no longer works

### ISSUE THREAD

**Issue by Alekhine51** [jrnl-org/jrnl#979]
Here is the script, pulled from jrnl.sh:
```
#!/usr/bin/env python3

import argparse
from Crypto.Cipher import AES
import getpass
import hashlib
import sys

parser = argparse.ArgumentParser()
parser.add_argument("filepath", help="journal file to decrypt")
args = parser.parse_args()

pwd = getpass.getpass()
key = hashlib.sha256(pwd.encode('utf-8')).digest()

with open(args.filepath, 'rb') as f:
    ciphertext = f.read()

crypto = AES.new(key, AES.MODE_CBC, ciphertext[:16])
plain = crypto.decrypt(ciphertext[16:])
plain = plain.strip(plain[-1:])
plain = plain.decode("utf-8")
print(plain)
```

And here is the terminal output upon running it:
```
Traceback (most recent call last):
  File "/home/daniel/bin/jrnl_decrypt", line 4, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

```
Any help on fixing this would be much appreciated. Really would rather not lose months of entries.

**Comment by eshrh** [comment]
That script needs the `pycrypto` module. It should *really* be included in the documentation.
Install it with `pip install pycrypto`.

**Comment by Alekhine51** [comment]
> That script needs the `pycrypto` module. It should _really_ be included in the documentation.
> Install it with `pip install pycrypto`.
> 

Thanks for your reply. FYI, it's `pip3` now. God knows why that was necessary.

Aaaaand I'm sorry to tell you it did not work. I installed pycrpto successfully, so we have progress, but when I ran it and entered my password, it returned this output:

```
Password: 
Traceback (most recent call last):
  File "/home/daniel/bin/jrnl_decrypt", line 20, in <module>
    plain = crypto.decrypt(ciphertext[16:])
  File "/home/daniel/.local/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

```
Any more ideas?

**Comment by wren** [comment]
@Alekhine51 Hi, sorry you're having troubles with the example decrypt script. Can you please give us some relevant info about the journal files your working with? What version of jrnl were they created with? Do you have jrnl installed now? If so, which version? Did you ever upgrade jrnl? What did your config file look like?

This info would be very useful for us to be able to help you better.

**Comment by guydebros** [comment]
Made some quick and dirty changes to the docs (#980) to emphasize this.

**Comment by Alekhine51** [comment]
@wren 
1. I'm afraid I don't know the version number of jrnl the file was made with. I can tell you I created the journal back in Ubuntu 18.04, then ported the journal over to 20.04 when I reinstalled, without decrypting it, which in hindsight was silly. 
2. I have jrnl installed now. Version 2.4.2, installed with `pipx`
3. I don't believe I ever upgraded jrnl in my previous install. If standard update and upgrade commands don't upgrade it, then I probably did, but I don't know if that's true for files installed with `pip`.
4. Config file was lost when I reinstalled, sadly.

**Comment by wren** [comment]
@Alekhine51 Ah, ok. Do you have a sense of how long ago this was? I'm trying to figure out if you used jrnl v1 or v2, which would change the format of the journal.

**Comment by Alekhine51** [comment]
@wren 

A few months ago, at most. I think I can say with certainty I made the file on jrnl v2.

**Comment by eshrh** [comment]
What happens if you just try `jrnl --decrypt` on your file? I'm not very knowledgeable about the encryption scheme, sorry.

**Comment by Alekhine51** [comment]
@eshrh  Just generates a blank file.

**Comment by eshrh** [comment]
That certainly sets off some alarm bells. Really the only reason I can think of that happening is either
1. The file you're trying to decrypt is different from the default jrnl(set in your `jrnl.yaml`) file that `jrnl --decrypt` is looking at. 
3. Worst case scenario, some or all bytes somehow got deleted off the file. This would also explain the earlier `multiple of 16` error.

Other than that, I'm all out of ideas.

**Comment by Alekhine51** [comment]
@eshrh That really worries me. Though I can't think how that could have happened? When I reinstalled I just copied over my home folder. Is it possible that some bytes were lost in transfer?

**Comment by eshrh** [comment]
I'm not an expert in cryptography, but the initialization vector is basically a random seed for AES, so if the IV gets corrupted then you might be out of luck. 

I did some digging, and it seems that the docs are outdated (yet again): 
The encryption scheme described in jrnl.sh is not the same as the one actually used by jrnl 2.0.
Jrnl2 uses the cryptography.Fernet, while jrnl1 does manual encryption/decryption like the script is built for. This also means that jrnl2 uses 128 bit AES, and not 256 AES like the frontpage of jrnl.sh says. @guydebros

Let's assume that nothing's been corrupted(that just sounds unlikely unless you're on a really old HDD). Given that the script didn't work, I think it's safe to assume that it was made with jrnl2. Not to mention that jrnl2 was released in sep2019. I'm still not sure why `jrnl --decrypt FILENAME` doesn't work. For a sanity check, could you create a new journal, encrypt it and decrypt it and make sure that everything works?

Either way, I'm working on writing a replacement script for jrnl2.

**Comment by eshrh** [comment]
Here it is:
```python
import base64
import getpass
import os
from pathlib import Path
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC


filepath = input("journal file path: ")
password = getpass.getpass("Password: ")

with open(Path(filepath),"rb") as f:
    ciphertext = f.read()

password = password.encode("utf-8")
kdf = PBKDF2HMAC(
    algorithm=hashes.SHA256(),
    length=32,
    salt=b"\xf2\xd5q\x0e\xc1\x8d.\xde\xdc\x8e6t\x89\x04\xce\xf8",
    iterations=100_000,
    backend=default_backend(),
)

key = base64.urlsafe_b64encode(kdf.derive(password))

print(Fernet(key).decrypt(ciphertext).decode('utf-8'))
```

Note that it depends on the package `cryptography` which you *should* already have if you really do have jrnl 2.

**Comment by Alekhine51** [comment]
@eshrh I think we're starting to get somewhere...

```
:~$ python3 ~/bin/jrnl_decryptV2.py 
journal file path: 'jrnl (3rd copy).txt'
Password: 
Traceback (most recent call last):
  File "/home/daniel/bin/jrnl_decryptV2.py", line 13, in <module>
    with open(Path(filepath),"rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: "'jrnl (3rd copy).txt'"
```
Sadly, I'm not good enough at Python yet to debug this. Thank you so much again for putting in all this work for me. I really do appreciate it. I've been using `jrnl` on and off for years now and I admire all the work that's been put it into it. It's the only piece of software I find I can write with.

**Comment by eshrh** [comment]
You just needed to not include the quotes when you entered the file path. I'm a little surprised that pathlib.Path doesn't catch this exception. It's really not that much work for me, I just extracted existing functionality that I also really appreciate!

**Comment by Alekhine51** [comment]
@eshrh It works! Thank you so, so much, I had daily entries going back to February. I would have been really depressed if I'd lost them.

**Comment by eshrh** [comment]
Can you reopen this issue until the documentation is updated with the new script and information?

**Comment by Alekhine51** [comment]
You got it.

**Comment by guydebros** [comment]
I added the new script to `encryption.md` (#980).
