### ISSUE TITLE
Change "master" branch to "release" 

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#983]
There's been lots of thoughtful discussion these past few weeks about the social ramifications of our use of language in software, and "master" is one term that keeps coming up in particular.

Changing `master` to `release` would be a nice way to address this.

It also makes our branching strategy a lot clearer, since most of our work is done on `develop` whereas releases are merged to the branch we currently call `master`. It could help reduce PRs to `master` that should've been set to `develop`. I've accidentally merged at least one PR to the wrong branch because of this confusion.

This change will need some changes to our build process but otherwise shouldn't have any effect on users.

**Comment by eshrh** [comment]
Doesn't really affect me, but if it makes some people happier or more comfortable at negative cost I guess I support it. Although, I'm sure you've heard the counterarguments about how `master` in this context might have nothing to do with the human crime but rather the idea of "mastering" something from an audio master record. recently. Surely we can't rename words like "master key," "masterpiece" or "remastered" right? I do support this change, but I don't like the general trend of where this is going. I'm scared of these kinds of changes being able to be easily propagated by a small virtue signalling population with everyone thinking that it might help someone else when it really helps nobody at all.

On the other hand, I'm also scared of people on the opposite side getting angry about things that really don't matter very much at all.

**Comment by micahellison** [comment]
It's true that it's a small change that isn't particularly substantive against the enduring legacy of slavery, and it's also true that the origins of this term are murky. But it's important for us to be welcoming to all, and using considerate language is one way to do that.
