### ISSUE TITLE
Deprecate Python 3.6

### ISSUE THREAD

**Issue by micahellison** [jrnl-org/jrnl#992]
We're refactoring the argument parsing code and are using some functionality that isn't supported until Python 3.7 (``ArgumentParser.parse_intermixed_args``). It will be a while before this code goes live, but in the meantime, we should add a deprecation notice if users are running Python 3.6.

I don't think this should significantly inconvenience users. 3.6 is about four years old and 3.9 should come out in a few months. Homebrew uses 3.8 with jrnl, and Windows users don't have a default version to worry about.

**Comment by wren** [comment]
Note to anyone reading this. The first version of jrnl that will require 3.7+ is v2.5.

v2.4.4-beta is coming out this weekend, and will be the last version of jrnl to support 3.6. Please update asap if you haven't already.
