### ISSUE TITLE
Paths starting with tildes (~) should always expand

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#998]
### Environment
  - Jrnl version: 
  - Install method: 
  - OS 
Likely all versions.

### Current Behavior

`~/template.md` doesn't work for a template file. Has this error:
`[Could not read template at '~/template.md']`

### Expected Behavior

The `~` should be expanded the same way it is for journal file themselves.
### Other Information

Current workaround is to use the full path to a file (e.g. `/Users/wren/template.md`) instead.

**Comment by wren** [comment]
There might be other instances of this behavior throughout the code, so the fix for this should include a simple function to handle properly expanding paths, and change all instances in the codebase to use this new function.

**Comment by minchinweb** [comment]
#704 solved a similar problem in the upgrade script.

The added code was:

```
path = os.path.expanduser(path)
```

**Comment by siimpragi** [comment]
After installation (during jrnl set up) I was a bit tripped up by `~` not being expanded as well. I manually set the default journal file as `~/journal.txt` but it was created in the current working directory instead. No biggie, but maybe the prompt message should be more clear since [`os.path.abspath(path)` is used](https://github.com/jrnl-org/jrnl/blob/b23c831da5b20122791279614b10e5a365dd18d9/jrnl/install.py#L91)? 🙂

```
➜  jrnl "now: This is a test. Something something something."
Path to your journal file (leave blank for /Users/siim/.local/share/jrnl/journal.txt): ~/journal.txt
Do you want to encrypt your journal? You can always change this later [y/N] y
Journal will be encrypted.
Enter password for new journal:
Enter password again:
Do you want to store the password in your keychain? [Y/n] n
Encrypted journal 'default' created at /Users/siim/Repositories/github.com/jrnl-org/jrnl/~/journal.txt
[Entry added to default journal]
```

**Comment by micahellison** [comment]
Thanks @siimpragi for reporting this issue in the new journal path.

To recap, a resolution to this bug should include the following:
- [ ] create a simple function for expanding paths
- [ ] modify current ~ expansion code to use that function
- [ ] fix ~ in the template paths
- [ ] fix ~ in the new journal path
- [ ] review code for other paths and fix them as necessary
