### ISSUE TITLE
Importing to directory-based journals doesn't do anything, and has incorrect message

### ISSUE THREAD

**Issue by wren** [jrnl-org/jrnl#999]
### Environment
  - Jrnl version:  v2.4.3
  - Install method:  pipx
  - OS  macos 10.15.3

### Current Behavior

```
$ j -2 --export text | j dirtest --import
[2 imported to default journal]
```

The above should be importing to the `dirtest` journal, but it says it's importing to default (it's actually not importing anywhere).

### Expected Behavior

Users should be able to import journal entries to directory-based journals the same way they can to single-file journals.

### Repro Steps

1. Make a directory-based journal (create an empty directory, and add to config as `dirtest` or whatever)
2. Add an entry to it (e.g. `jrnl dirtext some new entry`) to make sure it works
3. Try to import any number of entries to it from another journal (`jrnl --export text | jrnl dirtest --import`, or `jrnl --import -i journal_file.txt`)
4. Observe the message saying entries were imported to default journal
5. Observe entries were not actually imported to either journal (`jrnl -1` and `jrnl dirtest -1` or however you want to try to find those entries)

**Comment by gimzmoe** [comment]
jrnl version v2.4.5
I was looking into trying the directory-based jrnls, but this appears to be the case for me too.
